### ISSUE TITLE
Analyze what to do with the harvest sources without headers:

### ISSUE THREAD

**Issue by avdata99** [GSA/datagov-ckan-multi#112]
Check the harvest sources without headers:
 - http://www.fhfa.gov/data.json	FHFA JSON
 - https://raw.githubusercontent.com/gbinal/data/master/datasets/doi_cas.json	DOI CAS datajam
 - https://raw.githubusercontent.com/gbinal/data/master/datasets/hhs_cas.json	HHS CAS JSON
 - https://raw.githubusercontent.com/gbinal/data/master/datasets/doj_cas.json	DOJ CAS datajam
 - http://phlapi.com/data.json	phlapi json

### Tasks

* [ ] Ask GSA what to do with this sources
* [ ] Fix our script if necessary

### Analysis

Read these notes: https://gitlab.com/datopian/ckan-ng-harvest/issues/35#note_201314023

**Comment by thejuliekramer** [comment]
Spoke with @acouch about this. We are going to not accept datasets without headers. We are logging these errors and will notify the agencies in the future about this.
