### ISSUE TITLE
CCO Documentation: DevOps Guide

### ISSUE THREAD

**Issue by jqnatividad** [GSA/datagov-ckan-multi#123]
* [x] Overview
  * [x] Architecture diagram of key sub-components
* [x] Installation and quick start
    * [x] Supported clouds
* [x] Kubernetes setup etc. Docker files etc
* [x] UI setup and usage
* [x] Setting up logging
* [x] Security

**Comment by aluminiumgeek** [comment]
DevOps Guide is available [here](https://github.com/datopian/ckan-cloud-operator/blob/full-documentation/docs/DOCUMENTATION.md#devops-giude)

**Comment by jqnatividad** [comment]
On Friday, Oct 11, @adborden , @woodt and I attempted to do a fresh CCO install just using the docs in a 2.5+ hour co-working session.

From that exercise, it was apparent that the DevOps guide to install CCO on AWS will need to be refined with more detail as we were not able to deploy CCO on GSA's AWS account.

This will have to rollover to Sprint 11 as the docs will need to be rewritten.

**Comment by tkprmr** [comment]
Joel had review on this with Aaron and Tom W.  New tickets needs to be created for any additional documentation updates. 
Need to check with Aaron whether this can be closed after new update tickets are created.

**Comment by jqnatividad** [comment]
Closing this as CCO deployment is being automated and the associated documentation revamped to reflect this (#167).
