### ISSUE TITLE
CCO Documentation: User Guide

### ISSUE THREAD

**Issue by jqnatividad** [GSA/datagov-ckan-multi#124]
* [x] Architecture
* [x] Contributing
* [x] Repos
* [x] Features wanted (link to issues)

**Comment by aluminiumgeek** [comment]
User Guide section is [here](https://github.com/datopian/ckan-cloud-operator/blob/full-documentation/docs/DOCUMENTATION.md#user-guide)

**Comment by adborden** [comment]
@aluminiumgeek I'm reading through the User Guide, but it's unclear to me who the audience is. Can you clarify what the roles of the system are, maybe include these descriptions in the docs?

For example, the User guide talks about creating databases, but to me this is a task for an Operator (maybe should part of the DevOps guide)?

**Comment by adborden** [comment]
I would've though a User is a dataset owner or a CKAN administrator, someone consuming the CKAN bits, not the platform bits.

**Comment by jqnatividad** [comment]
@adborden I'll update the docs using the following personas:
 * DevOps
 * CKAN Administrator (sysadmin)
 * CCO Developer/Contributor

What do you think?

**Comment by tkprmr** [comment]
Joel had review on this with Aaron and Tom W.  New tickets needs to be created for any additional documentation updates. 
Need to check with Aaron whether this can be closed after new update tickets are created.

**Comment by jqnatividad** [comment]
Closing this as CCO deployment is being automated and the associated documentation revamped to reflect this (#167).
