### ISSUE TITLE
Cohere and QA CCO docs together including home page

### ISSUE THREAD

**Issue by rufuspollock** [GSA/datagov-ckan-multi#128]
We need to pull the docs into a coherent whole, QA them and publish them properly in one place so they are easy to find and navigate and we also encourage others to contribute.

**Comment by tkprmr** [comment]
Joel had review on this with Aaron and Tom W.  New tickets needs to be created for any additional documentation updates. 
Need to check with Aaron whether this can be closed after new update tickets are created.

**Comment by jqnatividad** [comment]
Given test deployment findings using current docs, will put this backlog as CCO deployment is automated #137

**Comment by jqnatividad** [comment]
We'll need to revisit creating this once CCO is refactored. #184

**Comment by kimwdavidson** [comment]
Documentation is included in other tickets. Closing
