### ISSUE TITLE
Migrate data (maybe sample) from old catalog into v2.8

### ISSUE THREAD

**Issue by rufuspollock** [GSA/datagov-ckan-multi#131]
## Tasks

* [x] Analysis needed e.g. do we start with full db dump and then run the migration?

**Comment by avdata99** [comment]
We can start deploying CKAN, run the harvesters and check what is missing.  
The harvesters also migrate _organizations_ and _harvest sources_ so maybe this will be enough.  
If not, we can define tickets to migrate all the missing tables.  

I talked to Joel and the full database migrator runs between minor version. It will difficult to go from 2.3 to 2.8 if is not strictly necessary.

**Comment by jqnatividad** [comment]
We currently migrate organization metadata (logos, about, etc). 
https://catalog.data.gov/organization

Do we need to also migrate users of each organization?

**Comment by adborden** [comment]
No, let's not migrate users for now. I assume we'll be able to manually add ourselves as sysadmins?

**Comment by jqnatividad** [comment]
Yes, you can add yourselves manually as sysadmins thru the CLI beyond the sysadmin that is assigned when provisioning an instance.

https://docs.ckan.org/en/2.8/maintaining/getting-started.html#create-admin-user

**Comment by kimwdavidson** [comment]
Only task is completed. Closing. Can reopen if additional issues arise
