### ISSUE TITLE
Setup access to GSA AWS environment for external team members with requisite clearance

### ISSUE THREAD

**Issue by jqnatividad** [GSA/datagov-ckan-multi#133]
## User Story
As an authorized external team member (CivicActions/Datopian personnel with GSA security clearance), I need to get access to GSA's AWS environment to test, deliver and troubleshoot project deliverables. 

## Details / tasks
As part of validating the CCO deliverables and documentation (#74), Joel will need access to GSA's AWS environment.  He will also help deploy/deliver project deliverables from other external members who may not have requisite clearance.  This will also allow Joel to do prelim QA and help GSA with UAT.
 
* [ ] create "Development" and "UAT" environments within GSA's AWS account
* [ ] grant access/permission to authorized external team members 

## Acceptance Criteria
- [ ] Authorized External Team Members can independently deploy project deliverables in both "Development" and "UAT" environments
- [ ] Create deployment guidelines for External Team Members to follow so as not to dramatically increase GSA's AWS costs.

cc @hkdctol @adborden

**Comment by jqnatividad** [comment]
After Aaron walked me thru on how GSA wants to provision environments using an "Infrastructure as Code" approach Sep 6, created a PR to provision access for development team.

https://github.com/GSA/datagov-infrastructure-live/pull/17

**Comment by kimwdavidson** [comment]
Included in #136. closing
