### ISSUE TITLE
CCO Documentation: Developer Guide

### ISSUE THREAD

**Issue by jqnatividad** [GSA/datagov-ckan-multi#134]
### Developer Guide
* [x] Environment
* [x] Code overview
* [x] Contributing
* [x] Testing

**Comment by aluminiumgeek** [comment]
Developer guide is [ready](https://github.com/datopian/ckan-cloud-operator/blob/full-documentation/docs/DOCUMENTATION.md#developer-guide)

**Comment by tkprmr** [comment]
Joel had review on this with Aaron and Tom W.  New tickets needs to be created for any additional documentation updates. 
Need to check with Aaron whether this can be closed after new update tickets are created.

**Comment by jqnatividad** [comment]
Closing this as CCO deployment is being automated and the associated documentation revamped to reflect this (#167).
