### ISSUE TITLE
Connect CKAN instances to logging infrastructure

### ISSUE THREAD

**Issue by akariv** [GSA/datagov-ckan-multi#135]
## User Story

As an administrator, I would like to be able to read a single CKAN instance logs using a web ui so that I can easily see and debug all component events for a single instance.

## Details / tasks

- [x]  Connect instances to the logging system
- [x]  configure logatash to parse ckan logs correctly

## Acceptance Criteria
- [x] Being able to easily read the logs of a specific instance from a specific
time range
- [x] All CKAN components' logs drain into the logging infrastructure (harvester, datapusher, etc)

**Comment by adborden** [comment]
This story is about connecting CKAN instances to the logging infrastructure.

I moved this task to #127, since it is not specific to CKAN work
> - set up domain and authentication on kibana instance

**Comment by akariv** [comment]
I created a ckan extension to connect with logstash 

https://github.com/datopian/ckanext-logstash

Now I'm waiting on #127 to complete.

**Comment by akariv** [comment]
Currently testing the elk environment currently deployed on the cluster, will attempt integration in the next couple of days.

**Comment by akariv** [comment]
We now have:
- CKAN image with logstash config
- Instance kinds that use that image and contain logstash configuration
- A deployed instance that uses logstash integration

Now I'm debugging the setup and making sure logs are visible in Kibana

**Comment by akariv** [comment]
Done, sample kibana view:

https://ckan-cloud-app-elk.datagov.us/app/kibana#/discover?_g=(refreshInterval:('$$hashKey':'object:2069',display:Off,pause:!f,section:0,value:0),time:(from:now-15m,mode:quick,to:now))&_a=(columns:!(host,level,message),index:'logstash-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'*')),sort:!('@timestamp',desc))

**Comment by tkprmr** [comment]
@adborden to help with QA and add comments

**Comment by adborden** [comment]
Looks good.
