### ISSUE TITLE
Setup interim UAT environment in AWS sandbox

### ISSUE THREAD

**Issue by jqnatividad** [GSA/datagov-ckan-multi#136]
## User Story

As a reviewer, I need a UAT environment to conduct acceptance testing of deliverables.

## Details / tasks

GSA already has an AWS sandbox environment to which select team members who need to review deliverables can be given access.

Grant access/permission to authorized external team members 

We will use this as our interim UAT environment.

## Acceptance Criteria
- [x] Sandbox onboarding Procedure for requesting access is created/documented
- [ ] Team members who need to review deliverables can gain access to the AWS sandbox by following onboarding procedure
- [ ] CKAN cloud env exists in the sandbox

**Comment by tkprmr** [comment]
as per @jqnatividad this is completed as @adborden already provisioned access
