### ISSUE TITLE
Create tests for geodatagov extension

### ISSUE THREAD

**Issue by woodt** [GSA/datagov-ckan-multi#146]
geodatagov https://github.com/GSA/ckanext-geodatagov.git (MISSING TESTS)

**Comment by kimwdavidson** [comment]
@adborden to look for duplicate

**Comment by adborden** [comment]
@avdata99 is adding tests as part of https://github.com/GSA/datagov-ckan-multi/issues/153. That should be sufficient, or we can create a more specific issue for any additional coverage we're looking for.
