### ISSUE TITLE
Generate report on completed, current, and planned security activities

### ISSUE THREAD

**Issue by woodt** [GSA/datagov-ckan-multi#147]
Use the 18f "before you ship" checklist as a reference.

**Comment by woodt** [comment]
Nearly completed a spreadsheet listing activities and status.  Just have to add some ticket #s.

**Comment by woodt** [comment]
https://docs.google.com/spreadsheets/d/19A5x9mQACuXLHY6H7afiJfSMW8fLei_Rscgzs9wavBQ/edit#gid=0

**Comment by tkprmr** [comment]
@hkdctol to review the document and provide feedback

**Comment by hkdctol** [comment]
@woodt if all the security related tickets are mentioned in the Notes column I think we can consider this issue closed and we will review the work on the tickets.

**Comment by tkprmr** [comment]
@woodt create tickets in backlog for pending items / issues out of the report before closing this ticket

**Comment by woodt** [comment]
Have created tickets for activities, *except* for some of the SSP tasks.

**Comment by tkprmr** [comment]
@woodt can you link tickets here or refererence here
