### ISSUE TITLE
Migrate GSA/geodatagov harvester to 2.8

### ISSUE THREAD

**Issue by jqnatividad** [GSA/datagov-ckan-multi#153]
## User Story
As a CKAN admin, I need to make sure that the current GSA/ckanext-geodatagov extension will work in CKAN 2.8.

## Details / tasks
 - [x] Migrate GSA/ckanext-geodatagov to 2.8
 - [x] Add migrated extension to CCO harvester image

## Acceptance Criteria
- [x] Migrated extension has identical, if not improved behavior (coz of 2.8 improvements)
- [ ] Migrated extension works in CCO
- [x] CI should be configured to run automated tests for both CKAN 2.3 and 2.8 on commit

**Comment by adborden** [comment]
Added an AC for CI:
> CI should be configured to run automated tests for both CKAN 2.3 and 2.8 on commit

**Comment by avdata99** [comment]
We have the [GSA branch](https://github.com/GSA/ckanext-geodatagov/network) active from CKAN 2.3 (May 6, 2019)
![image.png](https://images.zenhubusercontent.com/5d0fa29f8356d802835f2561/5bcbf32d-c7f7-4c48-8a33-329a207138e1)

The [DistributedOpenUnifiedGovernmentNetwork branch](https://github.com/DistributedOpenUnifiedGovernmentNetwork/ckanext-geodatagov) seems more up to date but in reality it only has _requirements_ updates with a bot

**Comment by avdata99** [comment]
Forked as Datopian repo
https://github.com/datopian/ckanext-geodatagov
We can send PR when finished

**Comment by avdata99** [comment]
Started with Circle CI
https://circleci.com/gh/datopian/ckanext-geodatagov/1

**Comment by avdata99** [comment]
Tests (CSW by now) it's working
https://circleci.com/gh/datopian/ckanext-geodatagov

with tests:
https://github.com/datopian/ckanext-geodatagov/blob/master/ckanext/geodatagov/tests/test_csw_harvester.py

**Comment by avdata99** [comment]
Tests for _waf-collections_ was created
https://github.com/datopian/ckanext-geodatagov/blob/master/ckanext/geodatagov/tests/test_waf-collection.py

![Selection_2421.png](https://images.zenhubusercontent.com/5d0fa29f8356d802835f2561/03f41aa5-e976-46c0-853d-02d35b5a8948)

This tests works OK at CircleCI config
https://circleci.com/gh/datopian/ckanext-geodatagov

I think _waf_ sources are covered by spatial ext and the other types are very rarely used

**Comment by avdata99** [comment]
Open PR pending at: https://github.com/GSA/ckanext-geodatagov/pull/120

**Comment by kimwdavidson** [comment]
Need #199 resolved in order to review

**Comment by kimwdavidson** [comment]
@avdata99 to QA, then ping @adborden for final approval

**Comment by avdata99** [comment]
Fixed review from Aaron error (GSA badges) (at the [open PR](https://github.com/GSA/ckanext-geodatagov/pull/120))
Fixing CircleCI errors
Testing manually GeoDataGov at our sandbox (not finished harvesting)

**Comment by avdata99** [comment]
The [PR](https://github.com/GSA/ckanext-geodatagov/pull/120) was updated and it's ready
To be able to do some QA at [the sandbox](https://ckan-cloud-harvester-ng-5de80628.datagov.us/harvest/geo-argis-test/job/last) we need one of this two:
 - Update ckan-clod-docker with the new version (maybe we need to re-deploy it). This is already pushed to the Datopian repo.
 - Merge the PR and update the reference at ckan-clod-docker from the datopian repo to the GSA repo.
Which is the best way to deploy this changes @akariv?

**Comment by kimwdavidson** [comment]
@akariv  ^

**Comment by akariv** [comment]
@avdata99 
Please ensure the ckan-cloud-docker ckan image was rebuilt after you last updated the geodatagov extension in the datopian fork.
Then fetch the tag of that image and create a PR here:
https://github.com/ViderumGlobal/datagov-ckan-cloud-provisioning-api/blob/6ca451b7fc36a5a837b9327ebd16497c8b8adec0/kinds/kind-harvester.yaml#L8
and assign it to me so I can redeploy.

**Comment by avdata99** [comment]
Fixed many of these reviews. The last one is to define the CKAN imagen to use (OKF or Viderum CKAN cloud docker)

**Comment by akariv** [comment]
@avdata99 I believe this last comment is for #195 and not for this issue, correct?

**Comment by avdata99** [comment]
@akariv, updated to last Julie's commit: https://github.com/ViderumGlobal/datagov-ckan-cloud-provisioning-api/pull/3

**Comment by avdata99** [comment]
We still have this [PR](https://github.com/GSA/ckanext-geodatagov/pull/120) opened.
Since the [CircleCI tests](https://circleci.com/gh/datopian/ckanext-geodatagov) are running OK I think we can close this and eventually add more tickets if we detect some failures after the QA in the sandbox.

**Comment by kimwdavidson** [comment]
Aaron to review PR then move to QA and QA

**Comment by adborden** [comment]
Approved https://github.com/GSA/ckanext-geodatagov/pull/120, left a few comments.

**Comment by avdata99** [comment]
Fixed attending all comments. Tests are not passing. Fixing

**Comment by avdata99** [comment]
I send this [PR](https://github.com/GSA/ckanext-harvest/pull/7) @adborden.
Is for fix tests.

**Comment by avdata99** [comment]
By Accepting the PR (simulated [here](https://github.com/datopian/ckanext-geodatagov/commit/526a786f2fe2c9fcf2a3291d25754476254ac674)) at ckanex-harvest [tests at CircleCI passes ok](https://circleci.com/gh/datopian/ckanext-geodatagov/tree/1_test_waf_collection)

**Comment by adborden** [comment]
@avdata99 can you update the README to describe how to run the automated tests?

**Comment by avdata99** [comment]
> @avdata99 can you update the README to describe how to run the automated tests?

I added this notes: https://github.com/GSA/ckanext-geodatagov/pull/124/files
Let me know if is this ok @adborden 
A docker environment to run tests locally will be included in [#multi-207](https://github.com/GSA/datagov-ckan-multi/issues/207).
