### ISSUE TITLE
Remediate security issues detected by static code analysis - NG harvester

### ISSUE THREAD

**Issue by woodt** [GSA/datagov-ckan-multi#156]
## Acceptance Criteria
- [x] Tailoring should be removed from bandit.yml - ckan-ng-harvest
- [x] CI/CD pipeline should not fail - ckan-ng-harvest
- [x] Tailoring should be removed from bandit.yml - ckan-ng-harvester-core
- [x] CI/CD pipeline should not fail - ckan-ng-harvester-core

Issues detected by bandit in ckan-ng-harvest:

>> Issue: [B602:subprocess_popen_with_shell_equals_true] subprocess call with shell=True identified, security issue.
   Severity: High   Confidence: High

>> Issue: [B605:start_process_with_a_shell] Starting a process with a shell, possible injection detected, security issue.
   Severity: High   Confidence: High

>> Issue: [B303:blacklist] Use of insecure MD2, MD4, MD5, or SHA1 hash function.
   Severity: Medium   Confidence: High

Issues detected in ckan-ng-harvester-core

>> Issue: [B314:blacklist] Using xml.etree.ElementTree.fromstring to parse untrusted XML data is known to be vulnerable to XML attacks. Replace xml.etree.ElementTree.fromstring with its defusedxml equivalent function or make sure defusedxml.defuse_stdlib() is called

>> Issue: [B310:blacklist] Audit url open for permitted schemes. Allowing use of file:/ or custom schemes is often unexpected.

**Comment by woodt** [comment]
I've completed a MR for ckan-ng-harvest -- https://gitlab.com/datopian/ckan-ng-harvest/merge_requests/67 -- which is ready for review.

Wrapping up the MR for ckan-ng-harvester-core today.  When this is done, we can close this ticket.

**Comment by woodt** [comment]
Ran into some complexities with remediating some XML parsing security issues; it looks like those issues are resolvable but will take more time.  I'm going to split this ticket into XML and non-XML work so that we can capture the non-XML issues now, and then I can pick up the XML work in the near future.

**Comment by woodt** [comment]
Created https://github.com/GSA/datagov-ckan-multi/issues/185 to capture XML remediation work.

**Comment by avdata99** [comment]
Merged:
OK: https://gitlab.com/datopian/ckan-ng-harvest/merge_requests/67
  Rebuild ant tested OK
OK: https://gitlab.com/datopian/ckan-ng-harvester-core/merge_requests/2
 No need to rebuild
