### ISSUE TITLE
Add Helm to Harvester NG Docker image

### ISSUE THREAD

**Issue by jqnatividad** [GSA/datagov-ckan-multi#157]
## User Story
As a GSA devop, I need to be able to spin up a Harvester NG instance on CCO.
This requires that the current Harvester NG docker image be packaged with a helm chart.

## Details / tasks
- [ ] create helm chart for Harvester NG Docker image

## Acceptance Criteria
- [ ] Harvester NG instance can be deployed from CCO

**Comment by kimwdavidson** [comment]
@akariv is this already done?

**Comment by kimwdavidson** [comment]
@estebanruseler to review if this ticket is still needed

**Comment by akariv** [comment]
Still needed,  blocked pending cluster fixes

**Comment by akariv** [comment]
Done in here:
https://github.com/ViderumGlobal/ckan-cloud-helm/blob/master/ckan/templates/harvester-deployment.yaml
