### ISSUE TITLE
Security and ATO Prep Activities for CCO

### ISSUE THREAD

**Issue by woodt** [GSA/datagov-ckan-multi#158]

**Comment by adborden** [comment]
@woodt I believe this work is mostly focused on the CCO work, and so we should icebox this epic since we are pausing the CCO work.

**Comment by woodt** [comment]
Makes sense!  There probably will be ATO tasks needed, though, for other new work (NG harvester?)

**Comment by adborden** [comment]
Yes, but we'll capture that in it's own issue https://github.com/GSA/datagov-ckan-multi/issues/218.

I'll rename this for now.

**Comment by hkdctol** [comment]
Closing for now. Prioritizing epics.
