### ISSUE TITLE
(Discovery) enable protected branches in project repos

### ISSUE THREAD

**Issue by woodt** [GSA/datagov-ckan-multi#160]
This is a best practice, but will require a little investigation to see what makes sense given the complex repo structure for this project.

**Comment by woodt** [comment]
Both GitHub and GitLab have support for protected branches:

https://help.github.com/en/github/administering-a-repository/configuring-protected-branches

https://docs.gitlab.com/ee/user/project/protected_branches.html

Per our CCO refactoring meeting earlier in the week, we should add protected branch configuration to the CONTRIBUTING.md checklist.  See GSA/datagov-ckan-multi#190.

**Comment by mogul** [comment]
You might consider whether it's possible to automate this via [Terraform's GitHub provider](https://www.terraform.io/docs/providers/github/r/branch_protection.html), which makes auditing easier later.

**Comment by woodt** [comment]
Some additional to do items that require team discussion/decision:

- do we want to identify a subset of collaborators as maintainers?   Maintainer responsibilities would include:
  - merging pull requests to *master*
  - performing code reviews
 
- are there any status checks (apart from requiring pull request reviews) that we want to enforce before pull requests can be merged to *master*?

I strongly recommend that all pull requests receive at least one review.

Here are the key components to add to CONTRIBUTING.md:

Branch protection affords the following advantages:

- branch commit history can not be rewritten
- pushes to significant branches can be restricted to a subset of maintainers
- merges to protected branches can require a status check (e.g., passing tests, pull request reviews, etc.)

Recommendations:

- Enable branch protection on *master* (or any deployable branch.)
- Enable "require pull request reviews before merging" on *master*
- Identify Maintainers (document in MAINTAINERS.md ?).  Restrict push permissions on *master* branch to maintainers only.

**Comment by woodt** [comment]
BTW, love your idea about automating this, @mogul!

**Comment by woodt** [comment]
Per our team discussion on 21 Nov, we will be stressing auditability over assignment of roles.  E.g., we want to enable branch protection, require pull request reviews (and signed commits), but we don't need to identify a select group of maintainers.

**Comment by adborden** [comment]
Thanks @woodt , let's write this down in our CONTRIBUTING doc. I think this would be part of the repo checklist https://github.com/GSA/datagov-ckan-multi/issues/190.

**Comment by kimwdavidson** [comment]
@woodt to update contributing doc and close.
