### ISSUE TITLE
Automate provisioning of CCO management server 

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#188]
## User Story
As an operator, I want the management server to be provisioned automatically through [terraform](https://github.com/GSA/datagov-infrastructure-modules/tree/master/modules/ckan-cloud) so that I can deploy and manage CCO with all the benefits of infrastructure-as-code and release engineering principles, including Identifiability, Reproducibility, Consistency, and Agility.

## Details / tasks
CCO documents the initial [setup of the management server](https://github.com/ViderumGlobal/ckan-cloud-cluster/blob/master/docs/MANAGEMENT.md#create-a-server-using-amazon-ec2) which is necessary for CCO. These instructions should be captured as terraform templates so they are incorporated into our existing CI/CD pipeline.

## Acceptance Criteria
- [ ] Management server is deployed automatically through our [automated CI/CD process](https://circleci.com/gh/GSA/workflows/datagov-infrastructure-live/tree/master).
- [ ] A pre-built AMI is used, so that deployment of new versions of the Management server can be deployed in an immutable fashion.
- [ ] State is persisted via EBS or similar so that the instance can be destroyed and re-created without losing state.

**Comment by pwalsh** [comment]
This is similar to the existing issue I have on the CCO tracker: https://github.com/datopian/ckan-cloud-operator/issues/69

I will investigate the additional step of AMI creation.

Related, automating is partly covered by https://github.com/datopian/ckan-cloud-operator/issues/68

**Comment by adborden** [comment]
I think the distinction between this and datopian/ckan-cloud-operator#69 is that this issue is specific to GSA, while the CCO issue is a broader and more generic solution.

For example, datopian/ckan-cloud-operator#69 could include work to create a reusable Terraform module, then this issue would create the Terraform templates and GSA-configuration to consume that module. I wanted to make sure the GSA-specific stuff was captured explicitly and separate from the CCO work because I think we haven't been great about that in the past.

**Comment by pwalsh** [comment]
@adborden 

To make things easier to follow, we added a new, properly documented EPIC for CCO here:

https://app.zenhub.com/workspaces/datagov-multi-tenant-ckan-5cf12b601437ff1e943f0aa2/issues/gsa/datagov-ckan-multi/209

Then following, the tasks that are in this particular issue are fully covered in other backlog items:

- https://app.zenhub.com/workspaces/datagov-multi-tenant-ckan-5cf12b601437ff1e943f0aa2/issues/datopian/ckan-cloud-operator/78
- https://github.com/datopian/ckan-cloud-operator/issues/81
- https://github.com/datopian/ckan-cloud-operator/issues/82

I suggest - we close this issue then. 

cc @estebanruseler @kimwdavidson

**Comment by adborden** [comment]
For https://github.com/datopian/ckan-cloud-operator/issues/78, I'm not seeing anything specific to GSA. My [suggestion](https://github.com/datopian/ckan-cloud-operator/issues/78#issuecomment-559194048) was to scope it down, or add GSA specific tasks. However, I think this issue captures that work best for GSA.

**Comment by akariv** [comment]
We now have an AMI containing terraform, cco and Jenkins.
It has all the required code to provision an EKS cluster & other required services using Terraform & CCO.
Everything is built and continuously tested in CI.

**Comment by akariv** [comment]
Would be good to do a peer session with @adborden to provision a new cluster (to replace the current, unstable one).

**Comment by kimwdavidson** [comment]
Adam completed documentation today. @estebanruseler to schedule a session for GSA to deploy themselves.

**Comment by adborden** [comment]
AC for deploying into the GSA environment isn't met, but we're going to call this done and move on.
