### ISSUE TITLE
Automated creation of a deploy-able image for CCO management server

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#189]
## User Story
As an operator, I want the CCO management server to be provisioned from an image using an automated build process so that any changes or security updates are quickly incorporated into the running instance via immutable deploy.

## Details / tasks
Technology that creates the image is not as important, could be Docker image or AMI for example. The goal is to create an immutable artifact that can be versioned and deployed.

We've used [Packer](https://packer.io/) and [Ansible](https://www.ansible.com/) for AMI creation in the past. We might swap out Ansible with shell just so the shell script can be used by the CCO community without introducing an Ansible dependency.

## Acceptance Criteria
- [ ] Changes to the build have some level of unit tests or linting
- [ ] Build is kicked off as part of CI/CD process and tags the production image
- [ ] "Local" builds are tagged in a way so they will not be picked up by production

**Comment by pwalsh** [comment]
This is a great idea and highly related to https://app.zenhub.com/workspaces/datagov-multi-tenant-ckan-5cf12b601437ff1e943f0aa2/issues/gsa/datagov-ckan-multi/188

I suggest we first get an end-to-end flow using terraform (or similar) that directly interacts with the APIs of the cloud provider, and then explore bundling that up into pre-built AMIs. What do you think @adborden ?

**Comment by adborden** [comment]
Hmm, maybe I'm missing something. So the reason I'm suggesting an AMI is because of these [steps that need to be performed](https://github.com/ViderumGlobal/ckan-cloud-cluster/blob/master/docs/MANAGEMENT.md#create-a-management-server) on the server. I think the AMI makes it a little more straightforward to do immutable deployment. If we went without the AMI, would you be provisioning them via shell as part of the `terraform apply` or did you have something else in mind?

There are a few dependencies in those setup steps: OS, docker-machine, ckan-cloud-cluster (maybe a few more). Let's say there is a new version of ckan-cloud-cluster. We update our infrastructure-as-code repo to specify the updated version of ckan-cloud-cluster which kicks off CI/CD. Terraform goes to deploy but since the instance is already created, Terraform would not re-create the instance. Terraform doesn't know that a change to the provision steps means the instance needs to be re-created, right?

Using AMIs ends up looking like: code change kicks of CI/CD, new AMI is built, Terraform detects the instance AMI doesn't match the latest AMI, Terraform re-creates the instance.

**Comment by adborden** [comment]
Updated the title and description to reflect that this doesn't have to be an AMI image.

**Comment by adborden** [comment]
Closing as duplicate of https://github.com/datopian/ckan-cloud-operator/issues/82
