### ISSUE TITLE
Stabilizing cluster

### ISSUE THREAD

**Issue by aluminiumgeek** [GSA/datagov-ckan-multi#199]
## Story
We are currently experiencing connection issues to the RDS instance. CKAN instances couldn't establish connection to the Postgres.

Also solr and zookeeper instances couldn't get internal IP due to some AWS VPC issue.

This is the blocker for deploying harvester on the AWS sandbox.

## Acceptance criteria
* [ ] Resolve VPC issue: working solr and zookeeper instances
* [ ] Resolve RDS connection issue

**Comment by aluminiumgeek** [comment]
I've tried to recreate one of sample CKAN instance and found deployment couldn't run pod due to security policy issue.
`Error creating: pods "ckan-54774bfbc9-" is forbidden: unable to validate against any pod security policy: []`

According to events log this error was on most of pods in the cluster:
```
create Pod alertmanager-cluster-alerting-0 in StatefulSet alertmanager-cluster-alerting failed error: pods "alertmanager-cluster-alerting-0" is forbidden: unable to validate against any pod security policy: []
Error creating: pods "prometheus-operator-monitoring-operator-b47945fcc-" is forbidden: unable to validate against any pod security policy: []	
Error creating: pods "jnlp-kube-prod-1-7fdfdb8c9b-" is forbidden: unable to validate against any pod security policy: []
...
``` 

I've resolved issue related to security policies, and now we've got another issue: pods stuck on ContainerCreating with the error:
`Warning  FailedCreatePodSandBox  65s (x140 over 5m57s)   kubelet, ip-192-168-164-62.us-west-2.compute.internal  Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "ckan-cloud-provider-solr-solrcloud-zk-0-689fd4fb7b-hbjnm_ckan-cloud" network: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:50051: connect: connection refused"`

I think It's related to outdated or broken Amazon VPC CNI plugin. Still investigating it.

**Comment by aluminiumgeek** [comment]
Upgraded aws-vpc-cni to the latest available version (1.5.5), but it didn't help. Still investigating.

**Comment by aluminiumgeek** [comment]
aws-node pod (which runs amazon-k8s-cni) fails to start on third node named `ip-192-168-164-62` with `Pod Predicate MatchNodeSelector failed` error.  
(Command to list aws-node pods: `kubectl -n kube-system get pods -l k8s-app=aws-node`)

This causes pods that are scheduled on this node to stuck on `ContainerCreating` phase with error message: `transport: Error while dialing dial tcp 127.0.0.1:50051: connect: connection refused`.

Currently I cordoned the node, so no new pods will be scheduled on it.

**Comment by aluminiumgeek** [comment]
Cluster is now stable

**Comment by adborden** [comment]
Hey Mikhail,  does that mean this one mode is somehow misbehaving and
should be removed? Will it be removed automatically?
