### ISSUE TITLE
Add CircleCI integration to ckanext-datagovtheme

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#205]
## User Story

As a Data.gov developer, I want CI running automatically on every commit, so that I can ensure only PRs that pass our automated tests can be merged into `master`.

## Acceptance Criteria
- [ ] CI runs against several versions of CKAN
        - CKAN 2.8
        - [Catalog fork](https://github.com/GSA/ckan/tree/datagov)
- [ ] GH protected branches enforce CI checks pass before merging to `master`

**Comment by thejuliekramer** [comment]
Circle CI added in this branch https://github.com/GSA/ckanext-datagovtheme/pull/32

**Comment by adborden** [comment]
I just enabled required CI checks for `master`, looks good.
