### ISSUE TITLE
docker-ckan based workflow for ckanext-datajson local development

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#208]
## User Story

As a Data.gov developer, I need a [docker-ckan](https://github.com/okfn/docker-ckan) based workflow for local development, so that I can quickly test changes locally and use the same configuration as CI.

## Acceptance Criteria
- [x] I can run something like `docker-compose up` to get a local development environment
- [ ] CI uses a similar docker-compose configuration for automated tests

**Comment by thejuliekramer** [comment]
In my mind the result of this would be a github repo inside GSA that includes a README with instructions and links to the repositories needed to create this local environment. Does this sound right or does GSA have a better place to put documentation. @adborden

**Comment by thejuliekramer** [comment]
@adborden the current CCO docker can do what this task is asking but it does require some configuration... where should the details of this configuration live?

**Comment by adborden** [comment]
It should live in ckanext-datajson. The idea is the repo is self contained. Anything you need to run/test the extension is provided through the docker setup, using a single command.

**Comment by thejuliekramer** [comment]
This has been implemented in this PR https://github.com/GSA/ckanext-datajson/pull/55. The build is failing because the datagov main branch CI is failing. I believe @avdata99 fixes that here https://github.com/GSA/ckanext-datajson/pull/54. Is it possible to merge this before mind so we see the clean build?

**Comment by adborden** [comment]
https://github.com/GSA/ckanext-datajson/pull/54 is merged and the build is passing, now.
