### ISSUE TITLE
Platform-agnostic CKAN Cloud Operator

### ISSUE THREAD

**Issue by pwalsh** [GSA/datagov-ckan-multi#209]
When I standup a cluster of CKANs managed by CCO, I want to be able to automate the required infrastructure deployment in a platform-agnostic way, so I have a consistent foundation for infrastructure resource management that is code-driven and does not require manual configuration steps.

**Comment by estebanruseler** [comment]
Updated epic after aligning on this epic with Adam: 72, 73, 74, 75 and 85 are not directly relevant to GSA CCO so were removed from the epic

**Comment by adborden** [comment]
Updated the title based on the conversation this morning. This encompasses more than just GSA's immediate need of deploying from scratch into the GSA sandbox.

**Comment by hkdctol** [comment]
Closing for now. Prioritizing epics that we are likely to take on.
