### ISSUE TITLE
Next gen data.json harvesters are running daily on staging

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#215]
As a Data.gov developer, I want [ckan-ng-harvester](https://github.com/datopian/ckan-ng-harvester-core) running on cloud.gov so that I can manage my application following TTS best practices and get all of cloud.gov's benefits (no infrastructure or platform maintenance, reduced compliance cost, better debugging, etc).

## Details
- add configuration for ckan instance 
- add or toggle one source (e.g. gsa.data.json source)
- enable in ckan next gen harvester

## Acceptance criteria
- [ ] a sample of DCAT-US (data.json) harvesters are running in staging daily

**Comment by adborden** [comment]
@mogul has done some work to get airflow running in cloud.gov. Can you publish that work on a branch, or as a gist?

**Comment by adborden** [comment]
https://github.com/mogul/airflow-cloudgov

**Comment by kimwdavidson** [comment]
Split this into three tickets

**Comment by adborden** [comment]
Replaced by https://github.com/GSA/datagov-deploy/issues/2995
