### ISSUE TITLE
Create staging environment for next gen harvester

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#222]
## User Story
As a Data.gov developer, I want ckan-ng-harvester running a staging environment on cloud.gov so that I can manage my application following TTS best practices and get all of cloud.gov's benefits (no infrastructure or platform maintenance, reduced compliance cost, better debugging, etc).

## Details / tasks
- set up airflow
- set up database service
- set up next gen harvester 

## Acceptance Criteria
- [ ] a staging space is created with necessary services for ckan-ng-harvester

**Comment by kimwdavidson** [comment]
Airflow setup started here: https://github.com/mogul/airflow-cloudgov

**Comment by adborden** [comment]
Replaced by https://github.com/GSA/datagov-ckan-multi/issues/222
