### ISSUE TITLE
Publish Data.gov CKAN extensions to pypi

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#224]
## User Story
As a Data.gov operator, I want the Data.gov CKAN extensions published to PyPi so that I can install them just like I would any other python dependency.

As a CKAN developer, I want the Data.gov CKAN extensions published to PyPi so that I can easily install the latest stable version of the extensions.

## Details / tasks
Data.gov CKAN extensions
- https://github.com/GSA/ckanext-datajson
- https://github.com/GSA/ckanext-geodatagov
- https://github.com/GSA/ckanext-datagovtheme
- https://github.com/GSA/USMetadata

## Acceptance Criteria
- [ ] Fork status for each repo is removed so that folks know these are the canonical extensions
- [ ] Branches are updated so that `master` is the default branch
- [ ] The latest stable versions are tagged and published to PyPi
- [ ] Publishing to PyPi is automated through CI based on git tag with GSA account

**Comment by avdata99** [comment]
I am familiar with this task so I can collaborate with whoever does it

**Comment by nickumia-reisys** [comment]
Superceded by https://github.com/GSA/data.gov/issues/3414
