### ISSUE TITLE
Complete team charter

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#227]
- [x] add to repo
- [x] Sign off
- - [x] Hyon
- - [x] Aaron
- - [x] Bret
- - [x] Julie
- - [x] Adam
- - [x] Andres
- - [x] Esteban
- - [x] Kim
- - [x] Tom
- - [x] Paul

**Comment by thejuliekramer** [comment]
@kimwdavidson where can I find the team charter?

**Comment by hkdctol** [comment]
@thejuliekramer https://docs.google.com/document/d/1yFA-Mo3eoYW7kiHq2Rn0RdMAK78eB1S4p_L4wikzqdI/edit#heading=h.dcxtuiayu45i should get you to charter

**Comment by adborden** [comment]
I had a few small changes, linked to our [CONTRIBUTING](https://github.com/GSA/datagov-ckan-multi/blob/master/CONTRIBUTING.md#story-lifecycle) doc where relevant.
