### ISSUE TITLE
Docker based workflow for ckanext-datagovtheme

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#228]
## User Story

As a Data.gov developer, I need a [docker-ckan](https://github.com/okfn/docker-ckan) based workflow for local development, so that I can quickly test changes locally and use the same configuration as CI.

## Acceptance Criteria
- [x] I can run something like `docker-compose up` to get a local development environment
- [ ] CI uses a similar docker-compose configuration for automated tests

**Comment by thejuliekramer** [comment]
PR is here https://github.com/GSA/ckanext-datagovtheme/pull/35
