### ISSUE TITLE
Discovery: Review existing forks

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#229]
(_Esteban updated this issue 9th March to make it into a purely discovery ticket. I've updated the ticket with latest situation. Please see [refer to this](https://hackmd.io/FsYGp4dAR6uC6AdsnOLuIA?sync=&type=) for the previous version in case you want to see what I changed._)

## User Story
As a developer, I want to know the state of all of our forks, so I know how much work we have ahead to tidy up and make future work easier

**Links**: [Aaron's spreadsheet](https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit#gid=0)

## Acceptance Criteria
- [x] Fill out spreadsheet
- [x] Spreadsheet is reviewed Andres review
- [x] Julie review
- [x] Create tickets for each repo
- [x] 95% Done - Update: Each ticket has been estimated at a high level (S/M/L/XL) - Completed except James' who wasn't privy to the conversation on Thursday 5th March.
- [x] Tickets have been prioritized

## Verify Current State 

_Both Julie and Andres will work on this and cross-ref findings_

1. [x] Review the spreadsheet and verify that it is complete and correct
    - [Spreadsheet](https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit?ts=5e4177f8#gid=0)
    - Where is the Production Environment configuration? (for both instances, catalog & inventory) --> Aaron has showed us. 
   *  [x] Andres review
   *  [x] Julie review
2. [x] Verify that none of the extensions currently in production use a python dependency that is also on GitHub (and not from PyPi).
   *  [x] Andres review (created the column "All reqs in Pypi?"
   *  [x] Julie review
3. [x] Verify that there are no (hot) patches in the production environment applied after installation ---> Aaron confirmed that no patches in use

## Analyze Each row

_Julie and Andres to split fork investigation using the owner column and create an issue for analysis and document findings (the working assumption is we create the issues in the particular repos but then create some need have some way to way to track that is better than a spreadsheet - need to check this with Aaron)_

4. [x] Make sure that the repo and branch/commit for each dependency is correct (columns B & C)
   *  [x] Andres issues
   *  [x] Julie issues
5. [x] Decide which is the official upstream. If not a clear-cut, then discuss and decide (column F)
   *  [x] Andres issues
   *  [x] Julie issues
6. [x] If current repo is not the official one, open issue for reconciliation (column G)
   *  [x] Andres issues
   *  [x] Julie issues
7. [ ] Document whether official upstream has Tests and CI (columns H & I)
   *  [x] Andres issues
   *  [ ] Julie issues

## Prep for reconciliation

* [x] Understand the differences between the forks
   *  [x] Andres issues
   *  [x] Julie issues
* [x] Asses the amount of work needed to merge / use the official
   *  [x] Andres issues
   *  [x] Julie issues
* [x] Have an Small / Medium / Large estimate to assist prioritisation
   *  [x] Andres issues
   *  [x] Julie issues
* [x] Prioritize the issues

**Comment by akariv** [comment]
@adborden you mentioned you've already made an initial analysis of the forks - can you share that spreadsheet?

**Comment by adborden** [comment]
Turns out this didn't exist as a spreadsheet, so I had to put it together from other docs: https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit#gid=0

**Comment by estebanruseler** [comment]
Syned with Julie and Andres. We have agreed a way forward.

**Comment by avdata99** [comment]
I added all the missing repos from the requirements files at [catalog-app](https://github.com/GSA/catalog-app/) and the [inventory-app](https://github.com/GSA/inventory-app/). I think we are done with the elements in the list.

I mark some forks for me and others for Julie

I checked all the requirements files to find not-pypi linked repos. I marked red (some things outside Pypi) and green (all in Pypi) in a new columns called _All reqs in Pypi?_
I also added the  and _Last updated_ columns

About _commits_ column: I propose to change: `git log --oneline upstream/master.. | wc -l` for `git log --oneline upstream/master --not origin/master | wc -l` + `git log --oneline origin/master --not upstream/master | wc -l` (but using the right branches) to check how many commits we are ahead and behind. I tested this for ckanext-harvest: 498 / 184. It gives a better idea of how different we are.

I also add some notes.

**Comment by adborden** [comment]
Thanks @avdata99 , change to commits column sounds good.

As we do analysis, if we can rebase onto the latest version of upstream, we should try to do that. But if it's challenging or there is uncertainty, then we can punt.

The goal is not to reconcile all of the forks, but to be able to identify and prioritize what we should do now.

For example ckanext-saml2 handles authentication, so it's important to get bugfixes. It's also causing a lot of friction due to the repoze.who conflict. This repo might be a good one to focus on first.

**Comment by avdata99** [comment]
I'll start my analysis on ckanext-saml2 @adborden 
I just added info about test, CI, branch dates, upstream and CKAN compatibility. 
I will start adding new well-documented tickets for each repo.
