### ISSUE TITLE
Establish forks and upstreaming rules

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#230]
## User Story
As a developer, I want to know the forks and upstreaming rules, so that I can keep my repos neat and maintainable 

## Details / tasks
Topics
- tests
- documentation
- management of forks during transition

## Acceptance Criteria
- [ ] Document rules in readme

**Comment by adborden** [comment]
Some prior work here to start https://github.com/GSA/datagov-deploy/wiki/Managing-Forks

**Comment by adborden** [comment]
This is done https://github.com/GSA/datagov-deploy/wiki/Managing-Forks.

Not sure if the wiki is the best place for it, would certainly like a review.

**Comment by estebanruseler** [comment]
Adam, Andres and Esteban have reviewed. In general a big thumbs up but a few minor things to clarify.

**Comment by kimwdavidson** [comment]
@thejuliekramer to review and move to done

**Comment by adborden** [comment]
Just following up, was there any feedback or edits? Were they already incorporated?

**Comment by estebanruseler** [comment]
@adborden From our stand-point we use this document to guide the work. The acceptance criteria reflects this approach. But it's good you've flagged this as I should have shared this doc with Paul. He knows our approach but he doesn't have the full picture of the background.
