### ISSUE TITLE
Forks Reconciliation

### ISSUE THREAD

**Issue by thejuliekramer** [GSA/datagov-ckan-multi#233]
# Forks Plan

## Verify Current State

1. [ ] Review the spreadsheet and verify that it is complete and correct
    - [Spreadsheet](https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit?ts=5e4177f8#gid=0)
    - Where is the Production Environment configuration? (for both instances, catalog & inventory)
2. [ ] Verify that none of the extensions currently in production use a python dependency that is also on GitHub (and not from PyPi).
3. [ ] Verify that there are no patches in the production environment applied after installation

## Analyze Each row

4. [ ] Make sure that the repo and branch/commit for each dependency is correct (columns B & C)
5. [ ] Decide which is the official upstream. If not a clear-cut, then discuss and decide (column F)
6. [ ] If current repo is not the official one, open issue for reconciliation (column G)
7. [ ] Document whether official upstream has Tests and CI (columns H & I)

## Reconciliation

8. [ ] Understand the differences between the forks
9. [ ] Asses the amount of work needed to merge / use the official
10. [ ] When applicable - create a pull request to the official upstream with proposed changes
11. [ ] Create issues for adding missing CI / Tests (when needed)

**Comment by kimwdavidson** [comment]
needs to be combined with #229

**Comment by kimwdavidson** [comment]
Combined. Closing.
