### ISSUE TITLE
Provision access to cloud.gov

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#238]
## User Story
Team members should have access to cloud.gov, so that they can work on it. 

## Acceptance Criteria
Everyone on the team has an account and has read the tutorial 
- [x] Kim
- [x] Tom
- [x] Julie
- [x] Esteban
- [x] Adam
- [x] Andres

**Comment by mogul** [comment]
Invitations sent! 

Here is the quickstart page we often refer people to, as well as a simpler page for reference.
- [Quick Start](https://cloud.gov/quickstart)
- [Getting Started](https://cloud.gov/docs/getting-started/your-first-deploy/) (other details here)

**Comment by mogul** [comment]
Here's the "official" [beginner training](https://www.cloudfoundry.org/trainings/cloud-foundry-beginners-zero-hero/).

**Comment by thejuliekramer** [comment]
@mogul can you send me an invite for this again please, mine expired
