### ISSUE TITLE
Develop user testing recruitment database

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#246]
## User Story

As a product team, I want to be able to easily find users to test our work, so that we can know we're achieving value for them.

## Acceptance Criteria
- [x] Spreadsheet of users interested in being contacted for user testing

## Details / tasks
- [x] Create Google form to send to users 
- [x] Users should select roles as  "data owners," "data managers," "data consumers," "OMB," and "CDO." (some users will have multiple roles)
- [x] Users give permission to be directly contacted by user researchers
- [x] Email contact information
- [x] Agency
- [x] Opt in to types of activities (5-minute survey, 10 minute interview, 30 min interview, etc.)

**Comment by adborden** [comment]
@gujacq shared an example survey they used at NSF https://nsf.gov/help/recruitment.jsp

**Comment by gujacq** [comment]
I've started a recruitment survey here: https://forms.gle/AxD5Tka8ZsoNeEwJ8

LMK if you'd like to edit the language at all, or if anything you see is missing.

cc @kimwdavidson @hkdctol @adborden

**Comment by adborden** [comment]
Thanks! Is it possible to share it with us? I'm getting a permission
denied error:

> You need permission
>
> This form can only be viewed by users in the owner's organization.
>
> Try contacting the owner of the form if you think this is a mistake.
> Learn More.

--
Aaron D Borden
Human and hacker

**Comment by gujacq** [comment]
@adborden just added you

@kimwdavidson it looks like Aaron isn't on the GSA Data.gov (838) google team drive. Can you add him so he's able to view our links?

**Comment by hkdctol** [comment]
@kimwdavidson when you see this can you add me as well, so @hkdctol @adborden @mogul and @philipashlock all at our GSA addresses should have access to view

**Comment by gujacq** [comment]
New link here: https://docs.google.com/a/civicactions.com/forms/d/1HTd0TNLnD8bV4aEgzExnzrVjfEnpTqqU_s92yfWMcbY/edit?usp=sharing

**Comment by gujacq** [comment]
@hkdctol and @kimwdavidson here's a link to the form built out in surveymonkey. lets use this instead since some gov folks won't be able to access google forms: https://www.surveymonkey.com/r/CHBZTSQ

**Comment by gujacq** [comment]
Participants are being kept here: https://www.surveymonkey.com/create/preview/?sm=grc6UEXZs15E7v3h6O3lLuX0fHU4c41tglpWBn9ee2Y_3D&tab_clicked=1
