### ISSUE TITLE
Set up data owner test of prototype for metadata entry UI

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#247]
## Details / tasks
- [x] Recruit data owners
- [x] Write test script for prototyping metadata entry UI with data owners

**Comment by gujacq** [comment]
Recuitment documentation including the recruiting template that Hyon's going to send is here: https://docs.google.com/document/d/15FOv8eeaqRmJ4Po7gZADCVS8cEcMsctgYv3Y8OCcBhY/edit#
