### ISSUE TITLE
Cloud.gov: Setting up test environments for inventory

### ISSUE THREAD

**Issue by estebanruseler** [GSA/datagov-ckan-multi#251]
## Description

We have an immediate need for a cloud.gov environment that hosts the GSA inventory application (CKAN version 2.3) for Jacqueline to do the tests of the metadata entry form. This can also be used to test the fork work. 

## User Story

As a developer, I want a cloud.gov environment up and running so that test the code I'm pushing.

## Acceptance Criteria
- [ ] We have an environment running in cloud.gov that hosts the GSA inventory application (CKAN version 2.3)

## Details / tasks
- [ ]

**Comment by mogul** [comment]
@woodt I have [an instance of `inventory-app` running in cloud.gov](https://inventory-empathic-tasmaniandevil-gt.app.cloud.gov). You can mess with it yourself if you'd like:
```sh
$ cf t -o gsa-datagov -s development
api endpoint:   https://api.fr.cloud.gov
api version:    2.146.0
user:           bret.mogilefsky@gsa.gov
org:            gsa-datagov
space:          development

$ cf app inventory
Showing health and status for app inventory in org gsa-datagov / space development as bret.mogilefsky@gsa.gov...

name:              inventory
requested state:   started
routes:            inventory-empathic-tasmaniandevil-gt.app.cloud.gov
last uploaded:     Thu 27 Feb 18:24:27 PST 2020
stack:             cflinuxfs3
buildpacks:        python

type:           web
instances:      1/1
memory usage:   512M
     state     since                  cpu    memory          disk           details
#0   running   2020-03-12T20:25:45Z   0.4%   89.6M of 512M   488.9M of 1G
```

If you want to redeploy it, see [the instructions on the branch](https://github.com/GSA/inventory-app/blob/feature/cloud.gov/README.md#deploying-to-cloudgov).

**Comment by woodt** [comment]
FYI: Jacqueline is using an inventory-app instance I spun up for user testing.
