### ISSUE TITLE
Tom learns about cloud.gov by standing up Bret's inventory-app

### ISSUE THREAD

**Issue by woodt** [GSA/datagov-ckan-multi#255]
Acceptance criteria:

- [x] Tom succeeds in getting inventory to run in cloud.gov
- [x] Tom creates a PR against GSA/inventory-app to capture any changes to code or documentation

**Comment by woodt** [comment]
Got inventory-app to run!  Working on the pull request now.

**Comment by woodt** [comment]
Need write access to `GSA/inventory-app` ... pinged Bret and Aaron.

**Comment by woodt** [comment]
Here's the PR: https://github.com/GSA/inventory-app/pull/32

**Comment by adborden** [comment]
Quoting Tom Wood (2020-03-20 07:21:25)
> Need write access to `GSA/inventory-app` ... pinged Bret and Aaron.

Granted.

--
Aaron D Borden
Human and hacker
