### ISSUE TITLE
Move Adding Category Tags to Geodatagov Extension

### ISSUE THREAD

**Issue by thejuliekramer** [GSA/datagov-ckan-multi#266]
## User Story

As a developer, I want to move this geodatagov specific code out of CKAN and into the [geodatagov extension](https://github.com/GSA/ckanext-geodatagov/) so that we can use the OKF version of CKAN instead of GSA's fork. 

## Acceptance Criteria
- [ ] Code is no longer in fork, and fork still works
- [ ] Code is in the geodatagov extension
- [ ] Category tags are being added into the extras dictionary (retaining the original functionality)
- [ ] Geodata extension tests pass

## Details / tasks
- [ ] remove [custom code](https://github.com/ckan/ckan/commit/fa9b7486ae542d4f69f8fd5934db603ef522e6a7) from GSA CKAN datagov branch
- [ ] add functionality in geodatagov plugin
- [ ] add tests for this feature to extension

CKAN was original [extended to allow for before_action and after_action from a plugin](https://github.com/ckan/ckan/commit/fa9b7486ae542d4f69f8fd5934db603ef522e6a7). This was to allow geodatagov to [define a custom before_action and after_action](https://github.com/GSA/ckanext-geodatagov/blob/master/ckanext/geodatagov/plugins.py#L407 )

Maybe replicate behavior using https://docs.ckan.org/en/2.8/extensions/plugin-interfaces.html#ckan.plugins.interfaces.IFeed.get_item_additional_fields

**Comment by avdata99** [comment]
How to QA: 
The code for CKAN 2.3 was already moved to CKAN 2.8 in commits from past months.
Some possible QA is to:
 - Run the `export-csv` command and then check for the `/topics-csv` URL 
 - Add `__category_tag_` from the external PHP tool, then update the datasets and validate this extra tag is not missing 

All changes are now covered with tests

**Comment by thejuliekramer** [comment]
Tested this in staging - I am able to run the command `geodatagov export-csv` generate the file and download it.
<img width="434" alt="Screen Shot 2020-10-20 at 10 12 55 AM" src="https://user-images.githubusercontent.com/7378770/96606547-0364f900-12bd-11eb-906b-e4285b7c284a.png">


<img width="1083" alt="Screen Shot 2020-10-20 at 10 12 46 AM" src="https://user-images.githubusercontent.com/7378770/96606541-019b3580-12bd-11eb-900d-d896a6f05026.png">

<img width="1654" alt="Screen Shot 2020-10-20 at 10 12 30 AM" src="https://user-images.githubusercontent.com/7378770/96606572-0a8c0700-12bd-11eb-8695-cbbc356a6112.png">
