### ISSUE TITLE
Move Collections Feature into Extension

### ISSUE THREAD

**Issue by thejuliekramer** [GSA/datagov-ckan-multi#269]
## User Story

As a developer, I want to move this collections feature specific code out of CKAN and into an extension so that we can use the OKF version of CKAN instead of GSA's fork. 

## Acceptance Criteria
- [ ] Code is no longer in fork, and fork still works
- [ ] Code is in an extension
- [ ] Collections feature still works
- [ ] Collections feature tests pass

## Details / tasks
- [ ] remove [custom code](https://github.com/ckan/ckan/commit/3ef9f1be9667476d14ce4411d0e36bbdf81e00dc) from GSA CKAN datagov branch
- [ ] add functionality in a plugin
- [ ] add tests for this feature to extension

**Comment by kimwdavidson** [comment]
Duplicate. Closing
