### ISSUE TITLE
Move Functions for PackageSearchQuery to Extension

### ISSUE THREAD

**Issue by thejuliekramer** [GSA/datagov-ckan-multi#278]
## User Story

As a developer, I want to move this package search query specific code out of CKAN and into an extension so that we can use the [OKF version of CKAN](https://github.com/ckan/ckan) instead of GSA's fork. 

## Acceptance Criteria
- [ ] Code is no longer in fork, and fork still works
- [x] Code is in a new extension
- [x] Additional methods for PackageSearchQuery are still available (retaining the original functionality)
- [x] Extension tests pass

## Details / tasks
- [ ] remove [custom code](https://github.com/ckan/ckan/commit/11283a01dce8c821519fafefc28c67ae8271d562) from GSA CKAN datagov branch
- [x] add functionality in plugin/extension
- [x] add tests for this feature to extension

**Comment by avdata99** [comment]
To QA:
 - Check the code is fully moved from CKAN fork to GeoDataGov extension
    + Check [this commit](https://github.com/GSA/ckanext-geodatagov/pull/165/commits/11624728d74cda4964e4013f857aa542408db31f#diff-a0207d668e39922cc8203484323f0151R1) as a part of [this PR](https://github.com/GSA/ckanext-geodatagov/pull/165/files)

If #447 is ok this issue could be closed.

**Comment by thejuliekramer** [comment]
@avdata99 I don't see sitemap listed in the robots.txt on staging or sandbox
<img width="610" alt="Screen Shot 2020-09-30 at 4 52 13 PM" src="https://user-images.githubusercontent.com/7378770/94743852-aa4d1980-033d-11eb-924b-7d4946e3d17c.png">

**Comment by avdata99** [comment]
> @avdata99 I don't see sitemap listed in the robots.txt on staging or sandbox
> <img width="610" alt="Screen Shot 2020-09-30 at 4 52 13 PM" src="https://user-images.githubusercontent.com/7378770/94743852-aa4d1980-033d-11eb-924b-7d4946e3d17c.png">
> 

Sorry, I still need to deploy catalog-next. I will do this and then move 447 to QA. I think maybe this issue do not require QA in sandbox or staging.

**Comment by thejuliekramer** [comment]
Verified
<img width="478" alt="Screen Shot 2020-10-01 at 5 45 35 PM" src="https://user-images.githubusercontent.com/7378770/94870759-041d1480-040e-11eb-9c4e-2363581c12bc.png">
