### ISSUE TITLE
Use Configurable robots.txt

### ISSUE THREAD

**Issue by thejuliekramer** [GSA/datagov-ckan-multi#279]
## User Story

As a developer, I want to move this robots.txt specific code  [1](https://github.com/ckan/ckan/commit/2660715a944d1113fb8f82e2c8a9403fb97c045e) & [2](https://github.com/ckan/ckan/commit/1c59104e7c66b6bf77708fd7fb349539c29e7868)  out of CKAN and into a configuration file so that we can use the [OKF version of CKAN](https://github.com/ckan/ckan) instead of GSA's fork. 

## Acceptance Criteria
- [ ] Code is no longer in fork, and fork still works
- [ ] Code is configured using [robots.txt in new version of CKAN](https://github.com/ckan/ckan/pull/3164/files)
- [ ] Original code is maintained in new file

## Details / tasks
- [ ] remove custom code [1](https://github.com/ckan/ckan/commit/2660715a944d1113fb8f82e2c8a9403fb97c045e) & [2](https://github.com/ckan/ckan/commit/1c59104e7c66b6bf77708fd7fb349539c29e7868) from GSA CKAN datagov branch
- [ ] add functionality in configurable robots.txt file

Look into changes made to allow robots.txt to be customized [here](https://github.com/ckan/ckan/pull/3164/files).

**Comment by kimwdavidson** [comment]
Duplicate. Closing
