### ISSUE TITLE
Data.gov theme in catalog version

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#284]
## User Story
As a member of the general public, when I come to data.gov, I want it to have continuity with the way it looks now, so that I can have continuity in my use of the site

# Acceptance criteria
When I visit the new catalog.data.gov 
- [x] THEN I see data.gov branding with similar experience to the existing catalog.data.gov.

## Details/Tasks 
- [x] Load extensions required (no need to configure, etc)
- [x] Load theme

**Comment by adborden** [comment]
I wasn't able to test on https://catalog-next.sandbox.datagov.us yet, so I verified that the theme is looking good locally.
