### ISSUE TITLE
Continuous delivery for catalog app to sandbox

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#287]
## User Story

As a data.gov developer, I want code merged to master to be delivered with as little effort as possible, so that the teams don't depend on each other for delivery.

## Acceptance Criteria

- [x] WHEN I merge a PR to master
  THEN the deployment is started automatically to sandbox

- [x] GIVEN I merge a PR
  WHEN the deploy fails
  THEN I am notified that I need to fix something.

**Comment by adborden** [comment]
I think this was closed by accident?

**Comment by avdata99** [comment]
> I think this was closed by accident?

In our Monday meeting, we talk about [PR #2](https://github.com/GSA/catalog.data.gov/pull/2). Since it's merged Kim unassign Julie and ask me to do a final check and close.

Maybe we need to wait for a real deploy here

**Comment by adborden** [comment]
I didn't think the notification aspect had been addressed yet.
> GIVEN I merge a PR
> WHEN the deploy fails
> THEN I am notified that I need to fix something.

I had added https://github.com/GSA/catalog.data.gov/pull/13 and just added a slack subscription to GH issues to #datagov-ckan-multi channel to meet that criteria. Is there an alternative solution we've already met?

**Comment by adborden** [comment]
@thejuliekramer FYI, the configuration for the job definition (and the repo it notifies) is https://github.com/GSA/datagov-deploy/blob/develop/ansible/inventories/sandbox/group_vars/all/vars.yml#L87-L89
