### ISSUE TITLE
Discovery: Improved metadata entry form

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#288]
## User Story

As a data.gov representative, I want to onboard agencies to an improved metadata entry tool, so that I can meet the federal data action plan requirements 

## Acceptance Criteria
- [ ]

**Comment by gujacq** [comment]
@kimwdavidson As far as Stephen and I are concerned, the UX activity on this (besides QAing the build) is done. Not sure if this epic is tied to any dev tickets so leaving this up for you to either close or leave open
