### ISSUE TITLE
Task: Write new help text

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#290]
- Based on discovery, write help text for each field that requires it

## User Story
As a data owner or manager, I want help text on fields so that I better understand how to complete the form.

## Acceptance Criteria
- [x] Plain language help text

## Details / tasks
- [x] GSA reviews suggested help text from UX team here
- [x] GSA makes an edits or changes

## Resources
Open Data Schema spreadsheet: https://docs.google.com/spreadsheets/d/1mcSkGlQph2CUnlS-I2FAayH6GreF0vLcJiK_Y4iZOM8/edit?ts=5ec6e879#gid=0

**Comment by gujacq** [comment]
This is the new document: https://docs.google.com/spreadsheets/d/1bWt_uLloRQ5Rd8HI22COUlIwH_REsywHJ43NmkQNSv0/edit?ts=5ed84307#gid=746832760

Notice the cells highlighted in a different colour.

**Comment by stephen-tsai** [comment]
@kimwdavidson @hkdctol We're closing this ticket but it's related to Ticket #316, and you will be able to review there.
