### ISSUE TITLE
Enable CSW application for catalog-next

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#306]
## User Story

As a geospatial user, I want the [CSW](https://github.com/GSA/pycsw) ([Catalog Service for Web](https://en.wikipedia.org/wiki/Catalogue_Service_for_the_Web)) app enabled for catalog-next so that I can access the catalog-next datasets in a common geospatial format as I can today on catalog.data.gov.

## Acceptance Criteria
- [ ] WHEN I browse https://catalog-next.data.gov/csw?service=CSW&version=2.0.2&request=GetCapabilities
  THEN I see the XML response describing CSW's capabilities ([similar to this](https://catalog.data.gov/csw?service=CSW&version=2.0.2&request=GetCapabilities))

## Details / tasks
- [ ] add catalog-next hosts to pycsw Ansible groups
- [ ] run the pycsw.yml playbook in sandbox and debug/document any errors
- [ ] manually run the ckan-load job on the pycsw-worker
- [ ] create GH issues to address any errors or followup tasks

**Comment by adborden** [comment]
This doesn't look like it was done. I'm not seeing any [catalog-next hosts in the ansible inventory](https://github.com/GSA/datagov-deploy/blob/2e11bce8df88c4520653d30dd863bdde5bf4398e/ansible/inventories/production/hosts#L101-L113) and https://catalog-next.data.gov/csw is returning a 503.

**Comment by avdata99** [comment]
> This doesn't look like it was done. I'm not seeing any [catalog-next hosts in the ansible inventory](https://github.com/GSA/datagov-deploy/blob/2e11bce8df88c4520653d30dd863bdde5bf4398e/ansible/inventories/production/hosts#L101-L113) and https://catalog-next.data.gov/csw is returning a 503.

I think #506 was created to cover this in production-next
I think we should move this to _done_ since is working in the sandbox ([already added in the _hosts_ file](https://github.com/GSA/datagov-deploy/blob/develop/ansible/inventories/sandbox/hosts#L45-L77))

**Comment by adborden** [comment]
👍
