### ISSUE TITLE
Discovery: Determine datasets per Harvester type

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#310]
### Description
Determine how many datasets there are per harvester type, so that we can prioritize remaining harvester rebuilds

**Comment by thejuliekramer** [comment]
Linking to the spreadsheet @adborden posted in Slack https://docs.google.com/spreadsheets/d/16mzofxXsMAaJYQa17rM-1jy2Iu3sQtfVJmFyeASsEX4/edit#gid=1399417690 


```
source_type    | total_datasets
waf-collection | 317260
datajson       | 69663
ckan           | 26021
waf            | 18041
csw            | 397 
arcgis         | 0 
Grand Total    | 431382 
```

**Comment by adborden** [comment]
The script to generate these stats is documented in our [catalog.data.gov runbook](https://github.com/GSA/datagov-deploy/wiki/catalog.data.gov#harvest-source-stats).

**Comment by adborden** [comment]
@estebanruseler I'm going to assign to you for QA. Does this provide enough information to determine the order for harvester stories?

**Comment by kimwdavidson** [comment]
Looks like we probably want waf-collection early in the next sprint, then csw harvester? 

There are arcgis harvests happening, but they're not pulling any datasets. Does that mean we hold off on arcgis for now? Or does it mean the arcgis harvester isn't working? 

Other notes: 
- there hasn't been a geoportal harvest since 2013
- the most recent single-doc harvests were in may 2018 
- 2013 was the last z3950 harvest

So sounds like we can put these all off for a while without affecting anyone, though we will want those datasets on the new catalog, so how would that work? Can we pull them in with the ckan -> ckan harvester?

**Comment by kimwdavidson** [comment]
Conferred with Esteban. Let's find out if the arcgis harvester is broken. If it's not, we'll deprioritize, if it is, it'll be the third priority harvester, since people do seem to be using it. 

And we'll deprioritize geoportal, single-doc, and z3950 until after MVP.

**Comment by adborden** [comment]
If the arcgis harvester is broken, we should open an issue and address it later. No need to fix what's already broken unless it's a show stopper.

Re: waf-collections, let's punt/deprioritize on this until we get back to the collections work. Depending on how we implement collections, I suspect we'll have to revisit waf-collections anyway.

**Comment by estebanruseler** [comment]
Great, thanks for that info :)
