### ISSUE TITLE
Review federal DCAT harvester sources

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#312]
@kimwdavidson commented on [Tue May 26 2020](https://github.com/GSA/datagov-deploy/issues/1703)

### Description:
Harvest sources list here: https://docs.google.com/spreadsheets/d/13n3PYD_ppd7mj38Yeix5sf6K3cZL2KxnYj5VuSUUfg8/edit#gid=1994989648

There are numerous errors on multiple harvest sources. We need to determine which are the ones we need to fix. 

### Details/Tasks
- [x] Hyon to add column designating federal sources
- [x] Review whether the harvesters hyon designated as active are working without errors
     - [x] Develop a script to test if the harvest are working and create a report (we could do this manually but want to create a script so that we can use for other harvester types)
     - [x] Test the script
- [x] Document errors: Final report [here](https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit?ts=5e4177f8#gid=1667396946)
   - 53 have an error about spatial field validation. Added [new issue](https://github.com/GSA/catalog.data.gov/issues/55).
   - 15 sources without errors
   - 5 have error no related with the catalog upgrade (JSON parsing, 404, etc)
   - 5 have errores related with validation at fields: BureauCode, progmanCode, keyword, contactPoint, etc. Maybe we miss something related while migrate sources (validation config), We already have [Catalog#42](https://github.com/GSA/catalog.data.gov/issues/42) to test this. We added more info to this issue.
- [x] Determine whether the errors are worth fixing
- [x] Start with federal sources, save non-federal sources for later

**Comment by hkdctol** [comment]
See DCAT-US tab, column K here: https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit#gid=264788117
F indicates federal source, to prioritize, N indicates non-federal, lower priority

**Comment by avdata99** [comment]
Send PR [#54](https://github.com/GSA/catalog.data.gov/pull/54) to add a new script to check harvest sources
To continue from [#55](https://github.com/GSA/catalog.data.gov/issues/55) with a widely repeated issue about _spatial_ field validation.
