### ISSUE TITLE
Create proposal to research metadata quality improvement

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#313]
### Description
We need to further explore the problem of metadata quality management, specifically around how data managers are currently doing this work and their pain points. 

### Details/Tasks
- [x] develop plan and timeline
- [x] present to data.gov team for approval

**Comment by gujacq** [comment]
We presented the research on our design review 5/29: https://github.com/GSA/datagov-ckan-multi/issues/288
