### ISSUE TITLE
Quick usability testing on forms

### ISSUE THREAD

**Issue by gujacq** [GSA/datagov-ckan-multi#314]
## User Story
As a user researcher, I want to conduct some quick usability tests on the designs I made so that I understand if they’re usable.

## Acceptance Criteria
- [x] User researcher understands where the pain points are and what’s working 
- [x] We hear from users on layout preference 

## Details / tasks
- [x] Write up user research plan
- [x] Build prototype
- [x] Recruit
- [x] Conduct user research
- [x] Record and analyze results

**Comment by gujacq** [comment]
Research plan has been started here: https://docs.google.com/document/d/1u_JxA_6r2IfYpUyI0LQM2cMInTTVGHPNerKf7f5_Wr0/edit?usp=sharing

**Comment by stephen-tsai** [comment]
@hkdctol @adborden @kimwdavidson Review same link https://docs.google.com/document/d/1u_JxA_6r2IfYpUyI0LQM2cMInTTVGHPNerKf7f5_Wr0/edit?usp=sharing  https://www.figma.com/proto/klRVVF5U6fFmDbiu3s6L3g/Metadata-Form?node-id=308%3A1069&scaling=min-zoom

**Comment by stephen-tsai** [comment]
@hkdctol @adborden @kimwdavidson We have updated the prototype and usability testing script.  Just want to double-check, are we good to move forward with testing or do you want to review the script first?  CC @gujacq 
Script:
https://docs.google.com/document/d/1u_JxA_6r2IfYpUyI0LQM2cMInTTVGHPNerKf7f5_Wr0/edit?usp=sharing  
Prototype:
https://www.figma.com/proto/klRVVF5U6fFmDbiu3s6L3g/Metadata-Form?node-id=308%3A1069&scaling=min-zoom

**Comment by hkdctol** [comment]
looks good to me

**Comment by gujacq** [comment]
@hkdctol and @adborden Here is the deck of our findings from this round of user research to review: https://docs.google.com/presentation/d/18367F_15CxXwrqzuDFwZsxYHTGB9cwQ1iXG2AVVIerw/edit#slide=id.g7515f1ce6e_0_22

Feel free to comment with any thoughts and questions, or to move to the done column if you're good with these. Artifacts such as raw notes and our Mural is on the last slide of the deck.

**Comment by hkdctol** [comment]
The findings/recommendations deck looks good to me.

**Comment by gujacq** [comment]
@estebanruseler the results from our user research can be found here
