### ISSUE TITLE
Finalize and spec designs for CKAN 2.5 form

### ISSUE THREAD

**Issue by gujacq** [GSA/datagov-ckan-multi#316]
## User Story
As a developer, I want finalized and spec’d out designs so that I understand how to build the form.

## Acceptance Criteria
- [x] Developers have access to the designs and understand form functionality

## Details / tasks
- [x] Make any necessary revisions
- [x] Clean Figma files
- [x] Make sure engineers are invited to Figma and have access
- [x] If needed, set up a meeting with developers to review design and interactions

## Resources
Spreadsheet of requirements: https://docs.google.com/spreadsheets/d/1bWt_uLloRQ5Rd8HI22COUlIwH_REsywHJ43NmkQNSv0/edit#gid=746832760

**Comment by stephen-tsai** [comment]
@hkdctol @adborden @thejuliekramer Heads-up that our designs are good to go after the feedback from this morning.

**Comment by hkdctol** [comment]
This looks good and I am moving to done.

**Comment by stephen-tsai** [comment]
@starsinmypockets Here is the prototype and spreadsheet for the metadata entry form.  @gujacq and I are happy to walk you through anything you might have questions on!

> @hkdctol @adborden @thejuliekramer Heads-up that our designs are good to go after the feedback from this morning.
> You can view the prototype [here](https://www.figma.com/proto/klRVVF5U6fFmDbiu3s6L3g/Metadata-Form?node-id=648%3A1297&scaling=min-zoom).
> And the spreadsheet with each field laid out [here](https://docs.google.com/spreadsheets/d/1bWt_uLloRQ5Rd8HI22COUlIwH_REsywHJ43NmkQNSv0/edit#gid=746832760)
> Let me and @gujacq know if you have any questions. Thanks!

**Comment by gujacq** [comment]
@estebanruseler for his reference as well. going to go over these two docs in our upcoming call
