### ISSUE TITLE
Write research plan for workflow observation

### ISSUE THREAD

**Issue by gujacq** [GSA/datagov-ckan-multi#317]
## User Story
As a user researcher, I want a research plan for the interviews I’ll be conducting so that I have guidance, a rubric, and a common understanding to research goals.

## Acceptance Criteria
- [x] Data.gov team reviews and is in alignment on the content of the research plan 

## Details / tasks
Produce a research plan that outlines the following: 
- [x] research goals
- [x] interview script
- [x] potential questions

## Resources
Previous example of research plan: https://docs.google.com/document/d/1p9n0pyAdxQ2Vaz-rW3lWYPdytIqA3gklQ8BSCFutm1Y/edit

**Comment by gujacq** [comment]
Research plan started here: https://docs.google.com/document/d/1k-unjySrLo6-7Mtxicj6JHOpUnlGGyvOKchHsajZTQo/edit?usp=sharing

**Comment by gujacq** [comment]
@hkdctol and @adborden, the reserach plan in my last comment is up for review when you're able to get to it. Hoping to get comments in by Tuesday the 30th if you can swing it!

**Comment by hkdctol** [comment]
Provided comments to document, moving to done
