### ISSUE TITLE
Catalog-Next web loses access to redis instance

### ISSUE THREAD

**Issue by woodt** [GSA/datagov-ckan-multi#320]
catalog-next-webt1f needs access to the catalog next redis instance in the sandbox.

I _think_ the current terraform is not using the right security group in establishing the ingress rules.

The web instance is attached to catalog-next-sandbox-web-sg-tf.

The SG catalog-next-redis-sandbox is used to control access to the redis instance.  It appears that the terraform adds an inbound rule from `catalog-next-sandbox`, but not from `catalog-next-sandbox-web-sg-tf`.  As a result, there was no connectivity between the catalog-next web instance and redis.  When I manually added an ingress rule using `catalog-next-sandbox-web-sg-tf` as a source, connectivity was restored.

Slight mystery: Aaron and I had things working on Thursday/Friday of last week, but something happened over the weekend (?) and connectivity was lost.

**Comment by adborden** [comment]
Any manual changes in the AWS console would have been removed by a deploy of [datagov-infrastructure-live](https://app.circleci.com/pipelines/github/GSA/datagov-infrastructure-live?branch=master) so I think [your fix there](https://github.com/GSA/datagov-infrastructure-modules/pull/68) is the correct one.

**Comment by woodt** [comment]
See PR here: https://github.com/GSA/datagov-infrastructure-modules/pull/68

**Comment by woodt** [comment]
Ok!  All PR's merged, and ready for QA.

**Comment by adborden** [comment]
I re-ran [datagov-infrastructure-live](https://app.circleci.com/pipelines/github/GSA/datagov-infrastructure-live/252/workflows/4cc72596-2096-4469-83d8-09670c8bea9a) to ensure Redis had an up-date-configuration. Then I ran a [harvest job successfully](https://catalog-next.sandbox.datagov.us/harvest/illinois-json/job/7ab29997-7f3e-4cab-a05d-621e61b25898), which means CKAN is still able to connect to Redis.
