### ISSUE TITLE
404 on harvest_org_list page for catalog-next

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#321]
Admin user cannot add new harvest soures.

## How to reproduce

1. [Log in](https://catalog-next.sandbox.datagov.us/user/login) as admin
1. Browse to [org edit page](https://catalog-next.sandbox.datagov.us/organization/edit/general-services-administration)
1. Click "Harvest Sources" tab (https://catalog-next.sandbox.datagov.us/organization/edit/harvest_org_list?id=general-services-administration)

## Expected behavior

I see a list of harvest sources and can create new harvest sources.

On production, the Harvest Sources tab links to https://admin-catalog.data.gov/organization/harvest/gsa-gov

## Actual behavior

Harvest Tab links to https://catalog-next.sandbox.datagov.us/organization/edit/harvest_org_list?id=general-services-administration and results in a 404.

> 404 Not Found
> The resource could not be found.
> Group not found

(I'm not sure that the URL path not matching production is an issue or not).

**Comment by adborden** [comment]
We discussed the upstream behavior of ckanext-harvester vs our fork. The Harvest Sources tab and the controller serving that is a data.gov customization. We might consider pushing this upstream and avoid addressing for now.

Given that only data.gov folks are editing harvest sources, the cumbersome method of bookmarking `/harvest/new` and having to locate an organizations harvest sources through search might be okay for now. We should discuss the implication with @hkdctol when we triage this. Moving to `New` for now.

**Comment by adborden** [comment]
@avdata99 as a potential fix for this, what if we just change the tab on the organization admin page to link to https://catalog-next.sandbox.datagov.us/harvest?q=organization:org-name

Where the organization name can be dynamically filled at render time?

**Comment by avdata99** [comment]
We have the organization list filled at bottom left in the harvest list page
![image](https://user-images.githubusercontent.com/3237309/88925961-aae90700-d24b-11ea-83ab-1bbff70ada2a.png)

If we click on an organization we get URL like `https://catalog-next.sandbox.datagov.us/harvest?organization=ORG-NAME`

![image](https://user-images.githubusercontent.com/3237309/88926116-dec42c80-d24b-11ea-93fb-cfcf586b5e1d.png)

Maybe we can just propose to upstream a simple link in the organization page in the same place we use for our old repo.

![image](https://user-images.githubusercontent.com/3237309/88926402-53976680-d24c-11ea-8522-1d0894502c3b.png)

**Comment by adborden** [comment]
I was able to login, click the Harvest Sources tab for GSA and then be directed to the harvest source page with the correct organization filter.
