### ISSUE TITLE
Content layout on Organization Datasets admin page

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#322]
Column layout is broken on organization datasets admin page.

https://catalog-next.sandbox.datagov.us/organization/bulk_process/wv-gis-technical-center

![Screenshot from 2020-06-12 09-05-09](https://user-images.githubusercontent.com/509703/84522724-035c4900-ac8c-11ea-9424-d4541663db25.png)

## How to reproduce

1. Log in as administrator
1. Browse to https://catalog-next.sandbox.datagov.us/organization/bulk_process/wv-gis-technical-center

## Expected behavior

- Filters appear in the left sidebar.
- "Add dataset" button is not overlaying other UI controls

## Actual behavior

Filters appear in the main column content area. Add Dataset button overlays the tab menu and some other button.

**Comment by avdata99** [comment]
To QA an organization with resources:
 - https://catalog-next.sandbox.datagov.us/organization/bulk_process/city-of-chesapeake
 - https://catalog-next.sandbox.datagov.us/organization/bulk_process/city-of-los-angeles

**Comment by adborden** [comment]
Thanks! Looks good to me.

https://catalog-next.sandbox.datagov.us/organization/bulk_process/alcc-fws-gov
![Screen Shot 2020-09-24 at 10 37 10 AM](https://user-images.githubusercontent.com/509703/94179849-fb4aa280-fe51-11ea-83e3-55f5256909e1.png)
