### ISSUE TITLE
DOI CKAN-CKAN harvester never starts

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#325]
Dept of the Interior CKAN-to-CKAN harvest job does not start:
https://catalog-next.sandbox.datagov.us/harvest/doi-open-data

Source URL: https://data.doi.gov

I grep'd for the job id (`ff93580a-ff7e-48e9-8c00-5ba2fdb1d78a`) in the harvest run logs, but don't see it. Other harvest jobs have started since.

![Screenshot from 2020-06-12 16-27-50](https://user-images.githubusercontent.com/509703/84553743-ce6ee700-acc9-11ea-904a-cd92bdd32b2c.png)

## How to reproduce

1. Login as Admin
1. Open https://catalog-next.sandbox.datagov.us/harvest/admin/doi-open-data
1. Click "Reharvest" button
1. Wait 10 minutes (harvest run is run every 3 minutes in most cases)
1. Refresh

## Expected behavior

Harvest job starts within ~3 minutes. Started timestamp is displayed.

## Actual behavior

Havest job never seems to start. Status is "Running" and "Started" remains empty.

**Comment by avdata99** [comment]
Local test also failed:

![image](https://user-images.githubusercontent.com/3237309/84651683-bfae4d00-aee0-11ea-8e41-1a7e9dfceaab.png)

Source DoI CKAN is 2.3 version: https://data.doi.gov/api/3/action/status_show

Error counter:

Count | Message
-- | --
22847 | Instance <User at 0x7fd08f989310> is not bound to a Session; attribute refresh operation cannot proceed
2813 | Instance <User at 0x7efc54bfd490> is not bound to a Session; attribute refresh operation cannot proceed
1 | Invalid package with GUID 0001edd8-b903-4102-9645-89f9cb2c8dd1: {u'extras': [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {'key': ['There is a schema field with the same name']}, {}, {}, {}]}
1 | Invalid package with GUID 1c50a5a2-233c-42b5-bc47-67b8d5a01825: {u'extras': [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {'key': ['There is a schema field with the same name']}, {}, {}, {}]}

**Comment by avdata99** [comment]
- https://data.doi.gov have 26k datasets
 - Harvest process starts immediately at the sandbox
 - It seems the source is too big to run in the sandbox

To reproduce error seeing logs.

In `catalog-harvester-next1tf.internal.sandbox.datagov.us` server run `tail -f /var/log/*.log`
The start harvest job for [doi-open-data source](https://catalog-next.sandbox.datagov.us/harvest/doi-open-data)

```
2020-07-29 19:16:46,205 DEBUG [ckanext.harvest.harvesters.ckanharvester] Searching for CKAN datasets: https://data.doi.gov/api/3/action/package_search?sort=id+asc&start=17800&rows=100
2020-07-29 19:16:46,765 DEBUG [ckanext.harvest.harvesters.ckanharvester] Searching for CKAN datasets: https://data.doi.gov/api/3/action/package_search?sort=id+asc&start=17900&rows=100
********************************
The gather consumer stops
********************************

==> /var/log/kern.log <==

********************************
Then we see some kernel error
********************************

Jul 29 19:16:48 catalog-harvester-next1tf kernel: [14982.402897] VM Thread invoked oom-killer: gfp_mask=0x100cca(GFP_HIGHUSER_MOVABLE), order=0, oom_score_adj=0
Jul 29 19:16:48 catalog-harvester-next1tf kernel: [14982.402900] CPU: 0 PID: 942 Comm: VM Thread Not tainted 5.3.0-1032-aws #34~18.04.2-Ubuntu
Jul 29 19:16:48 catalog-harvester-next1tf kernel: [14982.402901] Hardware name: Amazon EC2 t3.small/, BIOS 1.0 10/16/2017
...
Jul 29 19:16:48 catalog-harvester-next1tf kernel: [14982.402968] Mem-Info:
Jul 29 19:16:48 catalog-harvester-next1tf kernel: [14982.402971] active_anon:466443 inactive_anon:41 isolated_anon:0
Jul 29 19:16:48 catalog-harvester-next1tf kernel: [14982.402971]  active_file:13 inactive_file:15 isolated_file:0
Jul 29 19:16:48 catalog-harvester-next1tf kernel: [14982.402971]  unevictable:0 dirty:12 writeback:0 unstable:0
Jul 29 19:16:48 catalog-harvester-next1tf kernel: [14982.402971]  slab_reclaimable:4577 slab_unreclaimable:4282
Jul 29 19:16:48 catalog-harvester-next1tf kernel: [14982.402971]  mapped:6 shmem:190 pagetables:2765 bounce:0
Jul 29 19:16:48 catalog-harvester-next1tf kernel: [14982.402971]  free:13135 free_pcp:240 free_cma:0
Jul 29 19:16:48 catalog-harvester-next1tf kernel: [14982.402973] Node 0 active_anon:1865772kB inactive_anon:164kB active_file:52kB inactive_file:60kB unevictable:0kB isolated(anon):0kB isolated(file):0kB mapped:24kB dirty:48kB writeback:0kB shmem:760kB shmem_thp: 0kB shmem_pmdmapped: 0kB anon_thp: 0kB writeback_tmp:0kB unstable:0kB all_unreclaimable? yes
Jul 29 19:16:48 catalog-harvester-next1tf kernel: [14982.402973] Node 0 DMA free:7972kB min:364kB low:452kB high:540kB active_anon:7924kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:0kB writepending:0kB present:15992kB managed:15908kB mlocked:0kB kernel_stack:0kB pagetables:12kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
Jul 29 19:16:48 catalog-harvester-next1tf kernel: [14982.402976] lowmem_reserve[]: 0 1906 1906 1906 1906
Jul 29 19:16:48 catalog-harvester-next1tf kernel: [14982.402977] Node 0 DMA32 free:44568kB min:44688kB low:55860kB high:67032kB active_anon:1857848kB inactive_anon:164kB active_file:372kB inactive_file:24kB unevictable:0kB writepending:48kB present:2041832kB managed:1980752kB mlocked:0kB kernel_stack:3008kB pagetables:11048kB bounce:0kB free_pcp:960kB local_pcp:960kB free_cma:0kB
Jul 29 19:16:48 catalog-harvester-next1tf kernel: [14982.402979] lowmem_reserve[]: 0 0 0 0 0
...
Jul 29 19:16:48 catalog-harvester-next1tf kernel: [14982.402992] 217 total pagecache pages
Jul 29 19:16:48 catalog-harvester-next1tf kernel: [14982.402993] 0 pages in swap cache
Jul 29 19:16:48 catalog-harvester-next1tf kernel: [14982.402994] Swap cache stats: add 0, delete 0, find 0/0
Jul 29 19:16:48 catalog-harvester-next1tf kernel: [14982.402995] Free swap  = 0kB
Jul 29 19:16:48 catalog-harvester-next1tf kernel: [14982.402995] Total swap = 0kB
Jul 29 19:16:48 catalog-harvester-next1tf kernel: [14982.402996] 514456 pages RAM
Jul 29 19:16:48 catalog-harvester-next1tf kernel: [14982.402996] 0 pages HighMem/MovableOnly
Jul 29 19:16:48 catalog-harvester-next1tf kernel: [14982.402996] 15291 pages reserved
Jul 29 19:16:48 catalog-harvester-next1tf kernel: [14982.402997] 0 pages cma reserved
Jul 29 19:16:48 catalog-harvester-next1tf kernel: [14982.402997] 0 pages hwpoisoned
...
==> /var/log/gather-consumer.log <==
2020-07-29 19:16:47,608 DEBUG [ckanext.harvest.harvesters.ckanharvester] Searching for CKAN datasets: https://data.doi.gov/api/3/action/package_search?sort=id+asc&start=18000&rows=100

==> /var/log/kern.log <==
Jul 29 19:16:48 catalog-harvester-next1tf kernel: [14982.466648] oom_reaper: reaped process 3179 (ckan), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

********************************
The gather consumer restarts
********************************
==> /var/log/gather-consumer.log <==
2020-07-29 19:16:54,074 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2020-07-29 19:16:54,094 DEBUG [ckanext.harvest.model] Harvest tables already exist
```

**Comment by adborden** [comment]
@avdata99 can you clarify? So after the harvester is killed, does CKAN show the harvest job as being "Finished" but with 0 errors?

**Comment by avdata99** [comment]
To be decided. Possible solutions:
 - Improve the CKAN to CKAN harvester so that it consumes fewer resources (maybe yield each CKAN page results and not wait until finish all pages) 
 - Ensure more resources in the server in which runs
 - Catch the supervisor restarts for the `harvest-gather` process

**Comment by thejuliekramer** [comment]
@adborden I think this was do to postfix which you fixed in https://github.com/GSA/datagov-deploy/issues/1795 is it cool if I close this issue?

**Comment by adborden** [comment]
On Fri, Aug 14, 2020 at 9:25 AM Julie Kramer <notifications@github.com>
wrote:

> @adborden <https://github.com/adborden> I think this was do to postfix
> which you fixed in GSA/datagov-deploy#1795
> <https://github.com/GSA/datagov-deploy/issues/1795> is it cool if I close
> this issue?
>

Yeah, between the postfix fix, the timeout, and the increased resources in
staging/production, let's assume this is no longer an issue.

-- 
Aaron D Borden
Lead Engineer | IT Specialist
TTS | Data.gov <https://www.data.gov>

**Comment by thejuliekramer** [comment]
Blocked by https://github.com/GSA/datagov-ckan-multi/issues/296

**Comment by adborden** [comment]
#296 is QA'd and done. I'm going to move this to icebox.

**Comment by adborden** [comment]
Closing this since we're able to run the DOI harvest in staging. There are still errors but we'll follow up in https://github.com/GSA/datagov-ckan-multi/issues/450
