### ISSUE TITLE
Rebuild Dataset Entry Form

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#326]
## User story
As an agency user, I can easily add metadata and data that complies with the DCAT standard without having to be an expert in the schema or consult a lot of outside materials

**Comment by stephen-tsai** [comment]
@kimwdavidson Findings from cross-browser QA are here.  There are 17 issues I found, and you'll probably want to review all of them for potential launch blockers.  I specifically highlighted 6 that could be higher priority.  Lmk if you have any questions, thanks!  https://docs.google.com/spreadsheets/d/1nkfukAV9JN8xkUo2kEVweaJ9GjLkWYhT_o0A0mx1Y8o/edit#gid=934331518

**Comment by hkdctol** [comment]
Closing for now. Prioritizing epics
