### ISSUE TITLE
Build new form - Required metadata 

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#328]
## Acceptance criteria
- [x] WHEN I add a dataset
- THEN I see fields matching requirements in spreadsheet: 
https://docs.google.com/spreadsheets/d/1bWt_uLloRQ5Rd8HI22COUlIwH_REsywHJ43NmkQNSv0/edit#gid=746832760

## Details/Tasks
- [x] Build the form components 
  - [x] Fields (mostly already done in spike)
  - [x] Fixtures
  - [x] Unit tests
- [x] Get CI working
- [x] Refactor code according to review by Aaron
  - [x] Start building app from vanilla installation of Create React App
  - [x] Documenation
- [x] Replace html templates to override existing dataset form
        - templates/package/snippets/package_form.html
        - templates/package/new_package_form.html
(https://docs.google.com/spreadsheets/d/1bWt_uLloRQ5Rd8HI22COUlIwH_REsywHJ43NmkQNSv0/edit?ts=5ed7d570#gid=0) based on [UX research](https://docs.google.com/presentation/d/1shtG32IppQZt4QZMnzdYDXCem_aAlVhpwt18wF0QbCc/edit#slide=id.g87b1701054_3_3) and [mock ups](https://www.figma.com/file/klRVVF5U6fFmDbiu3s6L3g/Metadata-Form?node-id=22%3A747)

**Comment by starsinmypockets** [comment]
I assume that 

"WHEN I submit my dataset correctly
THEN I see a success message (and page tbd)"

implies a tested CKAN API integration

**Comment by starsinmypockets** [comment]
Based on https://www.figma.com/proto/klRVVF5U6fFmDbiu3s6L3g/Metadata-Form?node-id=714%3A3422&scaling=min-zoom
