### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#329]
## User Story
As a data publisher, when I create a dataset,I want to be able to upload files, so that I can share my data with the public

## Acceptance Criteria
- [ ] WHEN I browse to https://inventory.data.gov/dataset/new-metadata
  AND I go to step 3 of the workflow
  AND I select a resource file to upload (pdf, json, csv, xlsx)
  ~AND I specify the URL X~
  AND I submit my resource
  THEN I see on the dataset page X
  
## Details/Tasks
- https://www.figma.com/file/klRVVF5U6fFmDbiu3s6L3g/Metadata-Form?node-id=308%3A1808

**Comment by adborden** [comment]
FYI, USWDS recently released components for file input https://designsystem.digital.gov/components/form-controls/#file-input

**Comment by cmugisha** [comment]
Blocked because we can't QA until #425 has been resolved.
