### ISSUE TITLE
Remote file link

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#330]
## User Story

As a data publisher, when I add a dataset,I want to be able to link to a file, so that I can share my data with the public

## Acceptance Criteria
- [ ] WHEN I browse to https://inventory.data.gov/dataset/new-metadata
  AND I go to step 3 of the workflow
  THEN I can enter a link to a remote file
  AND I can name my resource
  AND I can submit my resource
  AND I see it on the dataset page X
  
## Details/Tasks
- https://www.figma.com/file/klRVVF5U6fFmDbiu3s6L3g/Metadata-Form?node-id=308%3A1808

**Comment by cmugisha** [comment]
This ticket is blocked by #328
