### ISSUE TITLE
Recruit and schedule user interviews for workflow discovery

### ISSUE THREAD

**Issue by gujacq** [GSA/datagov-ckan-multi#333]
## User Story
As a user researcher, I want to recruit and schedule participants for my user study so that I have users ready to interview.

## Acceptance Criteria
- [ ] 10-15 participants are scheduled, and understand the context of the user study we’re conducting

## Details / tasks
- [x] Draft recruitment templates to participants are aware and prepared for the interviews
- [x] Recruit participants
- [x] Check with data.gov team about need for consent form
- [ ] ~If consent form is needed, draft and build a consent form~

## Resources
Recruitment templates: https://drive.google.com/drive/folders/1-er90CWMYh4UHv_H3xTXVmikeU0ssbcG

**Comment by gujacq** [comment]
Recruitment email templates for @hkdctol and @adborden's review here: https://docs.google.com/document/d/1ZG2rH40W8VosSdcTW9JgbVmcRgVy-1u0ehAO4JdIDdk/edit?ts=5ef26050#

I plan to recruit early next week, so please take a look and let me know if there's anything you'd like to chance. Otherwise, I'll go ahead with these templates (minus the consent form piece) for recruiting.

**Comment by gujacq** [comment]
P.S. added this to review for the recruitment email templates for @hkdctol and @adborden's awareness, but it's not ready for done until participants are recruited

**Comment by hkdctol** [comment]
Email templates look fine.
