### ISSUE TITLE
dataset counts on organization page vs harvest page don't match

### ISSUE THREAD

**Issue by thejuliekramer** [GSA/datagov-ckan-multi#337]
## Description:
Datasets on harvest source page and on organization page don't reflect the same number of datasets. 

## To replicate:
- Go to https://catalog-next.sandbox.datagov.us/harvest/doj-json
- Observe number of datasets
- Go to https://catalog-next.sandbox.datagov.us/organization/doj-gov
- Observe number of datsets
Expected behavior: 
- TBD
Current behavior 
- Datasets on the harvest source page (987)
- Datasets on the organization page (995)

## Acceptance Criteria
- The number of datasets when filtering by organization is correct and matches to the number of datasets pulled in from the harvest source(s)

## Details / tasks

- [ ] Research how the count is calculated
- [ ] Fix code so that the count is accurate

**Comment by adborden** [comment]
@thejuliekramer can you give an example? I've seen a similar behavior in the past: the +1 is the harvest source.

**Comment by thejuliekramer** [comment]
I was trying to recreate this issue in production catalog but I couldn't find an example - I know this was brought up during collections discovery with @pjsharpe07, but it seems like the collections count is correct from what I can see
<img width="872" alt="Screen Shot 2020-06-22 at 4 46 07 PM" src="https://user-images.githubusercontent.com/7378770/85338577-2a92f180-b4a8-11ea-89ef-61b2721334b5.png">

**Comment by jbrown-xentity** [comment]
I believe this is in reference to harvest sources. If you look at dataset counts by organization in the filter section on the main page, you'll see the actual dataset count. If you go to the organization page, you see harvest sources + datasets, and it's an inaccurate number. Can pair tomorrow if not clear.

**Comment by adborden** [comment]
I just want to make sure the description has enough information for someone unfamiliar with the issue to be able to pick it up.

**Comment by thejuliekramer** [comment]
Ok I am not sure if this is related to collections then @jbrown-xentity, I might not be understanding correctly?

**Comment by thejuliekramer** [comment]
@jbrown-xentity Trying to find an example on the organization page but I don't see the harvest sources there either - maybe it was something in CKAN core causing it <img width="994" alt="Screen Shot 2020-06-23 at 12 49 52 PM" src="https://user-images.githubusercontent.com/7378770/85437344-0e4a8f80-b550-11ea-9463-5ba5543de4fa.png">

**Comment by jbrown-xentity** [comment]
Quite possibly. I didn't realize this was related to collections, my mistake. I believe this is in reference to dataset counts, example from DOJ below (there are others):
You can look at a dataset count for a harvest source by going to the [harvest source](https://catalog.data.gov/harvest/9a4f8e20-d21a-4d97-bbc6-c354916e379f), you'll see 1,224. This reflects the number of entries in the data.json array.
You can also see a dataset count for a harvest source by going  to the [organization page and filtering on the harvest source](https://catalog.data.gov/organization/e1f5f374-0d6d-47a5-8fb2-5285a01053ba?harvest_source_title=DOJ+JSON), this gives you 949. This references the number of true datasets created from the data.json.
We believe this is related to the collections feature, of which there are a number in this harvest source (for [example](https://catalog.data.gov/dataset/informal-enforcement-actions)).

**Comment by thejuliekramer** [comment]
Ok that makes sense now, I can reproduce this in the catalog environment using DOJ as an example 

Datasets on the harvest source page (987): https://catalog-next.sandbox.datagov.us/harvest/doj-json 
Datasets on the organization page (995): https://catalog-next.sandbox.datagov.us/organization/doj-gov

**Comment by avdata99** [comment]
Is working in the new production environment

https://catalog-next.data.gov/harvest/doj-json
https://catalog-next.data.gov/organization/doj-gov

![image](https://user-images.githubusercontent.com/3237309/99095443-e79afd00-25b3-11eb-9644-b7039d45043d.png)

**Comment by avdata99** [comment]
Tracking is enabled but it's failing when we call it from web

![image](https://user-images.githubusercontent.com/3237309/99099670-89711880-25b9-11eb-9d58-2f6c2e66d6db.png)

**Comment by hkdctol** [comment]
Confirmed.
