### ISSUE TITLE
Spike: login.gov 

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#338]
## User story
As a catalog admin, I want to be able to access the new catalog via login.gov so I can use an already compliant tool

## Details/Tasks
- [ ] is there an upstream solution that doesn't require us to fork the SAML extensions (pysaml2 and ckanext-saml) of login.gov

**Comment by woodt** [comment]
Created identity sandbox account at login.gov, reviewed documentation.  First question that comes up: login.gov supports two implementation protocols: SAML and Open ID Connect.  They strongly recommend Open ID Connect (which is built on top of OAuth 2). 

(1) Do we care?  For example, do we depend some user info (claims) that isn't available in OIDC?
(2) What is the status of ckan OIDC support, if any?

**Comment by adborden** [comment]
Attempting to capture the conversation from our daily sync:

We should reach out to the CKAN community for any pre-existing work for
OpenID Connect extensions for CKAN.

There is a preference for using OpenID Connect over SAML2. The SAML2
spec is complex, so we think working with OpenID Connect would be
simpler for development.

Given that there are no tests for ckanext-saml2 and pysaml2 is already
missing functionality we need (persistent storage), there's not much
of an advantage to sticking with ckanext-saml2.

--
Aaron D Borden
Human and hacker

**Comment by woodt** [comment]
Using the saml implementation of login.gov, I succeeded in getting a SAML2 response back from login.gov using ckanext-saml2 0.3.1 and pysaml2 v4.9.0.  pysaml2 required a tweak to the repoze.who plugin:

```
diff --git a/src/saml2/s2repoze/plugins/sp.py b/src/saml2/s2repoze/plugins/sp.py
index afc7453..cce4e14 100644
--- a/src/saml2/s2repoze/plugins/sp.py
+++ b/src/saml2/s2repoze/plugins/sp.py
@@ -470,7 +470,7 @@ class SAML2Plugin(object):
 
         is_request = "SAMLRequest" in query
         is_response = "SAMLResponse" in query
-        has_content_length = "CONTENT_LENGTH" in environ or environ["CONTENT_LENGTH"]
+        has_content_length = environ.get("CONTENT_LENGTH")
 
         if not has_content_length and not is_request and not is_response:
             logger.debug("[identify] get or empty post")
@@ -482,6 +482,8 @@ class SAML2Plugin(object):
         else:
             post = self._get_post(environ)
             binding = BINDING_HTTP_POST
+            is_request = "SAMLRequest" in post.keys()
+            is_response = "SAMLResponse" in post.keys()
 
         try:
             logger.debug("[sp.identify] post keys: %s", post.keys())
```

**Comment by woodt** [comment]
Best bet (IMHO) moving forward in the short term is to stick with SAML2 but try to move over to login.gov (appears to be much easier to configure, and to set up test environments.)

Story notes:

# As a developer, I want to test catalog.data.gov authentication using login.gov in the sandbox.
## Acceptance criteria:

Given that a test user account is created in the login.gov identity sandbox
When I visit the catalog login page I am redirected to login.gov
Then I can login using the test account credentials and
Then I am redirected back to the catalog application and
Then I am logged in.

## Tasks:
- configure a test team on the login.gov identity sandbox
- configure an application for catalog-next sandbox on the the login.gov identity sandbox:
-- Issuer string: something like urn:gov:gsa:SAML:2.0.profiles:sp:sso:datagovus:catalog-next-sandbox
-- PEM encoded public certificate
-- Return to app URL
-- Push notification URL
-- Redirect URL(s) after authentication
-- Desired profile attributes (note that to get more than e-mail and id we need IAL 2 identity proofing.)
- Retrieve idp metadata from https://idp.int.identitysandbox.gov/api/saml/metadata2020
- Based on Paul's recent saml2 work, configure catalog-next
- Note: it looks like login.gov does a POST back to the aapplication to deliver the SAML auth response.  The existing saml2 repoze.who plugin seems to expect a GET request; some tweaks may be
  required.

# As data.gov staff, I  want to authenticate with catalog-next in the staging environment using login.gov
## Tasks
- Catalog configuration as needed
- Q: should we continue to use the login.gov identity sandbox?

# As data.gov staff, I  want to authenticate with catalog-next in the production using login.gov
## Tasks
- Catalog configuration as needed
- Contact login.gov for production setup
- Create required user accounts

**Comment by woodt** [comment]
One note about the login.gov OpenID Connect support ... login.gov does *not* support client credentials using a client secret; they only support private_key_jwt.  Admittedly, this is probably a good choice from a security perspective, but many OAuth2 implementations don't seem to support this yet--they expect the authorization server to provide a client id and secret at registration time.

See https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication

**Comment by woodt** [comment]
Created ticket #354 to capture possible need to patch pysaml2.

**Comment by woodt** [comment]
I _think_ this is ready to be QA'd, given the four created tickets.

**Comment by adborden** [comment]
Looks good, :+1:
