### ISSUE TITLE
Analyze workflow interviews (initial round)

### ISSUE THREAD

**Issue by gujacq** [GSA/datagov-ckan-multi#344]
## User Story
As a UX researcher, I want to analyze the initial round of user interviews so I can understand the information and update the research plan

## Acceptance Criteria
- [x] We analyze 3-4 user interviews and make updates to the research plan

## Details / tasks
- [x] Record and analyze each user interview
- [x] Produce deck on findings
- [x] Edit interview guide to reflect findings if necessary

**Comment by gujacq** [comment]
This ticket will carry on to the next sprint (week of July 20th)

**Comment by stephen-tsai** [comment]
Adding the recording of the Design Review (https://civicactions.zoom.us/rec/share/wshsIYzizWhJQoWS6R3uGYN4G6b9X6a80CJK_vQNz0zIKzucUFIzaHusssav2IYz Password: +svHy5UJ) and the Slide Deck (https://docs.google.com/presentation/d/1ucw-7x_elI1DOAMh3FQlmsRSUuT8c7YPpH69Bg-4msE/edit) where we shared findings from the initial round of workflow discovery research.
