### ISSUE TITLE
Configure solr properly

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#345]
## Description
Currently, the [datagov-deploy-solr](https://github.com/GSA/datagov-deploy-solr/blob/master/tasks/configure.yml) role configures individual solr core with only the CKAN schema and missing all the other recommended configuration. This is described in the [CKAN docs](https://docs.ckan.org/en/2.8/contributing/test.html?highlight=solr#configure-solr-multi-core) (specifically, copying the template core directory). The files that should exist are described in [ckan-cloud-docker](https://github.com/datopian/ckan-cloud-docker/blob/master/solr/Dockerfile#L11-L17) and in [catalog-solr](https://github.com/GSA/catalog-solr/blob/feature/inventory/Dockerfile). These are just using the out-of-the-box configuration provided by solr.

## Details/Tasks
- Check documentation in CKAN
- Look at stop words
- Make sure what we configure in solr in ansible playbooks is doing what documentation recommends
- If it's not, document why or make appropriate changes
- Keep version at 5.5.5

**Comment by woodt** [comment]
Looks like the configuration, especially w.r.t. stop words is correct on sandbox.  Want to confirm what is what on staging and then this will be done.

**Comment by woodt** [comment]
OK.  So I confirmed that the staging config seemed to match sandbox (and ckan documentation.)  Before declaring this done, though, I wanted to run some tests to see if the stop word filtering actually worked (as opposed to just matching the documentation and schema.xml from ckan.)  Guess what?  I don't think it does.

I ran tests using the admin UI and the field analysis API and discovered that both in the development environment and on sandbox, stop word filtering is not being applied to index or queries.

I suggest that we create a ticket to add the following filters to text fields in the CKAN schema:

For indexing:

```
<filter class="solr.StopFilterFactory" words="stopwords.txt" ignoreCase="true"/>
```

For querying:

```
<filter class="solr.SuggestStopFilterFactory" ignoreCase="true" words="stopwords.txt" format="wordset"/>
```

**Comment by woodt** [comment]
Created ticket #375.

**Comment by woodt** [comment]
I'm going to move this to QA, as the discovery is done.

**Comment by adborden** [comment]
Great information in our sprint review https://drive.google.com/file/d/10d2Qte5TrmpaqUrJgJtp0bN9PTwrMFO9/view?usp=sharing
