### ISSUE TITLE
catalog-next authentication in staging using login.gov

### ISSUE THREAD

**Issue by woodt** [GSA/datagov-ckan-multi#349]
## User Story

As data.gov staff, I want to authenticate with catalog-next in the staging environment using login.gov

## Acceptance Criteria
- [ ] Go to admin-catalog-datagov.dev-ocsit.bsp.gsa.gov
- [ ] Login with login.gov

## Details / tasks
- Catalog configuration as needed
- Contact login.gov for production setup [done]

- Generate new certificate(s)

[login.gov dashboard]
- Create a new app on the dashboard https://dashboard.int.identitysandbox.gov/
- Enter a Friendly Name (Title) with "Staging" or "Production" in the title
- Enter the staging/production urls and configuration into the app

All production urls should have .gov .mil or a dedicated .com address and point to an ATO'd environment.

If your app does not have a logo, then you will need to upload one. You can find the logo guidelines here:
https://developers.login.gov/design-guidelines/#agency-logo-guidelines

If this is an SAML integration (Not OpenID Connect), then please ensure that:
- SAML Assertion Encryption is enabled
- Assertion Consumer Logout Service URL is defined.

Need to update ansible variables for catalog-next in staging.

**Comment by woodt** [comment]
I created a ticket to capture the assertion encryption requirement. (#532)

**Comment by cmugisha** [comment]
@thejuliekramer Can you estimate this?

**Comment by thejuliekramer** [comment]
PR for settings in production and staging https://github.com/GSA/datagov-deploy/pull/2640

**Comment by thejuliekramer** [comment]
Testing now in staging and getting this error <img width="1352" alt="Screen Shot 2021-01-13 at 10 12 41 AM" src="https://user-images.githubusercontent.com/7378770/104478923-77473280-5588-11eb-97a9-7fb890c04cf5.png">

**Comment by thejuliekramer** [comment]
Error in production
<img width="1324" alt="Screen Shot 2021-01-13 at 10 37 23 AM" src="https://user-images.githubusercontent.com/7378770/104481528-824f9200-558b-11eb-96e1-df5e95572ac5.png">

**Comment by thejuliekramer** [comment]
Production error <img width="1329" alt="Screen Shot 2021-01-13 at 10 40 15 AM" src="https://user-images.githubusercontent.com/7378770/104481729-bd51c580-558b-11eb-83e1-e0935b102a45.png">

**Comment by thejuliekramer** [comment]
Decoded Saml response

`<samlp:Response ID="_00e014c0-37ec-0139-f79c-06728617af77" Version="2.0" IssueInstant="2021-01-13T16:40:43Z" Destination="https://catalog-next.data.gov/acs" Consent="urn:oasis:names:tc:SAML:2.0:consent:unspecified" InResponseTo="id-SoPeNgORUToeIpray" xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"><Issuer xmlns="urn:oasis:names:tc:SAML:2.0:assertion">https://idp.int.identitysandbox.gov/api/saml</Issuer><samlp:Status`

**Comment by thejuliekramer** [comment]
@jbrown-xentity I am getting this error while trying to log in on catalog-next staging - the same configuration we are using in catalog-next prod is  working successfully - do you know why this might be happening in just staging?

**Comment by adborden** [comment]
@thejuliekramer and I updated `saml2_idp_entry` which is used in the apache config for the redirect. The issue here was that admin-catalog wasn't recognizing the referrer from login.gov and then redirect to catalog instead of processing the login request.

**Comment by adborden** [comment]
Confirmed this is working in staging. We're still working with Login.gov to promote the application out of sandbox. I opened https://github.com/GSA/datagov-deploy/issues/2673 to track.
