### ISSUE TITLE
[Epic] As a Platform Admin, I want to manage instances and instance maintainers so that I control users and instances on my platform

### ISSUE THREAD

**Issue by michellecbox** [GSA/datagov-ckan-multi#35]
As a platform admin, I should be able to do everything an instance maintainer can 
https://github.com/GSA/datagov-ckan-multi/issues/30
As a platform admin, I should be able to create a new instance, so that I can hand them over to instance maintainer 
https://github.com/GSA/datagov-ckan-multi/issues/4
As a platform admin, when I create a new instance, I should automatically become an instance admin of that instance, so that I can continue to administer it 
https://github.com/GSA/datagov-ckan-multi/issues/5
As a platform admin, when I create a new instance, I should be able to choose between a few predefined configurations for instances with different extension combinations 
https://github.com/GSA/datagov-ckan-multi/issues/8
As a platform admin, I should be able to create a custom DNS for my instance, so that it can have its own URL 
https://github.com/GSA/datagov-ckan-multi/issues/31
As a platform admin, I can add users to the platform, and set their role (platform admin or maintainer) 
https://github.com/GSA/datagov-ckan-multi/issues/32 
As a platform admin, I can view which users have access  to the platform as well as their roles  
https://github.com/GSA/datagov-ckan-multi/issues/33
As a platform admin, I can remove users from the platform (but not myself)  
https://github.com/GSA/datagov-ckan-multi/issues/34
Create Dashboard page mockup
https://github.com/GSA/datagov-ckan-multi/issues/28
Create mockup of UI for instance creation
https://github.com/GSA/datagov-ckan-multi/issues/6

TBD-Optional

Logging monitoring and alerts
https://github.com/GSA/datagov-ckan-multi/issues/17
Determine theme options
https://github.com/GSA/datagov-ckan-multi/issues/22
Delete instance
https://github.com/GSA/datagov-ckan-multi/issues/39

**Comment by akariv** [comment]
Completed in stage #1
