### ISSUE TITLE
catalog-next authentication in production using login.gov

### ISSUE THREAD

**Issue by woodt** [GSA/datagov-ckan-multi#350]
## User Story

As data.gov staff, I want to authenticate with catalog-next in production using login.gov

## Acceptance Criteria
- [ ] Go to catalog-next.data.gov
- [ ] Log in with login.gov 

## Details / tasks
- Catalog configuration as needed
- Contact login.gov for production setup
- Create required user accounts

**Comment by thejuliekramer** [comment]
PR for settings in production and staging GSA/datagov-deploy#2640

**Comment by adborden** [comment]
I can successfully login on production with the identity sandbox. I opened https://github.com/GSA/datagov-deploy/issues/2673 to promote the app to their production environment.
