### ISSUE TITLE
Recruit and schedule for rest of workflow discovery interviews

### ISSUE THREAD

**Issue by gujacq** [GSA/datagov-ckan-multi#351]
## User Story
As a user researcher, I want to recruit and schedule participants for my user study so that I have users ready to interview.

## Acceptance Criteria
- [x] 7-13 participants are scheduled, and understand the context of the user study we’re conducting

## Details / tasks
- [x] set up calendly link
- [x] Recruit participants (initial email, possibly follow-up email, confirmation email of interview, confirmation email day before interview)

## Resources
Recruitment templates: https://docs.google.com/document/d/1ZG2rH40W8VosSdcTW9JgbVmcRgVy-1u0ehAO4JdIDdk/edit

**Comment by gujacq** [comment]
From Hyon's email on June 23rd:

Agencies with problems uploading metadata: (I'll have to look again)

Agencies that would benefit from a data management tool:

- Nate Heard HeardNJ@state.gov

- Yen Shan - SBA - experienced in this schema, would be good perspective of more experienced open data lead

-
Agencies that have not started with data.gov: (these agencies do have datasets in Data.gov, but I'd consider these users to be "new" to Data.gov)

- Gulam Shakir - NARA - new name, indicates to me this is someone new to open data work with this schema
- Stephen Konya - SEC - also a new name. Not sure they consider themselves as required to do this under open data law, but would guess relatively new to the schema


I don't think these 3 fall into the three categories:

Lorna Schmid - USGS - lead on geospatial community- doesn't work much in the project open data schema but her perspective would be good and she might identify issues **Already contacted in the initial round twice and never got back, so I would de-prioritize her**

Brandon P. from USAID - longtime open data, a CDO, if you're looking for a senior person perspective, agency wide, etc. probably has good outlook on an agency wide, internal workflow problems, etc

Tod Dabolt - very senior, leadership role in geospatial, probably for very big picture perspective though he has extensive knowledge of details in metadata problems as well **He's one of the people who signed up in our survey moneky already so def should reach out to him**

**Comment by stephen-tsai** [comment]
Participant recruitment spreadsheet:

https://docs.google.com/spreadsheets/d/1Hw54U7JQzj16BnV0fzrH79wRgJmwph-LzQkFmkrK9RI/edit#gid=0
