### ISSUE TITLE
QA CKAN 2.5 form

### ISSUE THREAD

**Issue by gujacq** [GSA/datagov-ckan-multi#352]
## User Story
As a UX designer, I want to QA the build so that I can make sure the designs are built to spec. 

## Acceptance Criteria
- [ ] The backend and frontend interactions work across defined browsers and mobile devices

## Details / tasks
- [ ] Define which browsers/browser version and mobile devices that we QA against
- [ ] Set up QA workflow and tracking
- [ ] QA
- [ ] Review QA tickets with development
- [ ] Follow-up on QA

## Resources

**Comment by adborden** [comment]
Inventory doesn't see a lot of users, but here's the data on browsers. Anything above 2% should be included, but the numbers are so low and I suspect GSA inflates the Chrome users. Let's start with this list:
- Chrome
- Edge
- IE11
- Firefox

![Screen Shot 2020-09-21 at 6 53 19 PM](https://user-images.githubusercontent.com/509703/93837675-f0b6c000-fc3b-11ea-8691-3ef81a3ca7e9.png)

**Comment by gujacq** [comment]
We should add language saying you need to type then press enter to add tags. I originally typed tags out and separated them with commas, which resulted in an error so it's not entirely clear how a user adds tags

**Comment by gujacq** [comment]
tool tip should automatically close any time a user clicks out or interacts with another element on the form. right now, they stay open until the user clicks the icons again or the x

**Comment by gujacq** [comment]
Public Access Level dropdown options are incomplete. Should be:

Public - this dataset can be made publicly available to all without restrictions

Restricted Public - this dataset is available under certain use restrictions

Non-Public - this dataset is not available to members of the public

See metadata form spreadsheet for more detail: https://docs.google.com/spreadsheets/d/1bWt_uLloRQ5Rd8HI22COUlIwH_REsywHJ43NmkQNSv0/edit#gid=746832760

**Comment by gujacq** [comment]
Right now it's allowing me to set the start date after the end date without an error. We need to also update the text for the second date field to say "provide **end** date"

<img width="948" alt="Screen Shot 2020-09-25 at 5 59 39 PM" src="https://user-images.githubusercontent.com/33872753/94322800-1a802780-ff59-11ea-9fe6-f4846f04326d.png">

**Comment by gujacq** [comment]
Remove "save as draft" button if it's not going to be functional on release

**Comment by gujacq** [comment]
entering into editing a dataset from this page takes me to the original form design, not the new form.

<img width="964" alt="Screen Shot 2020-09-25 at 6 02 35 PM" src="https://user-images.githubusercontent.com/33872753/94322859-587d4b80-ff59-11ea-9c6b-3de601033f98.png">

<img width="979" alt="Screen Shot 2020-09-25 at 6 02 41 PM" src="https://user-images.githubusercontent.com/33872753/94322869-5f0bc300-ff59-11ea-8d47-468157ef1278.png">

**Comment by gujacq** [comment]
link to data on the resource upload page is confusing: 

- when you click on it, it gives a field for the URL. the guidance text, "if you are linking to a dataset..." should be outside of the text field, otherwise it violates accessibility standards

- There's no confirmation of the URL being entered taking. We need some kind of enter or commit button. (This was confusing during user testing)

- The remove button was also confusing. I suggest we remove that and have the URL field show up _under_ the upload data and link to data buttons so those options never disappear.

**Comment by gujacq** [comment]
License field dropdown also needs to follow the spreadsheet: https://docs.google.com/spreadsheets/d/1bWt_uLloRQ5Rd8HI22COUlIwH_REsywHJ43NmkQNSv0/edit#gid=746832760

**Comment by gujacq** [comment]
Right now, users are able to land on each page without having to save and continue using the navigation at the top, but I feel like we should disable this to avoid confusion about being able to advance (since they really shouldn't unless they fill out the required metadata in the first page.

**Comment by gujacq** [comment]
Clicking on any help text links takes you off the page. If you navigate back, you lose what you've entered on that page. I'm wondering if we can either include a warning message about this when people click off _or_ have it open in a new tab or window and include an icon that indicates such.

**Comment by gujacq** [comment]
Media type field says to start typing, but it's a dropdown instead

<img width="925" alt="Screen Shot 2020-09-25 at 6 23 20 PM" src="https://user-images.githubusercontent.com/33872753/94323652-42bd5580-ff5c-11ea-8aca-05b96e43a402.png">
