### ISSUE TITLE
to support login.gov authentication for catalog-next, (possibly) apply patch to pysaml2

### ISSUE THREAD

**Issue by woodt** [GSA/datagov-ckan-multi#354]
Using the saml implementation of login.gov, I succeeded in getting a SAML2 response back from login.gov using ckanext-saml2 0.3.1 and pysaml2 v4.9.0. pysaml2 required a tweak to the repoze.who plugin:

```diff
diff --git a/src/saml2/s2repoze/plugins/sp.py b/src/saml2/s2repoze/plugins/sp.py
index afc7453..cce4e14 100644
--- a/src/saml2/s2repoze/plugins/sp.py
+++ b/src/saml2/s2repoze/plugins/sp.py
@@ -470,7 +470,7 @@ class SAML2Plugin(object):
 
         is_request = "SAMLRequest" in query
         is_response = "SAMLResponse" in query
-        has_content_length = "CONTENT_LENGTH" in environ or environ["CONTENT_LENGTH"]
+        has_content_length = environ.get("CONTENT_LENGTH")
 
         if not has_content_length and not is_request and not is_response:
             logger.debug("[identify] get or empty post")
@@ -482,6 +482,8 @@ class SAML2Plugin(object):
         else:
             post = self._get_post(environ)
             binding = BINDING_HTTP_POST
+            is_request = "SAMLRequest" in post.keys()
+            is_response = "SAMLResponse" in post.keys()
 
         try:
             logger.debug("[sp.identify] post keys: %s", post.keys())
```

We should investigate whether this patch is really necessary, and whether it would impact other clients of pysaml2.

**Comment by adborden** [comment]
FYI, I have the pysaml2 v4.9.0 tests running in CI on the [feature/ci branch](https://github.com/GSA/pysaml2/tree/feature/ci). Assuming you don't need any of the MAX.gov fork, you should base your patch on this branch. Hopefully we can just push your patch upstream?

**Comment by adborden** [comment]
... oh right, even with patches upstream, they're not support python2, so we're stuck with a fork of v4.9.0 anyway.

**Comment by cmugisha** [comment]
Hi @woodt! How much time is left on this ticket? Could you update the estimate before sprint planning? Thanks!

**Comment by woodt** [comment]
Just to follow up, this patch was still necessary for the version of pysaml that Aaron has been working with. 
 Patch at https://github.com/GSA/pysaml2/pull/3 merged.  Wrote a new test, and fixed the Python dependencies so the old repoze.who plugin tests would run.

**Comment by woodt** [comment]
All tests pass under ci.  Merged to feature/ci branch.
