### ISSUE TITLE
Harvest data into new catalog

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#356]
## User Story
As a data consumer, I want to see all the available data in one place, so that I can easily find what I'm looking for

## Acceptance Criteria
- All harvesters run to completion

## Details/Tasks
- create script to check harvest status
- Hyon to identify exceptions to weekly harvests

**Comment by avdata99** [comment]
Analyzing random sources to run and checking sandbox logs:

Source https://catalog-next.sandbox.datagov.us/harvest/aid-dashboard
```
Transformation to ISO failed
```
Error already described in #323. The source shows as _running_ in the UI. It is required to show an error.

Source https://catalog-next.sandbox.datagov.us/harvest/cspc-json-file
```
Error 404 gather_stage (http://www.cpsc.gov/data.json)
```
We fail to capture these errors. The source shows as _running_ in the UI. It is required to show an error
To add a new issue

Source https://catalog-next.sandbox.datagov.us/harvest/nc-onemap-csw
```
Error contacting the CSW server: Opening and ending tag mismatch: meta line 29 and head, line 40, column 10 (line 40)
```
The source shows as _running_ in the UI. It is required to show an error

Source https://catalog-next.sandbox.datagov.us/harvest/restore-the-gulf
```
Error contacting the CSW server: ('The read operation timed out',)
```
The source shows as _running_ in the UI. It is required to show an error

Source https://catalog-next.sandbox.datagov.us/harvest/neh-source: Works as expected.

**Comment by kimwdavidson** [comment]
Timeboxed to 8/21/20

**Comment by hkdctol** [comment]
Looking at some of the non-federal data.json results on sandbox, they all have this timeout error. I checked for NYState which has a valid, current harvest source and is being regularly harvested in production. 

![Screen Shot 2020-08-19 at 4 28 08 PM](https://user-images.githubusercontent.com/3236989/90686377-3fd29500-e239-11ea-8454-abf495f552a4.png)
![Screen Shot 2020-08-19 at 4 27 57 PM](https://user-images.githubusercontent.com/3236989/90686392-46610c80-e239-11ea-9027-7ff191745e1d.png)

**Comment by hkdctol** [comment]
No clear pattern except all the non-federal in most recent harvest jobs have the timeout error, even though harvest jobs around the same time of federal data.json show normal results. But also found successful non-federal harvests from earlier in August (City of Chicago).

**Comment by avdata99** [comment]
@hkdctol We added that timeout weeks ago because many harvesting processes were stuck due to problems sending notifications by email or due to the large size of the work.
Some sources were imported with the previous version of the import script so they have some flaws.
In cases of failure, the process is to re-import the origin and run the harvesting process again.
I re-imported the origin _ny-state-json_ but it still fails. It appears to be treated as federal when configured as non-federal. I will check

**Comment by hkdctol** [comment]
Have QAd for data.json, WAF and WAF Collection, moving to done.
