### ISSUE TITLE
Determine final QA walkthrough scenarios

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#357]
## User Story
As data.gov staff, I want to feel confident that I am releasing a production ready product, so that my users will have everything they need

## Acceptance criteria
- Create QA walkthrough ticket
- Our most important scenarios are documented in behat format

## Details/Tasks
- Onboard a new agency/organization
- Create a new harvest source
- Trigger a re-harvest for an existing DCAT-US harvest source
- Search for and download popular datasets, e.g. FRPP, IOLP, etc
- package_search API is working, e.g. find all datasets for GSA via API

**Comment by adborden** [comment]
Draft QA scenarios https://docs.google.com/document/d/1il7Xo3tvBl5hlpQZvkioGDAJx6kWN4cd55JuXL8-iuw/edit#

**Comment by hkdctol** [comment]
Made one comment to the draft QA scenarios documents but overall it looks good.
