### ISSUE TITLE
OPM listed as non-federal organization in sandbox

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#370]
OPM datasets have the non-federal banner, but is a federal organization.
> This is a Non-Federal dataset covered by different Terms of Use than Data.gov.

![Screen Shot 2020-07-29 at 3 07 24 PM](https://user-images.githubusercontent.com/509703/88858684-3c556c00-d1ad-11ea-913c-1c6ac424e11d.png)

## How to reproduce

1. https://catalog-next.sandbox.datagov.us/dataset/annual-performance-reports-aprs

## Expected behavior

Banner does not appear for OPM or other federal organizations.

## Actual behavior

Non-federal banner appears.

**Comment by adborden** [comment]
This might just be a side-effect of how the organization was imported. On catalog-next OPM is missing some metadata that exists on catalog.data.gov.

[catalog.data.gov](https://catalog.data.gov/organization/opm-gov) shows `organization_type: Federal Government` in the metadata but [sandbox](https://catalog-next.sandbox.datagov.us/organization/about/opm-gov) shows none.

**Comment by avdata99** [comment]
Related to #355

**Comment by thejuliekramer** [comment]
@adborden this is fixed after I updated the script in #355

**Comment by adborden** [comment]
Confirmed!
