### ISSUE TITLE
Some icons not rendering on dataset page

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#371]
Some icons are not rendering on the dataset page.
![Screen Shot 2020-07-29 at 3 16 18 PM](https://user-images.githubusercontent.com/509703/88859725-28ab0500-d1af-11ea-882c-175833f59cd7.png)

## How to reproduce

1. https://catalog-next.sandbox.datagov.us/dataset/annuitants-added-to-the-annuity-roll-processing-system-arps

## Expected behavior

Icons should render or be removed.

## Actual behavior

Some icons do not appear.

**Comment by adborden** [comment]
IMHO CKAN is a bit icon heavy, and I would be interested in removing some icons rather than fixing this issue.

**Comment by thejuliekramer** [comment]
@adborden this is fixed in sandbox <img width="819" alt="Screen Shot 2020-08-26 at 2 06 05 PM" src="https://user-images.githubusercontent.com/7378770/91345771-8417e500-e7a5-11ea-8729-cc5abd26da85.png">

**Comment by adborden** [comment]
Looks good, thanks!
