### ISSUE TITLE
Python New Relic agent and instrumentation for catalog-next

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#372]
## User Story

As a Data.gov operator, I want catalog-next reporting to New Relic so that I can monitor and observe performance hook into existing alerting infrastructure.

## Acceptance Criteria
- [ ] WHEN I visit the [New Relic dashboard](https://one.newrelic.com/) for catalog-next staging
  THEN I see catalog-next is reporting data

## Details / tasks

Instructions are explained in the [New Relic docs](https://docs.newrelic.com/docs/agents/python-agent). Generally the tasks are:
- [ ] Add newrelic python dependency to poetry/requirements
- [ ] Configure New Relic through environment variables
- [ ] Ensure staging is reporting as "catalog-next (staging)", production as "catalog-next", and sandbox is not reporting; similar to the existing configuration for catalog-classic
- [ ] Update datagov-deploy to set the correct environment variables per environment

## Background

Historically, New Relic has been configured [incorrectly for data.gov's python applications](https://github.com/GSA/datagov-deploy/issues/174), hooking into the apache wsgi config instead of implemented at the application level. This has a number of issues, but most importantly, since catalog-next uses gunicorn instead of apache, the New Relic agent essentially isn't configured at all.

**Comment by kimwdavidson** [comment]
Duplicate. Closing
