### ISSUE TITLE
"Metadata Source" section is missing from dataset page on catalog-next

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#373]
The "Metadata Source" section shows the original metadata used to harvest this dataset. It's missing from the dataset page on catalog-next.

### catalog-classic
![Screen Shot 2020-07-30 at 11 32 18 AM](https://user-images.githubusercontent.com/509703/88960535-86475c00-d258-11ea-9c72-da49b78d9c9c.png)

---

### catalog-next
![Screen Shot 2020-07-30 at 11 32 37 AM](https://user-images.githubusercontent.com/509703/88960572-93fce180-d258-11ea-8cbb-0976517dbfa6.png)

## How to reproduce

1. http://catalog-next.sandbox.datagov.us/dataset/social-media-presence

## Expected behavior

Metadata Source section exists showing the original metadata source from the harvest, the harvest source (dataset), and the html rendering of the metadata.

## Actual behavior

Metadata Source section is absent.

**Comment by kimwdavidson** [comment]
It's back:
![Screen Shot 2020-08-30 at 10 39 47 PM](https://user-images.githubusercontent.com/22527532/91677770-b745d580-eb11-11ea-9671-fcd4ae4445b2.png)
