### ISSUE TITLE
add stop word filtering to catalog-next solr schema.xml

### ISSUE THREAD

**Issue by woodt** [GSA/datagov-ckan-multi#375]
Although it turns out that there are bits and pieces of solr configuration that comes close to turning on stop word filtering, it doesn't quite do the job.

We should add the missing analyzer filters to the catalog-next Solr schema.xml, and make sure the stopwords.txt file is up to date.   Should be able to take care of this in the datagov-deploy-solr repo.

Acceptance criteria:

[ ] When I submit a query containing common English stopwords (e.g., "*The* Department *of* Education")
[ ] Then "the" and "of" are filtered from queries, as demonstrated via the Solr analysis tools (either via the web UI, or the /analysis/field API endpoint.)

**Comment by woodt** [comment]
See PR https://github.com/GSA/datagov-deploy-solr/pull/18

**Comment by woodt** [comment]
To QA this properly, the https://github.com/GSA/datagov-deploy-solr/pull/18 PR should be merged and deployed to sandbox.

I would also recommend rebuilding the CKAN Solr index.

**Comment by woodt** [comment]
The PR above has been merged and deployed.  Next (and final) step is to rebuild the Solr index, which I'm proposing to do over the weekend, Aug 15 - 16.

**Comment by woodt** [comment]
Running reindex on catalog-next web host ala

```
paster --plugin=ckan search-index rebuild -c /etc/ckan/production.ini
```

**Comment by woodt** [comment]
```
ckan.lib.search.common.SearchIndexError: Solr returned an error: (u'Solr responded with an error (HTTP 400): [Reason: Exception writing document id 2a12fbaf52bf6747aaf8f4fdc0e91b866439cfd3 to the index; possible analysis error: Document contains at least one immense term in field="status" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: \'[123, 39, 106, 111, 98, 95, 99, 111, 117, 110, 116, 39, 58, 32, 49, 44, 32, 39, 116, 111, 116, 97, 108, 95, 100, 97, 116, 97, 115, 101]...\', original message: bytes can be at most 32766 in length; got 36941. Perhaps the document has an indexed string field (solr.StrField) which is too large]',)
```

**Comment by woodt** [comment]
Index rebuild completed!

Testing results are, um, unclear and so far, odd.  Example:

On data.gov, searching for "salaries employees" returns 120 datasets.
on catalog-next.data.gov, same query returns 60 datasets.  Note that catalog-next has far fewer datasets at the moment then data.gov, so this difference doesn't really mean anything.

On data.gov, searching for "salaries of employees" (stop word!) returns 11,472 datasets, which is IMHO, not good.
On catalog-next.data.gov, same query, still get 60 datasets.  Awesome!  This is exactly what I would expect -- the stop word "of" has been elided.

But ...

For the query "department of education" ...
data.gov returns 76,689 datasets (wow!)
catalog-next.data.gov returns 1.260 datasets (might be ok)

For the query "the department of education" ...
data.gov returns 75,133 datasets (not surprising)
catalog-next.data.gov returns ... 0 datasets.  (OOPS)

Clearly there is still something not quite right here.

As an aside, I will note that the default sort order appears to be popularity.  I'm not sure this is what I would recommend ... I might suggest using "relevance" would be less surprising to users.

**Comment by woodt** [comment]
Created a ticket datagov-ckan-multi#397 to capture the odd search before for "the department of education"

**Comment by starsinmypockets** [comment]
Looks like this is working:

Sandbox:
* No datasets found for "if and of for the"
* 129 datasets found for "state alabama"
* 131 datasets found for "state of alabama"

Prod:
* 1,842 datasets found for "state alabama"
* 92,228 datasets found for "state of alabama" (assume this is including results for "of")

I do see some funny behavior though, possibly related to stopwords config @woodt :

Sandbox:
* 129 datasets found for "state alabama"
* 131 datasets found for "state of alabama"
* No datasets found for "the state of alabama"

... where I would expect to see roughly the same result set.

**Comment by woodt** [comment]
I believe the team has decided to move forward with this, given that https://github.com/GSA/datagov-ckan-multi/issues/397 captures the new problem.  Moving this back to QA (hopefully on its way to done.)
