### ISSUE TITLE
Validator Schema Missing from Datajson Harvest Sources

### ISSUE THREAD

**Issue by thejuliekramer** [GSA/datagov-ckan-multi#377]
Related to #355 

## How to reproduce

1. Visit a harvest source form of a datajson harvest source type in [sandbox](https://catalog-next.sandbox.datagov.us/harvest/edit/healthdata-gov)

## Expected behavior

Harvest source form should include a validator schema field

<img width="363" alt="validator schema" src="https://user-images.githubusercontent.com/7378770/89319413-aeaecc00-d645-11ea-918d-0e9c82bc9f7f.png">

## Actual behavior

Harvest source form does not include a validator schema field

<img width="1575" alt="datajson" src="https://user-images.githubusercontent.com/7378770/89319252-7909e300-d645-11ea-9432-77df104afff5.png">

**Comment by thejuliekramer** [comment]
@avdata99 This issue is caused by the VALIDATOR_SCHEMA coming back from ckanext-datajson as None because we removed it from ckanext-datajson when we split it into 2 files for 2.3 and 2.8 - I added it back here and now validator schema shows up in the form https://github.com/GSA/ckanext-datajson/pull/73

**Comment by thejuliekramer** [comment]
@avdata99 while I was looking around at possible causes I realized how to hide/show the fields we need based on source type - that is done here https://github.com/GSA/ckanext-geodatagov/pull/144

**Comment by starsinmypockets** [comment]
QA/d form. I don't have permissions to update harvest sources at staging / prod to compare.
