### ISSUE TITLE
Error Updating Harvest Source - SOLR Unable to add package to search index

### ISSUE THREAD

**Issue by thejuliekramer** [GSA/datagov-ckan-multi#381]
## How to reproduce

1. Running the import_harvest_sources.py import script on certain existing harvest sources - you can use  fairfax-county-virginia-data-json for example

`python import_harvest_sources.py --destination_api_key XXX  --destination_url https://catalog-next.sandbox.datagov.us/ --names fairfax-county-virginia-data-json`

## Expected behavior

Harvest source should update `Finished: 1 harvest sources. 0 Added, 1 already exists, 0 failed`

## Actual behavior

` Finished: 1 harvest sources. 0 Added, 0 already exists, 1 failed`

`ERROR status: 500
	 content:b'{"help": "https://catalog-next.sandbox.datagov.us/api/3/action/help_show?name=harvest_source_update", "success": false, "error": {"message": "Unable to add package to search index: Solr returned an error: (u\'Solr responded with an error (HTTP 400): [Reason: Exception writing document id ee1e550cded858edd025bef297aadef5147f1f1b to the index; possible analysis error: Document contains at least one immense term in field=\\"status\\" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: \\\\\'[123, 39, 106, 111, 98, 95, 99, 111, 117, 110, 116, 39, 58, 32, 50, 44, 32, 39, 116, 111, 116, 97, 108, 95, 100, 97, 116, 97, 115, 101]...\\\\\', original message: bytes can be at most 32766 in length; got 42034. Perhaps the document has an indexed string field (solr.StrField) which is too large]\',)", "__type": "Search Index Error"}}'
	 sent: {'name': 'fairfax-county-virginia-data-json', 'owner_org': 'fairfax-county-virginia', 'title': 'Fairfax County, Virginia Data.json', 'url': 'http://data.fairfaxcountygis.opendata.arcgis.com/data.json', 'notes': 'Fairfax County, Virginia Data.json', 'source_type': 'datajson', 'frequency': 'WEEKLY', 'config': '{"default_groups": "local", "validator_schema": "non-federal", "private_datasets": "False"}', 'extras': [], 'private_datasets': 'False', 'id': '2336b212-eb24-4d1c-bd83-6a7891897852'}`

**Comment by kimwdavidson** [comment]
@thejuliekramer to determine if this is still happening

**Comment by thejuliekramer** [comment]
<img width="1264" alt="Screen Shot 2020-10-05 at 2 25 15 PM" src="https://user-images.githubusercontent.com/7378770/95122773-9c6d0f00-0716-11eb-87d7-2fbe3ef24520.png">

I can confirm this is no longer an issue. Closing

**Comment by cmugisha** [comment]
From Julie: "I moved #381 and #441 to QA - both are working properly and can be moved to Done"
https://gsa-tts.slack.com/archives/CDCL978KZ/p1601926123125200
