### ISSUE TITLE
Use USWDS grid for form

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#384]
## User Story

As a data.gov team member, I want the form to be aligned with USWDS standards, so that I have consistency across properties and an efficient design implementation.

## Acceptance Criteria
- [ ] When I inspect the application
- [ ] I see the USWDS stylesheets and our custom stylesheets and do not see bootstrap

## Details / tasks

- [x] Find and install appropriate uswds npm module
- [x] Refactor metadata app to use npm module
- [x] Get grid layout to work without bootstrap
- [x] Make sure bootstrap is not being used anywhere in the project and remove any bootstrap library from the project's codebase if any
- [x] Remove  metadata-app/src/fonts and metadata-app/src/img
- [x] Replace the icons with icons from uswds

**Comment by starsinmypockets** [comment]
uswds grid in dcat metadata form is here: https://github.com/GSA/ckanext-dcat_usmetadata/pull/17

**Comment by adborden** [comment]
@kmanaseryan I'm not seeing uswds in the package.json.

**Comment by kmanaseryan** [comment]
@adborden uswds is being explicitly used in the css file check `./metadata-app/src/css/uswds.css`. It was already added before I started working on this issue.

**Comment by adborden** [comment]
@kmanaseryan as part of this story we should be using [uswds from npm](https://www.npmjs.com/package/uswds), it's listed under the tasks description. The CSS file in code is already outdated (2.7.0), the latest is 2.9.0. Using the npm package allows us to keep up to date and easily pick up security fixes. It's bad practice to include uswds in source code.

**Comment by kmanaseryan** [comment]
@adborden agree, sorry I've overlooked this task. Since it has been handled by @pwalsh earlier I just prioritized the existing code over the task list. I'll make the necessary changes. Next time I'll make sure there is no any unclear points before starting the task.

**Comment by adborden** [comment]
@kmanaseryan can we remove the other static assets from USWDS in [metadata-app/src/fonts](https://github.com/GSA/ckanext-dcat_usmetadata/tree/master/metadata-app/src/fonts) and [metadata-app/src/img](https://github.com/GSA/ckanext-dcat_usmetadata/tree/master/metadata-app/src/img)?
