### ISSUE TITLE
API integration

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#385]
## User Story

As a data publisher, when I am entering metadata into the form, I want want it to appear in the database, so that my information is saved somewhere

## Acceptance Criteria
- [x] When I am creating a dataset using the metadata form
- [x] And I click submit
- [x] Then I should be able to see my dataset on the datasets page

## Details / tasks
- Create API integration with CKAN API 
- Unit tests

**Comment by starsinmypockets** [comment]
To QA:

1. Login as admin
2. Create an Organization
3. Visit `/dataset/new-metadata?ownerOrg=ORG_ID_HERE`
4. Fill out the form
5. Press submit
6. Make sure that the dataset was added in CKAN

**Comment by kimwdavidson** [comment]
@starsinmypockets i tried to test this, but got errors on, it looks like, everything?

What should I do?

![Screen Shot 2020-08-28 at 9 49 21 AM](https://user-images.githubusercontent.com/22527532/91569276-c19a8080-e913-11ea-9205-5f30290b21ec.png)

**Comment by starsinmypockets** [comment]
This should work with admin access following the steps above.

**Comment by kimwdavidson** [comment]
@starsinmypockets @anuveyatsu: i created a test org, went to /dataset/new-metadata?ownerOrg=ORG_ID_HERE using "testing-org" as the org ID, and I think I filled everything out properly, but I'm getting an error when i try to submit:
 
![Screen Shot 2020-09-10 at 11 02 08 AM](https://user-images.githubusercontent.com/22527532/92750470-1519bf00-f355-11ea-9b20-1ba9909d5771.png)
