### ISSUE TITLE
BUG: ValueError: need more than 1 value to unpack  

### ISSUE THREAD

**Issue by starsinmypockets** [GSA/datagov-ckan-multi#390]
There appears to be a bug in CKAN (or maybe Flask) where if the word 'static' is part of the URL (for example http://localhost:5000/static/media/my-image.png) an error is thrown when parsing the path.

I logged the issue against CKAN here https://github.com/ckan/ckan/issues/5544

## Steps to Reproduce

1. Create ckan extension with public/static/ directory
2. Add resources to this directory
3. Try to load the resource via http://CKAN-PATH/static/yourresource.img

I believe that this can be addressed in one of two ways

1. Fixing the bug in CKAN / Flask
2. Reconfiguring webpack to use a different static resources path -- this will involve "ejecting" Create React App which has some negative consequences

**Comment by chris-macdermaid** [comment]
This is blocking https://github.com/GSA/datagov-deploy/issues/2186

**Comment by chris-macdermaid** [comment]
It looks like upstream is not going to fix this for CKAN 2.8. We'll need to resolve this before moving to inventory-next. I'm happy to team up or discuss what a solution to this might be.

**Comment by chris-macdermaid** [comment]
@woodt If there is any work that you've done on this let me know otherwise I'll take on this ticket.

**Comment by chris-macdermaid** [comment]
Moved public/static to public/assets.  Tagged version 0.2.8. Now icons and fonts are available.
![Screenshot from 2020-12-08 10-03-17](https://user-images.githubusercontent.com/64213093/101516773-1f8c2a80-393d-11eb-93f3-a6e15b691c85.png)

**Comment by chris-macdermaid** [comment]
Tested that this change is working in version 0.2.11 on sandbox and staging. The version # for inventory-next will be updated with this [PR](https://github.com/GSA/inventory-app/pull/188)

Version 0.2.4
![Screenshot from 2020-12-28 15-46-31](https://user-images.githubusercontent.com/64213093/103299572-15000680-49ba-11eb-9c10-e6b65bc66147.png)

version 0.2.11
![Screenshot from 2020-12-29 09-55-03](https://user-images.githubusercontent.com/64213093/103300388-ff8bdc00-49bb-11eb-9e55-cafd02233139.png)

![Screenshot from 2020-12-28 17-19-31](https://user-images.githubusercontent.com/64213093/103300419-0dd9f800-49bc-11eb-8e8d-830446811eee.png)

**Comment by adborden** [comment]
Demo'd last sprint.
