### ISSUE TITLE
BUG: Missing `link is ok` affirmation in the Downloads & Resources section

### ISSUE THREAD

**Issue by estebanruseler** [GSA/datagov-ckan-multi#391]
### Description

Linked to: [UG: Missing `link is ok` affirmation in the Resource metadata page](https://github.com/GSA/ckanext-datagovcatalog/issues/12)

On the dataset metadata page, the Downloads and Resources section is missing the `link is ok` affirmation

**Environment:** [sandbox catalog](https://catalog-next.sandbox.datagov.us/dataset)
**Screenshot**
![](https://i.imgur.com/bGWKXCa.png)
![](https://i.imgur.com/1dNLiwZ.png)

### How to reproduce
1. Visit the [Data page](https://catalog-next.sandbox.datagov.us/dataset) of the sandbox catalog
2. visit this dataset - [Mine Inspections](https://catalog-next.sandbox.datagov.us/dataset/mine-inspections); the metadata page for the dataset gets loaded
3. Scroll to the `Downloads & Resources` section
4. observe that the `link is ok` affirmation message is missing

### Expected behavior
- the dataset metadata page has a `link is ok` affirmation message in the Downloads & Resources section
- The expected behavior can be [observed here](https://catalog.data.gov/dataset/mine-inspections)

**Comment by avdata99** [comment]
Also related to [Catalog#50](https://github.com/GSA/catalog.data.gov/issues/50)

**Comment by avdata99** [comment]
Before QA is required to run `archiver` and `qa` workers in the environment

**Comment by avdata99** [comment]
Moved to blocked since we are not able to QA them until we finish [Multi#417](https://github.com/GSA/datagov-ckan-multi/issues/417) and  [Deploy#2123](https://github.com/GSA/datagov-deploy/issues/2123)

**Comment by thejuliekramer** [comment]
You can verify this on [staging](https://admin-catalog-next-datagov.dev-ocsit.bsp.gsa.gov/dataset/mine-inspections)
