### ISSUE TITLE
Waf & Waf-collection Harvester Dataset Count Not Updating

### ISSUE THREAD

**Issue by thejuliekramer** [GSA/datagov-ckan-multi#392]
https://catalog-next.sandbox.datagov.us/harvest/admin/2014-necta-500k

## How to reproduce

1. Login as Admin
2. Open https://catalog-next.sandbox.datagov.us/harvest/admin/2014anrc
3. Click "Reharvest" button
4. Wait for harvest to finish (less than a minute)
5. Refresh the page and confirm the job is complete
6. Open the full job report https://catalog-next.sandbox.datagov.us/harvest/admin/2014anrc/job/last

## Expected behavior

2 dataset added and 1 fails, dataset count should be updated to 2

https://admin-catalog.data.gov/harvest/2014anrc

## Actual behavior

2 dataset added and 1 fails, dataset count is still 0
<img width="763" alt="2014anrc" src="https://user-images.githubusercontent.com/7378770/90271613-b595c580-de21-11ea-94b8-9db763d60af7.png">

**Comment by thejuliekramer** [comment]
Related to https://github.com/GSA/datagov-ckan-multi/issues/356

**Comment by avdata99** [comment]
The GSA fork on harvest [calculates this number differently](https://github.com/GSA/ckanext-harvest/blob/8b1c9b48df6ef6f4223d5f18a71638a35c539614/ckanext/harvest/logic/action/get.py#L111-L119).

``` python
packages = model.Session.query(model.Package) \
            .join(harvest_model.HarvestObject) \
            .filter(harvest_model.HarvestObject.harvest_source_id==source.id) \
            .filter(harvest_model.HarvestObject.current==True) \
            .filter(model.Package.state==u'active') \
            .filter(model.Package.private==False) \
            .group_by(model.Package.id) \
            .order_by(None)
    out['total_datasets'] = packages.count()
```

Upstream calculates in [a new way](https://github.com/GSA/ckanext-harvest/blob/55bd3fc2829319847f42a2376f80d8abc1cd6a53/ckanext/harvest/helpers.py#L85-L94)

``` python
def package_count_for_source(source_id):
    '''
    Returns the current package count for datasets associated with the given
    source id
    '''
    fq = '+harvest_source_id:"{0}"'.format(source_id)
    search_dict = {'fq': fq}
    context = {'model': model, 'session': model.Session}
    result = logic.get_action('package_search')(context, search_dict)
    return result.get('count', 0)
```

**Comment by avdata99** [comment]
The harvest source has no extras, so we don't have the `harvest_source_id` we need

![image](https://user-images.githubusercontent.com/3237309/90428731-cf8e0d00-e09a-11ea-8af8-6b1629779e6a.png)

**Comment by thejuliekramer** [comment]
@avdata99 The problem is that the datasets are not counted if the dataset is private because the API for  package_search does not return private datasets, so this helper function in ckanext-harvest will not return it. When the dataset is marked as public it is counted, as you can see below

<img width="1018" alt="Screen Shot 2020-08-17 at 8 24 30 PM" src="https://user-images.githubusercontent.com/7378770/90459917-54435000-e0c8-11ea-8e5d-f23941bf4938.png">

I am not sure why the datasets are being marked as private... we can look into it tomorrow morning

**Comment by avdata99** [comment]
QA run [at 2017-division-500 source](https://catalog-next.sandbox.datagov.us/harvest/admin/f4ae1def-c6bc-48ac-b816-f6677dab6821):

![image](https://user-images.githubusercontent.com/3237309/90791133-3a2f8a80-e2df-11ea-8405-1e9a84745418.png)

It's working
