### ISSUE TITLE
Save and add another

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#395]
## User Story

As a data publisher, when I add a resource, I want to be able to save an add another resource, so that I can add multiple resources

## Acceptance Criteria
- [x] WHEN I got to https://inventory.sandbox.datagov.us/dataset/new-metadata
- [x] and I fill out all the required metadata
- [x] and I click save and continue
- [x] and I arrive at the additional metadata page and click on save and continue
- [x] and I upload a resource file
- [x] THEN I should see a button to "Save and add another resource"
- [x] AND I should be able to repeat the upload process

**Comment by starsinmypockets** [comment]
Looks good:
![Screenshot from 2020-09-21 11-56-52](https://user-images.githubusercontent.com/949175/93790988-a57fbb80-fc01-11ea-9684-fff583ff524d.png)
