### ISSUE TITLE
Non Federal Datajson Sources Harvested at Federal

### ISSUE THREAD

**Issue by thejuliekramer** [GSA/datagov-ckan-multi#399]
Related to #356 

## How to reproduce

1. Visit https://catalog-next.sandbox.datagov.us/harvest/admin/ny-state-json

2. Observe that no datasets are added, and errors related to harvest source being harvested as federal instead of non federal are present.

## Expected behavior

Datasets should be added, and only data related to the datasets are present.
![image](https://user-images.githubusercontent.com/7378770/90796153-9214c400-e2d4-11ea-9f85-9ae50b80504c.png)

## Actual behavior

No datasets are added, and errors related to harvest source being harvested as federal instead of non federal are present.

<img width="1368" alt="Screen Shot 2020-08-20 at 11 00 13 AM" src="https://user-images.githubusercontent.com/7378770/90796030-65f94300-e2d4-11ea-8b52-17c5dd694469.png">

**Comment by hkdctol** [comment]
Related: https://github.com/GSA/datagov-deploy/issues/1135

**Comment by hkdctol** [comment]
I have seen that non-federal data.json harvest sources are working and moving this to done.
