### ISSUE TITLE
catalog-next minimum viable product launch

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#400]
## Feature/what we're after
From the [Catalog App One Pager](https://docs.google.com/document/d/1oiYWopA7-qPh_E3WYmQPWlq3xyBSkW9gnwhnzcgVIbM/edit#heading=h.khqx87vg13aw):

> stand up a new catalog application based on a recent CKAN (2.8+) within 60 days and without taking on the technical debt from the existing application and enabling us to iterate faster than is possible today.

## Anticipated/hypothesized benefits
- Build a modern foundation for catalog development
- Leave legacy, under-tested, under-documented "features" behind

## Measurements/metrics
- Increase in the number of issues that can be debugged locally instead of in sandbox or staging
- Development experience is more delightful
- Increase in test coverage

## References/background
- [Catalog App One Pager](https://docs.google.com/document/d/1oiYWopA7-qPh_E3WYmQPWlq3xyBSkW9gnwhnzcgVIbM/edit#heading=h.khqx87vg13aw)
- [CKAN 2.8 documentation](https://docs.ckan.org/en/2.8/)

## Launch plan

In order to reduce risk and keep the catalog-next launch as simple and foolproof as possible, a data.gov operator wants a detailed launch plan.

The launch plan captures the manual steps that need to happen to launch catalog-next, preferably in checklist form. The launch plan should also address any considerations for potential rollback.

### Overview

The actual launch should be a configuration change directing web traffic from the catalog-classic instances to the new catalog-next instances. We will do the majority of work ahead of launch time.

### Pre-launch

In the days leading up to the launch, these tasks should be completed:

- [x] This plan (and rollback) has been simulated in the staging environment
- [x] Any hotfix branches are merged and deployed to staging and production
- [x] Blog post is approved through TTS/GSA (~7 day lead time)
- [x] Blog post is published on www.data.gov
- [x] Post launch PR is up-to-date and ready to be merged with all checks passing https://github.com/GSA/datagov-deploy/pull/2506
- [x] Check in with @chris-macdermaid on the [sprint release](https://github.com/GSA/datagov-deploy/issues/2712)

### Launch

Tasks to be completed at the time of launch.

- [x] Merge (and deploy) launch PR https://github.com/GSA/datagov-deploy/pull/2507
- [x] Disable catalog-classic origin and enable catalog-next origin in CloudFront CDN (In the Behavior tab of the distribution change the Origin to catalog-next)
- [x] Invalidate the CloudFront cache (In the Invalidations tab of the distribution create a new invalidation to invalidate all (*))

In the event a rollback is necessary, apply these tasks.

- [ ] Disable catalog-next origin and enable catalog-classic origin in CloudFront CDN (In the Behavior tab of the distribution change the Origin to old catalog)
- [ ] Invalidate the CloudFront cache (In the Invalidations tab of the distribution create a new invalidation to invalidate all (*))

### Post launch

Once the launch is stable and successful, these tasks should be performed.

- [x] Merge post launch PR https://github.com/GSA/datagov-deploy/pull/2506
- [x] Trigger a reindex in search engines where possible (e.g. Google, Bing, etc)
- [-] ~Submit ticket to BSP to update DNS names (admin-catalog-next -> admin-catalog) and update login.gov application~
- [x] Write stories to clean up catalog-classic resources
- [x] String replace catalog-next.data.gov in datagov-deploy, ensure admin-next is linking to catalog.data.gov

**Comment by avdata99** [comment]
To be considered
 - [ ] Define how much load the system receives in the current production environment
 - [ ] Define a set of tools to test the load (maybe [ab](https://httpd.apache.org/docs/2.0/programs/ab.html))
 - [ ] If possible, get a list of indexed URLs in Google, Bing (and other if needed)
   - [ ] Analyze this URL with the new environment and propose fixes or create a list of 301 redirections

**Comment by adborden** [comment]
@avdata99 thanks, I've captured this in a new issue https://github.com/GSA/datagov-ckan-multi/issues/449

**Comment by adborden** [comment]
@hkdctol you can access the existing catalog from https://admin-catalog.data.gov/user/login


We'll delay updating the DNS names for admin-catalog since we want to keep a way to access the old catalog around for a bit.
