### ISSUE TITLE
Queries in Catalog Next Too Long

### ISSUE THREAD

**Issue by thejuliekramer** [GSA/datagov-ckan-multi#403]
As a user I should be able to load a harvest source page quickly and with out timeouts so that I can see information about the harvest source. 

## How to reproduce

1. Visit https://catalog-next.sandbox.datagov.us/harvest/environmental-dataset-gateway-non-spatial-records
2. Note the page load time.

## Expected behavior

1. Page should load in under a second

## Actual behavior

1. Page takes 10 seconds to load

## Tasks

1. Identify queries taking too long
2. Reduce time of queries

**Comment by adborden** [comment]
In some cases, we see 502 when loading harvest pages. If the request takes longer than 30 seconds, we see gunicorn kill the request.
<img width="966" alt="Screen Shot 2020-08-31 at 2 57 53 PM" src="https://user-images.githubusercontent.com/509703/91772934-abeabc80-eb9a-11ea-8de1-c179befef697.png">

![Screen Shot 2020-08-31 at 3 56 14 PM](https://user-images.githubusercontent.com/509703/91772990-c15fe680-eb9a-11ea-8085-93724b328463.png)

**Comment by cmugisha** [comment]
Moved this to Current Sprint because it is linked to the error that is keeping Hyon and Aaron from doing QAs. Deprioritizing the moving to staging ticket as Hyon suggested.

**Comment by avdata99** [comment]
This query is taking more than 15 seconds

```
SELECT 
    harvest_object_extra.id AS harvest_object_extra_id,
    harvest_object_extra.harvest_object_id AS harvest_object_extra_harvest_object_id, 
    harvest_object_extra.key AS harvest_object_extra_key, 
    harvest_object_extra.value AS harvest_object_extra_value
FROM    
    harvest_object_extra 
WHERE 
    '59e34a0b-d51f-4206-b8a2-c92f8cf073ef' = harvest_object_extra.harvest_object_id
```
Adding more indexes now

**Comment by avdata99** [comment]
Create [a document](https://hackmd.io/jYvieE0zQRqOBSAClWj77g) and a [PR for slow queries](https://github.com/ckan/ckanext-harvest/pull/414/files) in ckanext-harvest to start a discussion about this with CKAN tech team

**Comment by avdata99** [comment]
Blocked while we wait for upstream to approve the [PR we sent](https://github.com/ckan/ckanext-harvest/pull/414)
