### ISSUE TITLE
Develop drop-down fields for Additional Metadata page

### ISSUE THREAD

**Issue by starsinmypockets** [GSA/datagov-ckan-multi#406]
## User story
As a data publisher, I want to be able to choose metadata options from a dropdown list, so that I can prevent redundant entries and so I can more efficiently add metadata

## Description
Some of the fields described [here](https://docs.google.com/spreadsheets/d/1bWt_uLloRQ5Rd8HI22COUlIwH_REsywHJ43NmkQNSv0/edit#gid=746832760) require API integrations. Evaluate and implement. Create additional tickets as needed.

## Required dropdowns:
- [x] Data dictionary type: use the usmetadata extension as a guide to create a static dropdown. add "other" as an option
- [x] Accrual Periodicity: pull static list from usmetadata ext. implementation
- [x] Language / Language subtag: IANA list of language tags https://docs.microsoft.com/en-us/previous-versions/commerce-server/ee825488(v=cs.20)?redirectedfrom=MSDN  (default value for Language/Language subtag should be **en-US**)

**Comment by starsinmypockets** [comment]
For "theme" field we can use the existing tags field implementation -- ie, autocomplete with tags saved by CKAN

**Comment by starsinmypockets** [comment]
"Data Dictionary Type" is populated by usmetadata extension. Check implementation there.

**Comment by starsinmypockets** [comment]
"Accrual Periodicity" - pull static list from usmetadata ext. implementation

**Comment by starsinmypockets** [comment]
Language / Language subtag - simple to add a static dropdown but need the list/s of static values to use.

**Comment by starsinmypockets** [comment]
Parent Dataset -- should use any published parent dataset in catalog

**Comment by kimwdavidson** [comment]
Decisions: 
Theme field: free text for now
Data dictionary type: use the usmetadata extension as a guide to create a static dropdown. add "other" as an option
Accrual Periodicity: pull static list from usmetadata ext. implementation
Language / Language subtag: need static list: 
Parent Dataset: should use any published parent dataset in current catalog or "other"

**Comment by starsinmypockets** [comment]
Accrual Periodicity dropdown is implmented as part of  https://github.com/GSA/ckanext-dcat_usmetadata/pull/38

![Screenshot from 2020-09-16 23-11-32](https://user-images.githubusercontent.com/949175/93415666-09a52700-f872-11ea-9e14-680e06779a19.png)

**Comment by cmugisha** [comment]
@starsinmypockets This ticket was estimated at half a day. Any updates?

**Comment by starsinmypockets** [comment]
Language field should default to EN-US

**Comment by starsinmypockets** [comment]
@kmanaseryan I will implement "Parent Dataset" field

**Comment by starsinmypockets** [comment]
FYI @kmanaseryan  the implemention on the CKAN side of `isParent` is here https://github.com/GSA/USMetadata/blob/master/ckanext/usmetadata/plugin.py#L303

**Comment by starsinmypockets** [comment]
So there is a utility function in USMetadata to run the appropriate query to get the appropriate parent datasets for the authenticated user -- I think we need to map this to an api endpoint for the client-side implementation in the metadata form
https://github.com/GSA/USMetadata/blob/master/ckanext/usmetadata/db_utils.py#L16
(not sure why it is called `get_parent_organization` here, when it is getting parent datasets)
