### ISSUE TITLE
[catalog-next]  Assess risk of SNYK-PYTHON-WEBOB-40490

### ISSUE THREAD

**Issue by woodt** [GSA/datagov-ckan-multi#408]
No remediation path available for CKAN2.8 (not compatible with webob > 1.0.8).  Need to determine the risk of not upgrading.

## Acceptance Criteria
- Determine whether to remediate or accept risk
- Create new ticket for remediation if required

**Comment by thejuliekramer** [comment]
Duplicate of https://github.com/GSA/catalog.data.gov/pull/169
