### ISSUE TITLE
[catalog-next]  Assess risk of SNYK-PYTHON-IPADDRESS-590065

### ISSUE THREAD

**Issue by woodt** [GSA/datagov-ckan-multi#409]
No remediation available yet.  To properly evaluate the risk we should examine the Python cryptography package and assess whether and how it uses the hash() method of the classes IPv4Interface and IPv6Interface.

**Comment by woodt** [comment]
I've inspected the Python cryptography package (version 2.7, which is what we are using for catalog-next) and it does not appear that any of the vulnerable hash() methods are being called.

**Comment by cmugisha** [comment]
@woodt I see that this is a new ticket? Can you put an estimate on it and assign yourself? Thanks!

**Comment by woodt** [comment]
SNYK config change in https://github.com/GSA/catalog.data.gov/pull/117
