### ISSUE TITLE
Prepare recommendations deck

### ISSUE THREAD

**Issue by gujacq** [GSA/datagov-ckan-multi#412]
## User Story
As a member of the data.gov team, I want to understand CA UX's recommendations on what we've learned in the user interviews, so that I understand possibilities for next steps and can make an informed decision.

## Acceptance Criteria
- [ ] Produce a deck that outlines our recommendations

## Details / tasks
- [ ] Meet with Data.gov team to talk about their thoughts on interview findings
- [ ] Decide on what we want to highlight
- [ ] Put together outline for deck
- [ ] Create deck
- [ ] Make sure there's an appendix raw notes and resources
- [ ] Clean up our notes and resources (example: Mural board)

**Comment by cmugisha** [comment]
The deck was presented during Design Review today.
