### ISSUE TITLE
Test search

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#413]
Top searches:
- covid
- health
- crime
- education
- sba

QA Steps:
- Go to catalog-next.sandbox.datagov.us
- enter one of the above search terms
- go to catalog.data.gov
- enter the same search term
- review the results on both sites to ensure they match
- log any issues to the comments of this ticket
- repeat for each search term

List of top searches: https://docs.google.com/spreadsheets/d/137BxatsUW-OIr9LwKFOGQoVxQOCAgtw2EIzgEVQf1C0/edit#gid=230690925

**Comment by cmugisha** [comment]
- When I search "covid", Catalog-next gives me 140 datasets, but data.gov gives me 212 datasets.
- When I search "health", Catalog-next gives me 6406 datasets, but data.gov gives me 9309 datasets.
- When I search "crime", Catalog-next gives me 401 datasets, but data.gov gives me 622 datasets.
- When I search "education", Catalog-next gives me 2261 datasets, but data.gov gives me 6250 datasets.
- When I search "sba", Catalog-next gives me 143 datasets, but data.gov gives me 161 datasets.

@kimwdavidson Am I supposed to go through all these datasets and see which ones are missing on Catalog-next? That is thousands of search results! At the same time, what I just found doesn't seem helpful if the missing datasets aren't listed as well... Please advise...

**Comment by hkdctol** [comment]
covid - 191 sandbox 218 catalog
health 6591 sandbox 9359 catalog
crime 431 sandbox 625 catalog
education 2817 sandbox 6224 catalog
sba 143 sandbox 161 catalog

review of results on both, sort by relevance, mostly match
on smaller search results (covid, sba), it's possible to match the results per harvest source, the numbers are fairly close, and differences can be explained by the differences between sandbox and catalog (current catalog has datasets from non-current harvest sources, sandbox has not harvested all existing harvest sources, etc.)
Generally the review indicates search is working as expected.
