### ISSUE TITLE
QA waf-collection harvester

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#415]
### Harvest Sources 

1. [usgs-national-transportation-dataset-ntd-downloadable-data-collection](https://admin-catalog-next-datagov.dev-ocsit.bsp.gsa.gov/harvest/usgs-national-transportation-dataset-ntd-downloadable-data-collection)
2. [2014anrc](https://admin-catalog-next-datagov.dev-ocsit.bsp.gsa.gov/harvest/2014anrc)
3. [fema-r04](https://admin-catalog-next-datagov.dev-ocsit.bsp.gsa.gov/harvest/fema-r04)
4. [2010-census-urban-area-for-united-states-1-500-000](https://admin-catalog-next-datagov.dev-ocsit.bsp.gsa.gov/harvest/2010-census-urban-area-for-united-states-1-500-000)
5. [2019cb-cbsa](https://admin-catalog-next-datagov.dev-ocsit.bsp.gsa.gov/harvest/2019cb-cbsa)

Or you can choose any from this [spreadsheet](https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit#gid=1416535904)

- Go to https://admin-catalog-next-datagov.dev-ocsit.bsp.gsa.gov/harvest/
- Log in (Request login info from Julie or Kim if you don't have it)
- Select "waf-collection" under "type" on the left
- Search for a source name
- Click on that source

- Go to catalog.data.gov/harvest
- Select "waf-collection" under "type" on the left
- Search for a source name
- Click on that source

- Both sources should have the same datasets
- Click into one dataset from that source on each instance
- The datasets should have the same information

- Repeat for each source
- Log any issues to this ticket

**Comment by thejuliekramer** [comment]
Some functionality here is blocked by https://github.com/GSA/datagov-ckan-multi/issues/426. You can go to any waf-collection harvest source directly by appending the harvest source name from the [spreadsheet](https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit#gid=1416535904) to the url https://admin-catalog-next-datagov.dev-ocsit.bsp.gsa.gov/harvest/**harvest_source_name**

**Comment by kimwdavidson** [comment]
usgs-national-transportation-dataset-ntd-downloadable-data-collection: 1 dataset on new catalog, 117 on current catalog
2014anrc: 1 dataset on new catalog, 1 dataset on existing catalog, they match
fema-r04: 3,036 on new catalog, 3,043 on existing catalog, spot check metadata matches
2010-census-urban-area-for-united-states-1-500-000: current catalog says there are 2 datasets, shows 1 collection; new catalog shows 1 dataset, the dataset that shows matches
2019cb-cbsa: 1 dataset on new catalog, 1 dataset on current catalog. clicked into [current dataset](https://catalog.data.gov/dataset/series-information-for-the-2019-cartographic-boundary-file-kml-current-metropolitan-micropolita) and [new dataset](https://catalog.data.gov/dataset/series-information-for-the-2019-cartographic-boundary-file-kml-current-metropolitan-micropolita). new dataset seems to have a more robust description

**Comment by adborden** [comment]
I think we're seeing a bug in the dataset count on the harvest source page which is causing confusion. I opened https://github.com/GSA/datagov-ckan-multi/issues/437 to track. This issue looks good to me, @kimwdavidson let me know if you agree.

On the collections pages, I'm seeing matching or similar counts for these.

> usgs-national-transportation-dataset-ntd-downloadable-data-collection: 1 dataset on new catalog, 117 on current catalog

This one looks okay. I'm seeing identical counts (112) on both [classic](https://catalog.data.gov/dataset?collection_package_id=d4f92d86-e9c0-4e45-a585-609722f2f398) and [catalog-next](https://admin-catalog-next-datagov.dev-ocsit.bsp.gsa.gov/dataset?collection_package_id=52805bec-710a-47b9-914f-7ccb4892a0d4), both harvested today Sept 23.

> 2010-census-urban-area-for-united-states-1-500-000: current catalog says there are 2 datasets, shows 1 collection; new catalog shows 1 dataset, the dataset that shows matches

On the collections page, I'm seeing a count of 1 for both [catalog-classic](https://catalog.data.gov/dataset?collection_package_id=f3d38bee-952f-4988-99e3-c4bb7510e49b) and [catalog-next](https://admin-catalog-next-datagov.dev-ocsit.bsp.gsa.gov/dataset?collection_package_id=ac2fb712-4cee-474c-8851-b559c1600b8d).



> 2019cb-cbsa: 1 dataset on new catalog, 1 dataset on current catalog. clicked into [current dataset](https://catalog.data.gov/dataset/series-information-for-the-2019-cartographic-boundary-file-kml-current-metropolitan-micropolita) and [new dataset](https://catalog.data.gov/dataset/series-information-for-the-2019-cartographic-boundary-file-kml-current-metropolitan-micropolita). new dataset seems to have a more robust description

Seeing 3 datasets in both collections.
