### ISSUE TITLE
QA data.json harvester

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#416]
### Harvest Source Names
1. [fhfa-json](https://admin-catalog-next-datagov.dev-ocsit.bsp.gsa.gov/harvest/fhfa-json)
2. [neh-data-json](https://admin-catalog-next-datagov.dev-ocsit.bsp.gsa.gov/harvest/neh-data-json)
3. [wa-json](https://admin-catalog-next-datagov.dev-ocsit.bsp.gsa.gov/harvest/wa-json)
4. [city-of-austin-data-json](https://admin-catalog-next-datagov.dev-ocsit.bsp.gsa.gov/harvest/city-of-austin-data-json)
5. [los-angeles-data-json](https://admin-catalog-next-datagov.dev-ocsit.bsp.gsa.gov/harvest/los-angeles-data-json)

- Go to https://admin-catalog-next-datagov.dev-ocsit.bsp.gsa.gov/harvest/
- Log in (Request login info from Julie or Kim if you don't have it)
- Select "data.json" under "type" on the left
- Search for a source name
- Click on that source

- Go to catalog.data.gov/harvest
- Select "data.json" under "type" on the left
- Search for a source name
- Click on that source

- Both sources should have the same datasets
- Click into one dataset from that source on each instance
- The datasets should have the same information

- Repeat for each source
- Log any issues to this ticket

**Comment by kimwdavidson** [comment]
- [ ] fhfa-json: 2 datasets in each catalog. 
- [ ] neh-data-json: 754 on new catalog, 659 on legacy. 
- [ ] wa-json: 96 on new catalog, 97 on legacy. Clicked into WA JSON, 1151 Datasets on new catalog, 1835 on legacy
- [ ] city-of-austin-data-json: 789 on new catalog, 928 on legacy. Clicked on City of Austin Data.json, 1113 datasets on new catalog, 1832 on legacy
los-angeles-data-json: 754 on new catalog, 659 on legacy.

**Comment by thejuliekramer** [comment]
Adding here that dod-json is not harvesting correctly in staging - but is working locally and in sandbox CC: @avdata99

**Comment by avdata99** [comment]
@thejuliekramer I test this code locally (like an [emulation of what datajson does](https://github.com/GSA/ckanext-datajson/blob/master/ckanext/datajson/harvester_datajson.py#L26-L41))

```python
import urllib2, json
req = urllib2.Request('https://www.defense.gov/data.json')
response = urllib2.urlopen(req)

errors = []
datasets = []

try:
    data = json.load(response)
    datasets = data['dataset']
except Exception as e:
    errors.append('Error parsing: {}'.format(e))

try:
    response = urllib2.urlopen(req)
    data = json.load(response, 'cp1252')
    datasets = data['dataset']
except Exception as e:
    errors.append('Error for cp1252: {}'.format(e))

try:
    response = urllib2.urlopen(req)
    data = json.load(response, 'iso-8859-1')
    datasets = data['dataset']
except Exception as e:
    errors.append('Error for iso-8859-1: {}'.format(e))
    
print('{} datasets found'.format(len(datasets)))
print('Errors: {}'.format(json.dumps(errors, indent=4)))
```

Without adding new response objects

```0 datasets found
Errors: [
    "Error parsing: 'utf8' codec can't decode byte 0x92 in position 214: invalid start byte", 
    "Error for cp1252: No JSON object could be decoded", 
    "Error for iso-8859-1: No JSON object could be decoded"
]
```

Adding new response objects per each parse process

```
177 datasets found
Errors: [
    "Error parsing: 'utf8' codec can't decode byte 0x92 in position 214: invalid start byte"
]
```

**I add new requests and works. I leave as it is and fails**

If you can try in staging to add this extra requests maybe it will be fixed

**Comment by avdata99** [comment]
@thejuliekramer it seems the response object should be readed just one time

I created this PR which (I think) will fix this issue
https://github.com/GSA/ckanext-datajson/pull/79

**Comment by avdata99** [comment]
The PR is merged, so you can check test this in staging @thejuliekramer

**Comment by thejuliekramer** [comment]
To QA - 

Verify there are datasets harvested from https://admin-catalog-next-datagov.dev-ocsit.bsp.gsa.gov/harvest/dod-json

**Comment by adborden** [comment]
Looks good to me.
