### ISSUE TITLE
Configure a test team on the login.gov identity sandbox

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#418]
## Acceptance Criteria

[ ] Give I am set up to use the login.gov identity sandbox (see https://developers.login.gov/testing/ and visit https://dashboard.int.identitysandbox.gov/)

[ ] Then I can view the team https://dashboard.int.identitysandbox.gov/teams/263  and confirm that Aaron and Julie are added as initial members.

It may turn out that because of permission issues, I (thomas.wood@ed.gov) may be the only person who can view that team...if that is the case, I guess I will QA the ticket. :-(

**Comment by woodt** [comment]
Team 'catalog-next-sandbox' created in the login.gov identity sandbox.

https://dashboard.int.identitysandbox.gov/teams/263

I've added Aaron, Julie, and myself to get started.

**Comment by woodt** [comment]
I'm not sure that the acceptance criteria for this story is actually going to work ... I think maybe saying that Aaron is a member of the team is more appropriate.

**Comment by adborden** [comment]
I was able to log into the login.gov dashboard, view the team, and even add a @mogul and @hkdctol to the sandbox application.
