### ISSUE TITLE
Bug when parsing a dataset name

### ISSUE THREAD

**Issue by anuveyatsu** [GSA/datagov-ckan-multi#419]
If I try to create a dataset with name that contains a dash (`-`), it is removed from the name. For example:

`my-dataset-name` is converted to `mydatasetname` which is I believe unexpected. 

## How to reproduce

1. Go to "required metadata" stage of the react app.
2. Create a dataset and make sure you have a dash in the title. E.g., `my-dataset`.
3. Check the auto generated URL underneath of the title which should display: `http://localhost:3000/dataset/my-dataset`
4. Fill in other fields and save.
5. Check the created dataset and you'd see that `my-dataset` was changed to `mydataset`

## Expected behavior

It should not remove dashes.

## Actual behavior

It removes dashes in a function called `safeName`.

Screenshot of suggested URL with the expected and correct dataset name:

![Screen Shot 2020-09-02 at 16.57.30.png](https://images.zenhubusercontent.com/583c185ab9dc3c622022968d/469cb017-fc6a-4e21-9ebf-73a502c4415a)

However, after the dataset is created, the dash is removed.

**Comment by starsinmypockets** [comment]
This works now:
![Screenshot from 2020-09-21 11-54-10](https://user-images.githubusercontent.com/949175/93790633-428e2480-fc01-11ea-96c3-e84a19ca2ebd.png)
