### ISSUE TITLE
Access to the new metadata form

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#424]
## Acceptance Criteria
- When I go to the staging site
- And I log in
- And I click on "Add dataset"
- Then I am taken to the new metadata form
- the URL to the new form should be `/dataset/new-metadata`.

## Implementation Notes
- redirect "Add dataset" link to new form
- the link to the new form should be `/dataset/new-metadata`.
- the old/original URL should be preserved and should still load the old form

**Comment by cmugisha** [comment]
@kimwdavidson Who should this be assigned to?

**Comment by anuveyatsu** [comment]
Hi @adborden I have a question about organization field in the metadata form. As you might know, it is the required field when creating a dataset (assuming you don't allow datasets without organization in your CKAN instance). If users would access the new metadata form from the `/dataset/` page, we wouldn't know what organization a dataset should belong to, especially, if a user has edit rights for multiple organizations.

Options:

1) Just use the first organization implicitly that user has access to.
2) Create a new field which should be a dropdown (just check how it works in CKAN).

Let me know WDYT please.

cc @starsinmypockets

**Comment by adborden** [comment]
@anuveyatsu I chatted with @osahon-okungbowa and the team about this. We should re-implement the existing behavior on Inventory where the user selects the organization from a drop-down which is populated based on the users' membership, I guess that's option 2.
