### ISSUE TITLE
[BUG] API Response for package_create returns 400 error

### ISSUE THREAD

**Issue by starsinmypockets** [GSA/datagov-ckan-multi#425]
# Context / Description

The embedded metadata app uses the CKAN api to create and update packages. When the required metadata form is complete the app calls the APIs  _package_create_ method via `POST` request. This should create a new package with the required metadata. CKAN returns a `400` error and the message: `"Bad request - JSON Error: Invalid request. Please use POST method for your request"`. (Note that this was in fact a `POST` request).

# Steps to reproduce

* Authenticate with the sandbox app
* Visit https://inventory.sandbox.datagov.us/dataset/new-metadata?group=123
* Open inspector in the browser to capture subsequent network requests
* Complete the required metadata form
* Submit the form
* Inspect the network request / response for the 400 error

**Comment by starsinmypockets** [comment]
cc @avdata99 @woodt @jbrown-xentity

**Comment by starsinmypockets** [comment]
CURL request to the same endpoint works

`curl -X POST https://inventory.sandbox.datagov.us/api/3/action/package_create -d '{"name": "lala"}' -H "Authorization: foo-bar-123"`

Using a REST client (Postman and Insomnia were tested) the same endpoint fails with the afformentioned 400

**Comment by jbrown-xentity** [comment]
Strange @starsinmypockets. We do test adding users, organizations, and data as part of the [inventory-app docker setup](https://github.com/GSA/inventory-app/blob/master/seed.sh#L41-L137), and that all works fine. Not sure why curl would work and postman would not...

**Comment by osahon-okungbowa** [comment]
here's a screenshot of the failed Postman request. Request mimics exactly what the form does and gets the same failed response
![2020-09-11 (1)](https://user-images.githubusercontent.com/60897650/92955476-1a623100-f45d-11ea-8646-15a8f970b796.png)

**Comment by jbrown-xentity** [comment]
I was able to get the expected 403 response in Postman. Here is what I did, but I had to use the form-data version of the body. Something strange is being automatically inserted in the headers on postman when you use the raw option...
https://www.getpostman.com/collections/0a67ed0dfc15f0eb4561
![image](https://user-images.githubusercontent.com/26980513/92956804-ba4f9880-f424-11ea-940c-219fd5dfef65.png)

**Comment by starsinmypockets** [comment]
Looks like we see this error when the `content-type: application/json` header is present.

Any ideas on this @woodt ?

**Comment by avdata99** [comment]
Working fine from CURL

![Screenshot-20200911105447-1854x903](https://user-images.githubusercontent.com/3237309/92959385-14ab2200-f442-11ea-9881-e8c7db98e934.png)
![Screenshot-20200911105506-1913x601](https://user-images.githubusercontent.com/3237309/92959389-1674e580-f442-11ea-94c9-ccd5fc56be4a.png)

**Comment by starsinmypockets** [comment]
@avdata99 you can reproduce via curl with:

` curl -X POST https://inventory.sandbox.datagov.us/api/3/action/package_create -d '{"name": "lala"}' -H "Authorization: foo-bar-123" -H "content-type: applicaiton/json" -v`

**Comment by avdata99** [comment]
@starsinmypockets if I add 

   `-H "content-type: applicaiton/json"` 
then I get
   `"Bad request - JSON Error: Invalid request. Please use POST method for your request"`

**Comment by starsinmypockets** [comment]
I guess we could form-encode the POSTed data but maybe good to root-cause the issue?

**Comment by jbrown-xentity** [comment]
I would say we are still too far away on CKAN2.8 for inventory to wait to see if 2.8 will fix the problem. I would go ahead and implement whatever work-arounds need to happen @starsinmypockets ...

**Comment by starsinmypockets** [comment]
Looks like this is a bug in inventory -- I can reproduce this locally. I think we are hitting this exception https://github.com/GSA/ckan/blob/datagov-inventory/master/ckan/controllers/api.py#L185-L188

**Comment by adborden** [comment]
I am pretty sure you're running into this [bug](https://github.com/GSA/datagov-deploy/issues/1177). @starsinmypockets I think you're right, that you can [work around the issue by specifying `Content-Type: application/x-www-form-urlencoded`](https://github.com/GSA/datagov-deploy/issues/1177#issuecomment-579526285), without encoding your payload any differently.
