### ISSUE TITLE
Filtering By Waf-Collection Causes 500 Error

### ISSUE THREAD

**Issue by thejuliekramer** [GSA/datagov-ckan-multi#426]
From the harvest page of catalog-next.data.gov in staging, when you filter harvest sources by source type waf-collection it causes a 500 error 

## How to reproduce

1. Visit https://admin-catalog-next-datagov.dev-ocsit.bsp.gsa.gov/harvest and filter by source type waf-collection or visit https://admin-catalog-next-datagov.dev-ocsit.bsp.gsa.gov/harvest?source_type=waf-collection directly

## Expected behavior

Harvest sources should be filtered by source_type = waf-collection

## Actual behavior

A 500 error occurs

**Comment by thejuliekramer** [comment]
@avdata99 Found the logs here catalogpubweb1d.dev-ocsit.bsp.gsa.gov

This is the error <img width="861" alt="Screen Shot 2020-09-14 at 4 39 11 PM" src="https://user-images.githubusercontent.com/7378770/93141609-1e36c300-f6aa-11ea-9477-856f1fbab3e0.png">

**Comment by avdata99** [comment]
It seem the extras are _rolled_up_ at this point and we didn't expect that

**Comment by avdata99** [comment]
The `validate` function [in CKAN](https://github.com/GSA/ckan/blob/datagov-newcatalog/ckan/lib/navl/dictization_functions.py#L281) change extras. It seems related to the two underscores for the extra key

**Comment by avdata99** [comment]
Probably related with [CKAN#5549](https://github.com/ckan/ckan/issues/5549) who was fixed with [this PR](https://github.com/ckan/ckan/pull/5546/files)

**Comment by avdata99** [comment]
How to QA?

To QA this is enough to navigate the source without and error
https://catalog-next.sandbox.datagov.us/harvest/current-county-and-equivlaent-national-shapefile

Also is important to check is the extras are ok:
https://catalog-next.sandbox.datagov.us/api/3/action/harvest_source_show?name_or_id=current-county-and-equivlaent-national-shapefile

![image](https://user-images.githubusercontent.com/3237309/93502299-ed929b80-f8ec-11ea-8990-911095020529.png)

To fix other broken sources:
Firts of all we need to delete the source
```
sudo ckan dataset purge harvest-source-name -c /etc/ckan/production.ini
```
After that we can import the source without error
```
python import_harvest_sources.py --names=current-county-and-equivlaent-national-shapefile --destination_url=https://CKAN-URL.com --destination_api_key=xxxxx-xxxxxx-xxx
```

**Comment by thejuliekramer** [comment]
This is also fixed in staging at https://admin-catalog-next-datagov.dev-ocsit.bsp.gsa.gov/harvest?source_type=waf-collection
