### ISSUE TITLE
Populate values for Publisher / Subagency

### ISSUE THREAD

**Issue by starsinmypockets** [GSA/datagov-ckan-multi#429]
## User story
As a data publisher, I want to be able to choose my Publisher and Sub agency from a pre-populated, relevant list, in order to standardize these publishers across datasets. 

## Implementation notes
- Use list from current catalog 

## Acceptance Criteria
- When I visit the new metadata form at https://inventory.sandbox.datagov.us/dataset/new-metadata?group=123
- And I click to add a publisher
- I see a dropdown list of existing publishers
- And I can select one in order to populate the field 
- ~When I click in the subagency field~
- ~I see a dropdown list of existing subagencies under that publisher~
- ~And I can select one in order to populate the field~

**Comment by kimwdavidson** [comment]
@hkdctol to add list

**Comment by hkdctol** [comment]
Discussed with @starsinmypockets today and provided csv in Slack and email.
