### ISSUE TITLE
Better server error reporting in metadata app

### ISSUE THREAD

**Issue by starsinmypockets** [GSA/datagov-ckan-multi#435]
### User Story

As a data maintainer I want to see clear messages from CKAN so that I can correctly complete the metadata

### Acceptance Criteria

- [ ] Non-200 server response help text is clearly formatted as alerts
- [ ] The following server messages are clearly communicated to the user:
  - [ ] Authentication failure
  - [ ] Non-unique name / URL value
  - [ ] Non-unique Unique ID field

**Comment by kimwdavidson** [comment]
Duplicate #434
