### ISSUE TITLE
Spacing on the collection label is too tight

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#439]
The spacing to the right of the collection label is too close to the dataset title.

<img width="637" alt="Screen Shot 2020-09-23 at 4 03 56 PM" src="https://user-images.githubusercontent.com/509703/94082746-7a8a9880-fdb6-11ea-91c7-f4a4ec21ea1e.png">

There's a little more breathing room on catalog classic:
<img width="691" alt="Screen Shot 2020-09-23 at 4 05 42 PM" src="https://user-images.githubusercontent.com/509703/94082833-ad349100-fdb6-11ea-89b8-4093cf8f43ad.png">

## How to reproduce

1. https://catalog-next-datagov.dev-ocsit.bsp.gsa.gov/dataset

## Expected behavior

A about a em's worth of space to the right of the collection label and the dataset title.

## Actual behavior

The collection label is too close to the dataset title.

**Comment by thejuliekramer** [comment]
Can be QA'd here https://catalog-next.sandbox.datagov.us/organization/census-gov
