### ISSUE TITLE
Vertical alignment on dataset sidebar on catalog-next

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#440]
The vertical alignment looks incorrect for Publisher and Contact.
<img width="242" alt="Screen Shot 2020-09-23 at 4 09 40 PM" src="https://user-images.githubusercontent.com/509703/94083365-cc7fee00-fdb7-11ea-977b-e6e1db1334b5.png">

## How to reproduce

1. https://catalog-next-datagov.dev-ocsit.bsp.gsa.gov/dataset/veterans-health-administration-2008-hospital-report-card

## Expected behavior

Text should be vertically centered within the cell.

## Actual behavior

Text appears bottom aligned within the cell.

**Comment by thejuliekramer** [comment]
Can be QA'd in Sandbox as well https://catalog-next.sandbox.datagov.us/dataset/veterans-health-administration-2008-hospital-report-card

**Comment by thejuliekramer** [comment]
Can be QA'd here https://catalog-next.sandbox.datagov.us/dataset/vnpclaiminformationservice
