### ISSUE TITLE
500 server error when browsing City of Austin dataset on catalog-next

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#441]
[Brownfield Site List](https://catalog-next-datagov.dev-ocsit.bsp.gsa.gov/dataset/brownfield-site-list) fails to load with a 500 error. It looks like this might be the case for all [City of Austin datasets](https://catalog-next-datagov.dev-ocsit.bsp.gsa.gov/organization/city-of-austin).

## How to reproduce

1. https://catalog-next-datagov.dev-ocsit.bsp.gsa.gov/dataset/brownfield-site-list

## Expected behavior

Dataset page loads with a 200, receives treatment for local city non-federal dataset.

## Actual behavior

500 server error

**Comment by kimwdavidson** [comment]
Andres: working in sandbox, but failing in staging. 

Julie and Andres to determine how widespread an issue this might be. 
- If it's just this source it's not a launch blocker
- If it's all non-federal sources, maybe not a launch blocker. Hyon to make decision.
- If it's something else, to discuss again.

**Comment by hkdctol** [comment]
https://catalog-next-datagov.dev-ocsit.bsp.gsa.gov/dataset/brownfield-site-list this page loads normally. Am I missing something?

**Comment by adborden** [comment]
Right now I'm getting a 404 for all of catalog-next, but if someone can confirm then we can close this. I'm regretting not grabbing the error logs at the time. It's possible the source was re-harvested which resolved some issue 🤷

**Comment by thejuliekramer** [comment]
<img width="1379" alt="Screen Shot 2020-10-05 at 2 21 19 PM" src="https://user-images.githubusercontent.com/7378770/95122393-0df88d80-0716-11eb-813e-d0ad2394ca95.png">

I can confirm this is working correctly. Closing

**Comment by cmugisha** [comment]
From Julie: "I moved #381 and #441 to QA - both are working properly and can be moved to Done"
https://gsa-tts.slack.com/archives/CDCL978KZ/p1601926123125200
