### ISSUE TITLE
Nominate link at the bottom of dataset search page times out

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#442]
## How to reproduce

1. https://catalog-next-datagov.dev-ocsit.bsp.gsa.gov/dataset
1. Scroll to the bottom of the page and click "Didn't find what you're looking for? Suggest a dataset here."

## Expected behavior

URL takes you to the data.gov contact page https://www.data.gov/contact

## Actual behavior

Link goes to https://data.gov/navigate which times out.

**Comment by hkdctol** [comment]
Link goes to data.gov/contact
