### ISSUE TITLE
Older Adults Health topic icon does not appear in the topics menu on catalog-next

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#443]
The Older Adults Health topic was recently added, but the icon does not seem to appear on catalog-next.

<img width="976" alt="Screen Shot 2020-09-23 at 4 30 39 PM" src="https://user-images.githubusercontent.com/509703/94084371-30a3b180-fdba-11ea-92f3-f38c2371b04d.png">

## How to reproduce

1. https://catalog-next-datagov.dev-ocsit.bsp.gsa.gov/dataset
1. Click "Topic" in the primary nav menu

## Expected behavior

Icon for the Older Adults Health topic appears. 

## Actual behavior

Icon for the Older Adults Health topic does not appear.

**Comment by adborden** [comment]
FYI, the icon was added in https://github.com/GSA/datagov-deploy/issues/1964, so the PRs linked might be helpful for debuggin/fixing.

**Comment by hkdctol** [comment]
Also @jbrown-xentity if there was anything unusual about this--I recall you had to spend some time on it--can you comment?

**Comment by jbrown-xentity** [comment]
There are a number of reasons why this might be occurring.
The UI comes from a URL that is set in production.ini file with the datagovtheme extension. I would check to make sure that extension is setup, and the URL is pointing to the same instance. Also there are sometimes issues with the caching of that file, and using an old version. If you want me to work on this or pair with the ckan-multi team more thoroughly, just let me know.

**Comment by thejuliekramer** [comment]
This is working now in [catalog-next](https://catalog-next.sandbox.datagov.us/dataset) 
<img width="1194" alt="Screen Shot 2020-10-22 at 12 19 58 PM" src="https://user-images.githubusercontent.com/7378770/96907603-10225200-1461-11eb-99af-01023238f6a1.png">

**Comment by adborden** [comment]
Verified on sandbox.
