### ISSUE TITLE
CKAN API documentation URL points to 2.3.5 docs on catalog-next

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#444]
## How to reproduce

1. https://catalog-next-datagov.dev-ocsit.bsp.gsa.gov/dataset
1. Scroll to the bottom of the page and click "API Docs"

## Expected behavior

URL takes you to the CKAN 2.8 documentation.

## Actual behavior

URL takes you to the CKAN 2.3.5 documentation.

**Comment by hkdctol** [comment]
URL goes to CKAN 2.8 documentation.
