### ISSUE TITLE
RDF reference does not return valid RDF on catalog-next

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#445]
## How to reproduce

1. https://catalog-next-datagov.dev-ocsit.bsp.gsa.gov/dataset/child-labor-biographical-content
1. View the source of the page.
1. Look for the RDF link e.g. `<link rel="alternate" type="application/rdf+xml" href="https://catalog-next-datagov.dev-ocsit.bsp.gsa.gov/dataset/d3a58f26-e1ce-4f42-b3ca-963eba6dde17?format=rdf"/>`
1. Click the RDF link

## Expected behavior

Valid RDF document is returned.

## Actual behavior

The HTML version of the dataset is returned.

**Comment by avdata99** [comment]
From CKAN 2.5 changelog:

```
Changes and deprecations
------------------------

* The old RDF templates to output a dataset in RDF/XML or N3 format have been
  removed. These can be now enabled using the ``dcat`` plugin on *ckanext-dcat*:

    https://github.com/ckan/ckanext-dcat#rdf-dcat-endpoints
```

Should we add the [ckanext-dcat](https://github.com/ckan/ckanext-dcat#rdf-dcat-endpoints) extension @adborden ?

**Comment by adborden** [comment]
@avdata99 yes, let's add the dcat extension. Without this we'll fall out of [Google's Dataset Search](https://datasetsearch.research.google.com/).

**Comment by avdata99** [comment]
To QA this you can go to any dataset page and viewing the source code validate we have new URLs for RDF
 
https://CKAN-HOST/dataset/NAME-OR-ID.rdf (the final **.rdf** is what changed)

![image](https://user-images.githubusercontent.com/3237309/97902882-fb757200-1d1c-11eb-991a-acc5d8d585fc.png)

Also is possible to validate the **dcat plugin** is installed [here](https://catalog-next.sandbox.datagov.us/api/3/action/status_show)

**Comment by adborden** [comment]
`$ curl -s 'https://catalog-next.data.gov/dataset/abb6d0f6-dc43-495d-8375-c27c1658e973.rdf'`

Looks good on production.
