### ISSUE TITLE
Add topic groups to catalog-next

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#446]
## User Story

https://catalog.data.gov/group lists 22 groups, most of which should be added to catalog-next.

As a [user description], I want [behavior description] so that [goal achieved].

## Acceptance Criteria
- [ ] Groups are added in catalog-next and datasets are associated with these groups

## Details / tasks
https://github.com/GSA/datagov-deploy/issues/1964 is a recent example where we added the Older Adults Health topic.

**Comment by adborden** [comment]
At the very least we want to make sure the Older Adults Health group is added since that is a recent and active campaign.

**Comment by kimwdavidson** [comment]
- If Hyon can tell us which are in use, then only move over the ones in use
- If this requires discovery to determine, what's in use, then move all groups over.

**Comment by hkdctol** [comment]
The only groups still being used are: 
Agriculture
Climate
Energy
Local Government
Maritime
Ocean
Older Adults Health

**Comment by thejuliekramer** [comment]
@FuhuXia we also need that CSV file with the tags and groups mentioned in https://github.com/GSA/ckanext-geodatagov/pull/170 in order to complete this task

**Comment by thejuliekramer** [comment]
@hkdctol so of the 22 in prod we only need to worry about these 7 groups?

> The only groups still being used are:
> Agriculture
> Climate
> Energy
> Local Government
> Maritime
> Ocean
> Older Adults Health

**Comment by hkdctol** [comment]
@thejuliekramer yes, correct. the others are remnants

**Comment by avdata99** [comment]
How to QA
We can see the groups imported to the sandbox here: https://catalog-next.sandbox.datagov.us/group

![image](https://user-images.githubusercontent.com/3237309/96028854-3e37de80-0e30-11eb-8ca6-c2a601d1a77c.png)

Also, we can run the importer to the staging environment

**Comment by hkdctol** [comment]
@avdata99 On staging I see 2 groups but it's just a matter of importing these? I see them all on sandbox.

**Comment by avdata99** [comment]
> @avdata99 On staging I see 2 groups but it's just a matter of importing these? I see them all on sandbox.

Stagging will be filled by @adborden or @thejuliekramer 

The command to just import and connect **these groups** is:

```
python import_groups.py \
    --destination_url=https://catalog-stagging-url \
    --destination_api_key=xxx  \
    --groups=agriculture8571,climate5434,energy9485,local,maritime,ocean9585,older-adults-health-data
```

**Comment by cmugisha** [comment]
Julie will QA this once it's been unblocked.

**Comment by thejuliekramer** [comment]
Groups have been added to catalog next 
<img width="1052" alt="Screen Shot 2020-10-12 at 5 29 47 PM" src="https://user-images.githubusercontent.com/7378770/96600600-b9791480-12b6-11eb-933d-20db57522008.png">

**Comment by thejuliekramer** [comment]
Does this need to be in blocked or can we just add 'Groups' to the acceptance criteria for when we deploy to production?

**Comment by thejuliekramer** [comment]
Created https://github.com/GSA/datagov-ckan-multi/issues/492 to track this issue for production environment
