### ISSUE TITLE
Add sitemap to robots.txt on catalog-next

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#447]
## User Story

As an open data user, I want a crawlable sitemap listed in https://catalog-next-datagov.dev-ocsit.bsp.gsa.gov/robots.txt so that I can use everyday search engines to search and index data.gov.

## Acceptance Criteria
- [ ] WHEN I browse to https://catalog-next-datagov.dev-ocsit.bsp.gsa.gov/robots.txt
  THEN I see an entry for Sitemap pointing to filestore.data.gov
- [ ] WHEN I inspect the crontab on catalog-next harvesters
  THEN I see the s3 sitemap job is disabled

**Comment by kimwdavidson** [comment]
@avdata99 to determine implementation plan

**Comment by avdata99** [comment]
Some notes:
 - [ckanext-sitemap](https://github.com/kata-csc/ckanext-sitemap) don't include multiple-page sitemaps and we need it.
 - GeoDataGov includes [a command](https://github.com/GSA/ckanext-geodatagov/blob/master/ckanext/geodatagov/commands.py#L1032:L1032) to generate a multiple file sitemap to deal with the huge amount of data to show.
 - This command uses some [custom functions in CKAN 2.3 fork](https://github.com/GSA/ckan/blob/datagov/ckan/lib/search/query.py#L248-L281) that are not available now.

**Comment by avdata99** [comment]
The solution requires to use functions in CKAN 2.3 fork (related to #278)

**Comment by avdata99** [comment]
Before QA:
 - Ensure 3 PRs are merged
 - The `sitemap-to-s3` command run in the sandbox environment (validate [new URL](https://filestore.data.gov/gsa/catalog-next/sitemap/sitemap.xml) is working)

Hot to review it in sandbox?
 - Go to [robots.txt URL](https://catalog-next.sandbox.datagov.us/robots.txt) and validate:
   + We have a `Sitemap` line
   + The `Sitemap` line point to the new sitemap URL: https://filestore.data.gov/gsa/catalog-next/sitemap/sitemap.xml (check the **catalog-next** folder)

**Comment by thejuliekramer** [comment]
@avdata99 I don't see the sitemap line in sandbox or staging - reassigning to you to look at

**Comment by thejuliekramer** [comment]
Verified

<img width="478" alt="Screen Shot 2020-10-01 at 5 45 35 PM" src="https://user-images.githubusercontent.com/7378770/94870725-f23b7180-040d-11eb-805b-35eba56237ba.png">

**Comment by adborden** [comment]
@thejuliekramer @avdata99 on catalog.data.gov the sitemap is
> Sitemap: https://filestore.data.gov/gsa/catalog/sitemap/sitemap.xml

But catalog-next is:
> Sitemap: https://filestore.data.gov/gsa/catalog-next/sitemap

Are our configuration values correct?

**Comment by avdata99** [comment]
@adborden the idea to use different sitemap URLs was proposed here https://github.com/GSA/datagov-deploy/pull/2216
This values is what we expect.

**Comment by adborden** [comment]
@avdata99 that is okay, but https://filestore.data.gov/gsa/catalog-next/sitemap results in a 404, which does not seem okay.

**Comment by adborden** [comment]
I opened https://github.com/GSA/datagov-ckan-multi/issues/480 issue to track. I think we need the sitemap job running in production first, but then the configuration value should be obviously correct or not.

**Comment by avdata99** [comment]
Ok @adborden, we will need to run the sitemap_to_s3 command in stagging to create this new file
