### ISSUE TITLE
Investigate: DOI Open Data (ckan-to-ckan) harvest source has too many missing datasets

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#450]
[DOI Open Data](https://admin-catalog-next-datagov.dev-ocsit.bsp.gsa.gov/harvest/admin/doi-open-data) harvest source is missing too many datasets, with 20k errors in a recent harvest. We should be closer to 20k datasets for DOI.

![Screen Shot 2020-09-24 at 11 36 32 AM](https://user-images.githubusercontent.com/509703/94185901-d149ae00-fe5a-11ea-83ba-075cd2c1a477.png)

Note that this issue is not necessarily about fixing the harvest source, but about getting at least one good harvest run in so that DOI's datasets appear complete.

## How to reproduce

1. https://admin-catalog-next-datagov.dev-ocsit.bsp.gsa.gov/organization/doi-gov

## Expected behavior

I see at least 20,000 datasets

## Actual behavior

I see only 3717. The harvest job is failing midway through.

**Comment by jbrown-xentity** [comment]
Just to make sure, this should be a CKAN-to-CKAN harvest at https://data.doi.gov...

**Comment by kimwdavidson** [comment]
Duplicate #472. Closing
