### ISSUE TITLE
Enable clean_harvest_log job on catalog-next

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#453]
## User Story

As a data.gov operator, I want the [clean_harvest_log](https://github.com/ckan/ckanext-harvest/blob/master/ckanext/harvest/model/__init__.py#L444) job enabled and running everyday so that the database is maintained at a scalable size without impacting performance.

## Acceptance Criteria
- [ ] GIVEN the harvest extension is configured to job logs older than 180 days
  WHEN I inspect the supervisor job logs `/var/log/ckan/clean_harvest_log.log` on misc worker
  THEN I see log entries for clean_harvest_log running with timestamp every day

## Details / tasks
- Add a job to the supervisor configuration
- Add a cron job to start the supervisor job
- Ensure the job is not enabled on catalog classic

**Comment by adborden** [comment]
@avdata99  I don't think this is actually enabled on any single host... pull request ^

**Comment by cmugisha** [comment]
@adborden  What's the estimate on this?

**Comment by adborden** [comment]
It looks like this is already merged and done.

**Comment by adborden** [comment]
Not seeing the logfile. Looks like /etc/cron.d/ckan gets overwritten by the following task. Pushed a PR to fix ^

**Comment by adborden** [comment]
Seeing successful log messages on catalogharvester2p.

> 2021-01-11 02:30:15,865 INFO  [ckanext.harvest.model] Harvest log table clean-up finished successfully
