### ISSUE TITLE
Edit existing dataset resources using new form

### ISSUE THREAD

**Issue by osahon-okungbowa** [GSA/datagov-ckan-multi#455]
### User Story
As a dataset publisher, when editing/updating an existing dataset I should be taken through the new metadata form, so that there is a consistent experience with creating a new dataset

### Acceptance Criteria
- [x] when i click on the `Edit` button for an existing dataset
- [x] the new metadata form is loaded
- [x] all pre-existing data from the dataset is properly pre-filled into the new Required Metadata page
- [x] all pre-existing data from the dataset is properly pre-filled into the new Additional Metadata page
- [x] when i change a field 
- [x] and i click on finish and publish
- [x] then the dataset is updated

**Comment by kimwdavidson** [comment]
Scooting this out of To Do for just a moment. We may need the "manage" button to do something different, so holding while we figure that out. See #504
