### ISSUE TITLE
Topic Categories is empty on catalog-next

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#459]
We shouldn't be showing a filter group if it's empty. We can [populate the Topic Categories](https://github.com/GSA/datagov-ckan-multi/issues/458) or we can just hide the filter group.

![Screen Shot 2020-09-25 at 12 07 36 PM](https://user-images.githubusercontent.com/509703/94306399-be50df80-ff27-11ea-8753-77669babe844.png)

## How to reproduce

1. https://admin-catalog-next-datagov.dev-ocsit.bsp.gsa.gov/dataset

## Expected behavior

Only filter groups that have filters in them appear.

## Actual behavior

The Topic Categories filter group appears empty.

**Comment by hkdctol** [comment]
![Screen Shot 2020-10-02 at 3 41 01 PM](https://user-images.githubusercontent.com/3236989/94963376-0e9ae500-04c6-11eb-8ec9-f27c72aedc8a.png)
the only "Topic" still occasionally adding datasets and "Categories" is Climate. I can ask them if this is important if this work is difficult or too time consuming.
