### ISSUE TITLE
Additional metadata links result in a 404

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#460]
https://catalog-next.sandbox.datagov.us/dataset/basemap-framework-submission-for-santa-fe-county-nm-and-incorporated-areas

The primary "Download Metadata" URL works correctly, but the others result in a 404:
- https://catalog-next.sandbox.datagov.us/harvest/object/6161aae3-33a0-4462-8d97-a7e96ab93037/html
- https://catalog-next.sandbox.datagov.us/harvest/object/6161aae3-33a0-4462-8d97-a7e96ab93037/original
- https://catalog-next.sandbox.datagov.us/harvest/object/6161aae3-33a0-4462-8d97-a7e96ab93037/html/original

![Screen Shot 2020-09-25 at 2 12 29 PM](https://user-images.githubusercontent.com/509703/94316431-2d82ff80-ff39-11ea-91e2-c3809fca51ed.png)

## How to reproduce

1. https://catalog-next.sandbox.datagov.us/dataset/basemap-framework-submission-for-santa-fe-county-nm-and-incorporated-areas
1. Click "View Full Metadata", "Download Original Metadata", or "View Original Full Metadata"

## Expected behavior

View Full Metadata is an HTML rendering of the ISO-19139 transformed metadata.

Download Original Metadata should show the original CSDGM formatted metadata, before the transform.

View Original Full Metadata is an HTML rendering of the CSDGM formatted metadata.

## Actual behavior

All three links result in 404, page not found.

**Comment by adborden** [comment]
Before picking this up, I'd like to understand the effort involved in fixing these. Are these links from our forks? Do we understand the use case for these, or which audience these are for?

**Comment by avdata99** [comment]
@adborden it seems we just miss to add the `spatial_harvest_metadata_api` plugin. [ref code](https://github.com/GSA/ckanext-spatial/blob/master/ckanext/spatial/plugin.py#L408:L418)

Started PRs:
PR for deploy: https://github.com/GSA/datagov-deploy/pull/2311
PR for catalog-next: https://github.com/GSA/catalog.data.gov/pull/148

**Comment by avdata99** [comment]
Regarding the audience: these URLs show the source document before being harvested. I guess it's for technical users

**Comment by avdata99** [comment]
the QA this will be required to re-harvest the source

**Comment by adborden** [comment]
Verified on sandbox.
