### ISSUE TITLE
Improve build time for catalog-next repo

### ISSUE THREAD

**Issue by avdata99** [GSA/datagov-ckan-multi#463]
## User Story

As a GSA developer, I want a faster [build for the local environment](https://github.com/GSA/catalog.data.gov/blob/bugfix/harvest-source-type/ckan/Dockerfile) so that when we run the CI tests we don't lose 15 minutes each time.

## Acceptance Criteria
- [ ] `docker-compose build` require fewer time to run 

## Details / tasks

Our current local development environment uses a [Dockerfile](https://github.com/GSA/catalog.data.gov/blob/bugfix/harvest-source-type/ckan/Dockerfile) inherent from an [alpine Dockerfile](https://github.com/okfn/docker-ckan/blob/master/ckan-base/2.8/Dockerfile) and the build process take at least 15 minutes each time

![image](https://user-images.githubusercontent.com/3237309/94442605-8ab9c380-017a-11eb-925b-f1ba296050b9.png)

**Comment by avdata99** [comment]
Ideas:
 - Build a `catalog-next` image and publish it in the [DataGov dockerhub account](https://hub.docker.com/u/datagov) so we can use it as a part of the CI process of our extensions.
 - Start using a new docker environment with Ubuntu and stop using Alpine

**Comment by avdata99** [comment]
@adborden we get the message `Specified using docker layer caching, but it is only available for Performance Plan`  [here](https://app.circleci.com/pipelines/github/GSA/catalog.data.gov/550/workflows/b50bef62-2c4c-4250-849a-57d0a318b108/jobs/1107)

![Screenshot-20201014135523-940x234](https://user-images.githubusercontent.com/3237309/96030702-b7d0cc00-0e32-11eb-86da-c9efdc2c78d6.png)

We need to check [our account plan](https://app.circleci.com/settings/plan/github/GSA/overview)

**Comment by adborden** [comment]
The short answer, is that we're not going to be able resolve the issue with the CircleCI plan very quickly.

I checked with our #infrastructure team, and the outlook on Docker Hub is not good, but as of right now, it's still an option. Let's try that for now.

**Comment by thejuliekramer** [comment]
@adborden can you review this when you get a chance https://github.com/GSA/catalog.data.gov/pull/147

**Comment by adborden** [comment]
GSA/catalog.data.gov still takes 23 minutes to build. I think with the docker publish we've added 3 minutes.

The extension repos are 10 minutes faster now that they use the existing image. That seems okay to me.
