### ISSUE TITLE
Help text updates

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#467]
## Description
- [x]  Media type field says to start typing, but is a dropdown (Jacqueline to add text to spreadsheet)
- [x] Temporal field says to provide a start date in the second temporal field, but should say end date
- [x] Public Access Level dropdown is missing descriptions of levels
- [x] Resource help text is inside field, which disappears when you start typing

## Acceptance criteria
- [ ] When I go to the required metadata form
- [ ] And I click into the Public Access Level dropdown
- [ ] Then I see each level with the description of the level
- [ ] And I see the second temporal field with help text that says, "If your dataset has a temporal component, please provide end date for applicability of data above," not "start date"
- [ ] When I go to the resource upload page
- [ ] And I click on the "Link to data" button
- [ ] I see help text "If you are linking to a dataset, please include "http://" at the beginning of your URL" under the field, not inside it.
- [ ] And I see the media type field has help text that says, ""

**Comment by gujacq** [comment]
I suggest removing the text altogether. I believe the title, the dropdown, and the items in the dropdown menu make it intuitive what it should be.

I'd reflected it as such on the spreadsheet: F53 https://docs.google.com/spreadsheets/d/1bWt_uLloRQ5Rd8HI22COUlIwH_REsywHJ43NmkQNSv0/edit#gid=746832760

**Comment by kimwdavidson** [comment]
@starsinmypockets: I'm not seeing any of these changes on sandbox:

![Screen Shot 2020-10-01 at 5 12 23 PM](https://user-images.githubusercontent.com/22527532/94863968-47c14f80-0409-11eb-8e84-e476200072c8.png)
![Screen Shot 2020-10-01 at 5 12 37 PM](https://user-images.githubusercontent.com/22527532/94863991-50198a80-0409-11eb-809e-1902e410f02b.png)
![Screen Shot 2020-10-01 at 5 12 57 PM](https://user-images.githubusercontent.com/22527532/94864023-5c054c80-0409-11eb-8ab5-207e5e1805ac.png)
![Screen Shot 2020-10-01 at 5 13 14 PM](https://user-images.githubusercontent.com/22527532/94864047-66274b00-0409-11eb-8967-3e7a9fbfee61.png)
