### ISSUE TITLE
Evaluate Datasets Not Harvesting

### ISSUE THREAD

**Issue by thejuliekramer** [GSA/datagov-ckan-multi#470]
There are some harvest sources in staging where the number of datasets are not comparable to those in production. We need to figure out why

## How to reproduce

1. Visit report https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit#gid=263740072
2. Find harvest sources the need work
3. Debug issue

## Expected behavior

1. Visit report https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit#gid=263740072
2. All harvest sources should be ok

## Actual behavior

1. Visit report https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit#gid=263740072
2. Some harvest sources still need work

**Comment by kimwdavidson** [comment]
Duplicate. Closing
