### ISSUE TITLE
Data upload workflow usability

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#478]
## Description: 
Current workflow is confusing

## Acceptance criteria
- Workflow should reflect preferred state under Resource Upload in these mockups: https://www.figma.com/file/klRVVF5U6fFmDbiu3s6L3g/Metadata-Form?node-id=648%3A1297

**Comment by kimwdavidson** [comment]
@anuveyatsu i'm still seeing the old workflow here:

![Screen Shot 2020-10-09 at 11 47 56 AM](https://user-images.githubusercontent.com/22527532/95604159-49040500-0a25-11eb-8763-bf88f806f74a.png)

**Comment by anuveyatsu** [comment]
Hi @kimwdavidson sorry about confusion. It should be deployed soon once we have tests passing.
