### ISSUE TITLE
Remove "Sub Agency" field

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#479]
## Description
Sub Agency is a bit of a misnomer, since it's actually the parent agency. It's also predictable from the submitters agency choice.

## Acceptance criteria
- [ ] When I go to the required metadata entry form
- [ ] I do not see the sub agency field

**Comment by adborden** [comment]
IMHO I think we should do https://github.com/GSA/datagov-ckan-multi/issues/481 instead of this issue.

My understanding is that if we remove Sub Agency now, then we'll have to go back and clean up data missing information when we do #481.

**Comment by kimwdavidson** [comment]
I had this in the backlog, so we wouldn't be doing it now!

I'll go ahead and close it as a duplicate, though.
