### ISSUE TITLE
catalog-next sitemap results in 404

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#480]
https://catalog-next-datagov.dev-ocsit.bsp.gsa.gov/robots.txt reports the sitemap as `https://filestore.data.gov/gsa/catalog-next/sitemap` which results in a 404. The sitemap URL in robots.txt should point to a valid sitemap XML file.

## How to reproduce

1. https://catalog-next.data.gov/robots.txt
1. Identify the `Sitemap` URL
1. Open the sitemap URL in your browser.

## Expected behavior

robots.txt refers to a valid sitemap XML file.

## Actual behavior

robots.txt refers to `https://filestore.data.gov/gsa/catalog-next/sitemap` which results in a 404

**Comment by adborden** [comment]
I think there's two issues going on here. One is that the sitemap job is not running in production. Staging probably does not have credentials to upload to filestore.data.gov.

Two, the configuration for the sitemap is wrong, I think it should be https://filestore.data.gov/gsa/catalog-next/sitemap/sitemap.xml, which is closer to what is on catalog-classic.

**Comment by avdata99** [comment]
Steps to publish sitemap in the new production environment

 - run `sudo ckan geodatagov sitemap-to-s3`
 - If fails, ensure configuration is set [here](https://github.com/GSA/ckanext-geodatagov/blob/master/ckanext/geodatagov/commands.py#L1126-L1127) and [here](https://github.com/GSA/ckanext-geodatagov/blob/master/ckanext/geodatagov/commands.py#L1349:L1349)

**Comment by thejuliekramer** [comment]
@adborden We are missing these values in production catalog next 

<img width="621" alt="Screen Shot 2020-11-10 at 10 45 33 AM" src="https://user-images.githubusercontent.com/7378770/98704163-f1b5c500-2341-11eb-8526-2a4415c04821.png">

Is it ok to add these to catalog next in datagov-deploy?

**Comment by avdata99** [comment]
This PR is a proposal to add credential to catalog-next: https://github.com/GSA/datagov-deploy/pull/2412

**Comment by adborden** [comment]
@thejuliekramer sure, but be careful about posting configuration files on public issues like that. Technically aws_bucket_name is stored in the vault and should be treated as a secret (but I don't think it's really a secret).

**Comment by thejuliekramer** [comment]
After deploying the [config changes](https://github.com/GSA/datagov-deploy/pull/2412/files) to Production - I ran `ckan --plugin-ckanext-geodatagov geodatagov sitemap-to-s3` and receive this error:

<img width="881" alt="Screen Shot 2020-11-17 at 12 56 26 PM" src="https://user-images.githubusercontent.com/7378770/99434689-ae74cc80-28d4-11eb-956b-8445c881140b.png">

**Comment by thejuliekramer** [comment]
This is ready for QA

Visit https://catalog-nextd.data.gov/robots.txt 

Sitemap is defined as https://filestore.data.gov/gsa/catalog-next/sitemap/sitemap.xml

Visit https://filestore.data.gov/gsa/catalog-next/sitemap/sitemap.xml

**Comment by adborden** [comment]
@thejuliekramer in https://catalog-next.data.gov/robots.txt I'm seeing Sitemap: https://filestore.data.gov/gsa/catalog-next/sitemap/ which still 404s.

**Comment by thejuliekramer** [comment]
I think maybe you have a cached version?

<img width="712" alt="Screen Shot 2020-11-18 at 11 51 07 AM" src="https://user-images.githubusercontent.com/7378770/99567917-5ef5d580-2994-11eb-9c2d-982f388e0a21.png">

**Comment by adborden** [comment]
Oops, yes, that was it! Hmm, strange because it should not have been cached that long `Cache-Control: public, max-age=300, must-revalidate`. 🤷
