### ISSUE TITLE
Populate parent publisher hierarchy from single publisher field

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#481]
## User Story

As a data manger, I want to input a single publisher field (the one with the most specificity) and have the parent publishers automatically filled in so that I don't have to specify multiple parents that are mostly redundant.

## Acceptance Criteria
- [ ] WHEN I click Add Dataset from inventory.data.gov
  THEN I see a single Publisher auto-complete field AND I don't see Sub Agency field
- [ ] GIVEN I am a member of GSA
  WHEN I start typing "Data.gov" in the Publisher field
  THEN only GSA publishers are auto-completed
  AND when I select "Data.gov" the publisher chain includes "General Services Administration" -> "Technology Transformation Service" -> "Data.gov"
- [ ] GIVEN I save a dataset with the Publisher "Data.gov"
   WHEN I export my data.json file
  THEN I see the `publisher` field is:
```
"publisher": {
  "@type": "org:Organization",
  "name": "Data.gov",
  "subOrganizationOf": {
    "@type": "org:Organization",
    "name": "Technology Transformation Service",
    "subOrganizationOf": {
      "@type": "org:Organization",
      "name": "General Services Administration"
    }
  }
}
```

## Details / tasks
The list of existing Publishers are in this [spreadsheet](https://docs.google.com/spreadsheets/d/1VeHgn1uzDiqOO6Fu8UKdmjTY7IENDysnsLsuloZQ2Jc/edit#gid=32258133).
- [ ]  Clean the spreadsheet (remove blanks and invalid data).
- [x] Convert spreadsheet into json list
- [ ]  Split the spreadsheet into groups that should be assigned to each CKAN organization. For example, users in the GSA org should only see publishers where "General Services Administration" is the top-level publisher.
- [ ]   Figure out how to store/represent the Publisher hierarchy in code. Individual CSVs? `extras` on organizations?
- [ ] Populate Publishers for each organization
- [ ] On form render, load the correct list of publishers for the organization.
- [x] Remove Sub Agency
- [x] Convert the Publishers dropdown to autocomplete
- [x] Publisher field should not have any “Other” option
- [x] Update info popover 

Note that the top-level publisher is not one-to-one with CKAN organizations. For example Department of Labor is made up of 19 CKAN organizations in inventory.data.gov. It's okay to use a single DOL publisher list for all of these organizations.

**Comment by avdata99** [comment]
To be considered: 
 - The data.json will be genered with [this action](https://github.com/GSA/ckanext-datajson/blob/master/ckanext/datajson/plugin.py#L69-L70). You will need to be sure [routes are enabled](https://github.com/GSA/ckanext-datajson/blob/master/ckanext/datajson/plugin.py#L39:L39) before running. Use the `ckanext.datajson.url_enabled` config value.
- The datajson harvester will read this data [here](https://github.com/GSA/ckanext-datajson/blob/master/ckanext/datajson/parse_datajson.py#L69-L82)

**Comment by avdata99** [comment]
The URL `/data.json` is not working now in the inventory

These URLs are already working:
 - https://inventory.sandbox.datagov.us/organization/general-services-administration/draft.json
 - https://inventory.sandbox.datagov.us/organization/general-services-administration/redacted.json
 - https://inventory.sandbox.datagov.us/organization/general-services-administration/unredacted.json

I go to `/etc/ckan/production.ini` in the inventory sandbox and changed the configuration
  `ckanext.datajson.url_enabled` to True
and restart CKAN
  `supervisorctl restart gunicorn-web-app`

And now these URLs are working:
https://inventory.sandbox.datagov.us/organization/general-services-administration/data.json
https://inventory.sandbox.datagov.us/data.json

**Comment by avdata99** [comment]
> @avdata99 do you need to make the config change in GSA/datagov-deploy?

Not sure @adborden. Maybe @osahon-okungbowa could validate we need a permanent change

**Comment by osahon-okungbowa** [comment]
> Not sure @adborden. Maybe @osahon-okungbowa could validate we need a permanent change

@adborden just discussed with @avdata99 . Yes, we need to make this update permanent across deployment cycles.
@avdata99 will raise a PR regarding this for your approval

**Comment by avdata99** [comment]
@adborden I created [a PR](https://github.com/GSA/datagov-deploy/pull/2277) for this.
I think this is going to activate this URL for _inventory-next_ and also for the old one. Do we want this?
Should we create different production.ini files for each inventory environment?

**Comment by adborden** [comment]
@avdata99 hmm, stepping back on this... what does /data.json have to do with this story? The data.json file is generated from the inventory buttons and the [URLs that were already working](https://github.com/GSA/datagov-ckan-multi/issues/481#issuecomment-707759757). I don't think we need the /data.json enabled for this story.

**Comment by osahon-okungbowa** [comment]
@adborden it's not tied to this story alone. I'll explain better during scrum, so you can have clearer context before you decide

**Comment by adborden** [comment]
Chatted in scrum, sounds like the /data.json URL was to be able to test the output of the data.json. Instead, we should use the inventory workflow, which involves clicking the export redacted inventory button on the organization page. This is how production works and this is how our users will be generating the data.json file.

**Comment by kimwdavidson** [comment]
Adding a column to the publisher spreadsheet.

**Comment by hkdctol** [comment]
Updated spreadsheet, with each row with a parent/top level organization in the second column: https://docs.google.com/spreadsheets/d/1BWpXWswnnMRaNazMCYrzl4W5JMWpGuyW0Wo2YaNH9jY/edit?usp=sharing
[Inventory publishers-November 17-Updated.xlsx](https://github.com/GSA/datagov-ckan-multi/files/5557031/Inventory.publishers-November.17-Updated.xlsx)

**Comment by adborden** [comment]
I also did a pass through. I rearranged the columns so they are ordered from top-level parent (publisher) to 4th grand-child (publisher_5). I also removed the redundant top-level names and removed the abbreviations.

**Comment by hkdctol** [comment]
@osahon-okungbowa Attaching Excel version with Aaron's updates
[Nov 18 version inventory publishers.xlsx](https://github.com/GSA/datagov-ckan-multi/files/5562105/Nov.18.version.inventory.publishers.xlsx)

**Comment by cmugisha** [comment]
@osahon-okungbowa Kim had said that this ticket had a question for Aaron before Karlen could work on it. Is that still the case or can Karlen pick it up as is?

**Comment by osahon-okungbowa** [comment]
@cmugisha This issue is clear now. No questions or blockers. Karlen has commenced work on it 👍

**Comment by adborden** [comment]
I think we chatted about this and will end up splitting it into multiple stories...

**Comment by kmanaseryan** [comment]
![image.png](https://images.zenhubusercontent.com/5f6328c257f4b155de7c38d7/1d254ab1-0f5d-40e7-92dc-67e1356bf00d)

Since we are removing Sub Agency optional field, I guess we should update the info text as well ^^

**Comment by adborden** [comment]
Yeah, I think it should read:
> The publishing entity (e.g. your agency, department, bureau, or office).

**Comment by hkdctol** [comment]
This is blocked pending a problem with login.gov -- it is not accepting my password or email even though I have an account with gsa address.

**Comment by hkdctol** [comment]
@kimwdavidson maybe you can try it if it's a problem just with my account?

**Comment by osahon-okungbowa** [comment]
@hkdctol this is only available to QA in sandbox https://inventory.sandbox.datagov.us/ and sandbox doesn't require login.gov

**Comment by hkdctol** [comment]
thanks--got confused with inventory next sandbox--this update on publisher info text is done
![publisher field](https://user-images.githubusercontent.com/3236989/102111956-08e64780-3e05-11eb-9688-27a586b58ab6.png)
