### ISSUE TITLE
Add "Update Frequency" field in Inventory new dataset form

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#482]
## User Story

As a data manager, I want to easily select the `Update Frequency` field from a set of common options so that I can easily select a meaningful `Update Frequency` value for my dataset.

## Acceptance Criteria
- [x] WHEN I view the `modified` drop-down
  THEN I see options:
  - Daily
  - Weekly
  - Monthly
  - Yearly
  - As needed (formerly "ad hoc")
  - Custom
- [x] WHEN I select "Daily" for modified
  THEN the dataset is saved with the value `R/P1D`
- [x] WHEN I select "As needed"  (formerly "ad hoc")
  THEN the dataset is saved with the value of the current date/time.
- [x] WHEN I select "Other"
  THEN I am presented with the help text referencing ISO 8601 with a link to the wikipedia page and examples of recurrence periods I can use
  AND a text input is available for me to enter a custom recurrence period
- [x] GIVEN I select "Other"
  AND I type "monthly"
  WHEN I click "Save"
  THEN I am presented an error that the modified field is not formatted as a proper ISO 8601 timestamp.

## Details / tasks
[modified](https://resources.data.gov/resources/dcat-us/#modified) field is a bit confusing in the spec. It can be a representation of when the dataset is updated (a recurring value) OR it can be when the dataset was last updated. These should probably be two separate fields in the spec, but for now, it is what it is.
- [x] identify an ISO 8601 validator library

**Comment by adborden** [comment]
I haven't done any research into this, but if an ISO 8601 datetime picker exists that supports the recurrence periods, that would replace the drop-down.

**Comment by osahon-okungbowa** [comment]
@adborden can we pickup this issue to work on now? it's pretty clear what's needed

**Comment by adborden** [comment]
No, I'd rather tackle some of the technical debt first before we start this issue.
