### ISSUE TITLE
Temporal field updates for IE

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#484]
## Description

- No date picker is available for the form in IE, so we should add the format to the help text: 

"If your dataset has a temporal component, please provide start date for applicability of data above (MM/DD/YYYY)"

- We should also validate the date in IE, since the date picker won't do that automatically

## Acceptance Criteria
- [x] When I am in Internet Explorer 11
- [x] And I go to Add Dataset
- [x] And I go to the temporal fields
- [x] Then I see help text that says "If your dataset has a temporal component, please provide start date for applicability of data above (MM/DD/YYYY)" and same for end date
- [x]  When I enter the required metadata and enter the temporal field correctly
- [x] And I save
- [x] Then the form passes validation
- [x]  When I enter the required metadata and enter the temporal field incorrectly
- [x] And I save
- [x] Then I see a helpful error message

**Comment by hkdctol** [comment]
All worked on IE11 - when correct format, saved successfully, when incorrect format, I got error message.
