### ISSUE TITLE
Resource type different for 2.3 and 2.8

### ISSUE THREAD

**Issue by avdata99** [GSA/datagov-ckan-multi#487]
[A resource](https://catalog.data.gov/dataset/noaa-unified-access-framework-uaf/resource/c366164b-9e38-4279-af98-18408e5ca864) harvested in CKAN 2.3 is interpreted with format `NetCDF File`
[The same resource](https://catalog-next.sandbox.datagov.us/dataset/noaa-unified-access-framework-uaf/resource/89c11769-51b9-414f-bbf4-6824b2a7b030) in CKAN 2.8 is showed as `Web Resource`

Both resources point to this URL: https://data.nodc.noaa.gov/cgi-bin/iso?id=noaa_dmit_uaf

![image](https://user-images.githubusercontent.com/3237309/96269311-9b52a200-0fa0-11eb-8952-02f136c838de.png)

![image](https://user-images.githubusercontent.com/3237309/96269576-ee2c5980-0fa0-11eb-863a-3f9dca83a68f.png)

## How to reproduce

Harvest the `uaf-waf` source in old and new catalog.

## Expected behavior

Both resources must be interpreted in the same format

## Actual behavior

The formats are different

**Comment by chris-macdermaid** [comment]
CKAN 2.8 is using a newer version of OWSLib. That may be the cause of the differences. CKAN 2.8 has the correct format for that resource.

**Comment by avdata99** [comment]
Thanks @chris-macdermaid. If catalog-next has the right format and the error is in CKAN 2.3 we can close this.
Do you agree @adborden?
