### ISSUE TITLE
Duplicates in Publisher list

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#491]
## Description
Currently, the list of publishers contains duplicates, different listings of the same organization, and duplicates including typos. This ticket is for cleaning and streamlining that list.

**Comment by adborden** [comment]
[Inventory publishers](https://docs.google.com/spreadsheets/d/14NSn2siNsZk4NifHo9T7Y-zm9DMUpFDnuqLpNUlLIWs/edit).

**Comment by hkdctol** [comment]
Use this updated list
[Inventory publishers-Updated.xlsx](https://github.com/GSA/datagov-ckan-multi/files/5423767/Inventory.publishers-Updated.xlsx)
