### ISSUE TITLE
Import Groups in catalog-next Production Environment

### ISSUE THREAD

**Issue by thejuliekramer** [GSA/datagov-ckan-multi#492]
## User Story

As a catalog-next, I want groups to be imported so that I can group datasets within groups.

## Acceptance Criteria
- [x] `/group` should should show groups and these groups should be present
   - [x] Agriculture
   - [x] Climate
   - [x] Energy
   - [x] Local Government
   - [x] Maritime
   - [x] Ocean
   - [x] Older Adults Health 
- [x] groups should be associated with datasets

## Details / tasks

- [x] import groups using script in catalog.data.gov `python import_groups.py --destination_url=xxx --destination_api_key=xxxx --groups=agriculture8571,climate5434,energy9485,local,maritime,ocean9585,older-adults-health-data`

**Comment by thejuliekramer** [comment]
@hkdctol this is ready to QA https://catalog-next.data.gov/group

**Comment by hkdctol** [comment]
@thejuliekramer what about the icons? Would that be a different ticket?

**Comment by hkdctol** [comment]
Actually--I see that in /groups view in production the icons aren't there either.
