### ISSUE TITLE
Disable "Finish and publish" button while new metadata form is submitting

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#495]
When uploading a large dataset on a slow connection, there's no indication if the form submission is in progress, succeeded or failed.

## How to reproduce

As a logged in user:
1. Browse to the new metadata form https://inventory.sandbox.datagov.us/dataset/new-metadata
1. Enter required metadata
1. Click Save and Continue
1. Click Save and Continue to continue to Resource Upload form
1. Click Upload data
1. Select a larger file e.g. 24MB Per Diem dataset https://inventory.data.gov/dataset/ad729937-b245-4eec-a88d-b72eb36d8106/resource/e0eb3a12-a13d-4b83-af5c-8dcb73042c3d/download/perdiemreimbursementratesfy20fy16.csv
1. Click Finish and publish

## Expected behavior

Button is disabled. Text or progress indicator appears that the submission is in progress:
> Your submission is in progress, this may take a few minutes for large dataset files.

## Actual behavior

No change, it looks like the request hangs while the request is pending.

The 24MB file successfully submitted after 5.7 minutes.

**Comment by hkdctol** [comment]
I get the expected behavior when trying to upload a dataset that is 51MB![Screen Shot 2020-10-29 at 12.22.09 PM.png](https://images.zenhubusercontent.com/5d374a506df6e4059e63379d/6d70f6bc-4a1f-433a-8f82-662a0bd974dd)
