### ISSUE TITLE
Update publisher dropdown

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#498]
## User story
As a data publisher, I want to see a sanitized list of publisher options, so that I can choose the correct publisher without duplicates.

## Acceptance Criteria
- When I go to the new metadata form
- And I click on the publisher dropdown
- I should see options that match the attached list. [https://app.zenhub.com/files/153296282/29401b9b-1647-49f3-80fd-44afd93fcd06/download](https://app.zenhub.com/files/153296282/29401b9b-1647-49f3-80fd-44afd93fcd06/download)

**Comment by hkdctol** [comment]
Publisher field shows the updated list
![Screen Shot 2020-10-29 at 12 31 03 PM](https://user-images.githubusercontent.com/3236989/97603352-bbdc1c80-19e2-11eb-9d0a-340d7fa0761b.png)

**Comment by cmugisha** [comment]
@hkdctol Should this be moved to Done?
