### ISSUE TITLE
Import harvest sources to production

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#499]
## User story
As the data.gov team, I want to see my harvest sources on the production site, so that data.gov will aggregate all the data required. 

## Acceptance criteria
- [x] When I go to the production site
- [x] And I go to https://catalog-next.data.gov/harvest
- [x] Then I see the harvest sources listed in the source type tab in this document are imported: https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit#gid=264788117

**Comment by thejuliekramer** [comment]
This is ready for QA - you can see new datasets here https://catalog-next.data.gov/dataset

and harvest sources here https://catalog-next.data.gov/harvest

We will create new issues for specific issues with harvesting if they come up

**Comment by hkdctol** [comment]
@thejuliekramer is it ready? I get an error when I go to that /dataset URL.

**Comment by thejuliekramer** [comment]
@hkdctol there was an issue with the load balancer that I fixed - it should be working now. I also split harvesting the datasets into a different ticket so its less confusing - this ticket should just be for harvest sources imported

**Comment by hkdctol** [comment]
Looks like the harvest sources all got imported.
