### ISSUE TITLE
Edit existing dataset resources using new form

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#502]
## User Story

As a data publisher, I want to use the new inventory metadata form to update/manage dataset resources so that i benefit from a consistent design/workflow and also enjoy the improved user experience when editing dataset resources.

## Acceptance Criteria
- [x] When i edit an existing dataset, i am taken to the new metadata form 
- [x] when i click on the `Resource Upload` tab on the new metadata form,
- [x] then i am able to provide input to add a new resource to the pre-existing resources 
- [x] i am also able to update existing resources
- [x] and also able to update existing resource URL 
- [x] and also to remove/delete a resource from the pre-existing resources.
- [x] when i click on `Finish and Publish`, then the updated dataset and it's updated resources are successfully saved and i am returned to the `/datasets` page

## Details / tasks/notes
- [x] the design for the editing of dataset resources **should also** handle a case where the data publisher wants to **remove**(not just edit) a resource that was previously uploaded/added
- [x] There should be some space before the Resource table to establish where the Resource table begin
- [x] There should be some space and a horizontal rule after the Resource table. To separate the Resource table from the other content
- [x] The table has a title which is: “Resource saved: (n resources saved in total)”. Where n = total number of resources available.
- [x] The “Edit” button should come before the “Delete” button
- [x] When no resource has been included at all, then the Resource table and the horizontal rule should be absent
- [ ] Remove second sentence in the success message for saved/edited resoruces
- [ ] Number of resources in success message should be equal to the total number of resources (including saved and edited) for the given dataset
- [ ] Resource URL should be editable as well

**Comment by kimwdavidson** [comment]
duplicate. closing

**Comment by cmugisha** [comment]
@gujacq What's the estimate on this ticket?

**Comment by gujacq** [comment]
Here is the design with two solutions. You can view it under the green section - Resource Upload > PREFERRED STATE
[NEW - with ability to edit and delete on the page]: https://www.figma.com/file/klRVVF5U6fFmDbiu3s6L3g/Metadata-Form?node-id=648%3A1297

Attached are the designs as well. The main difference is where the resources show up (above or below the resource upload fields)

![saves  resource upload 1](https://user-images.githubusercontent.com/33872753/101083900-cf931980-3572-11eb-90cf-ac7034bfe93f.png)
![saves  resource upload 2](https://user-images.githubusercontent.com/33872753/101083901-d0c44680-3572-11eb-89ef-43b69f5233ac.png)

**Comment by cmugisha** [comment]
@gujacq Hyon likes the option where the edit button is at the top of the form.

**Comment by kmanaseryan** [comment]
## Analysis for Edit and Delete actions button

*Edit process*
- When we click Edit button regardless what is in the current form field values, the form should be pre-populated with the given resource values.  
- Update the resource [resource_update endpoint](https://docs.ckan.org/en/ckan-2.2/api.html#ckan.logic.action.update.resource_update). The resource `id` should be provided. Every resource in resource array of dataset has an ID, so it can be retrieved from there. 
- Change the "Save and add another" to "Save Updates"
- Disable it while the resource update request is being processed 
- Once the update is done, empty the form and update the resources array of the dataset. 

*Delete process*
- When we click Delete button we should delete the resource using [resource_delete](https://docs.ckan.org/en/ckan-2.2/api.html#ckan.logic.action.delete.resource_delete) endpoint. 
- Update the resources array of the dataset
- Update the number of resource mentioned in Resource table title.

**Comment by hkdctol** [comment]
Can someone else try to see if deleting an existing resource works? That's the one function I can't seem to do. The delete button is there next to list of resources, but nothing happens.

**Comment by hkdctol** [comment]
![inventory delete](https://user-images.githubusercontent.com/3236989/104753724-616f7400-5726-11eb-95a6-4356df24db70.png)
Tried to delete existing resource in inventory sandbox -- both the delete and edit buttons were unresponsive

**Comment by osahon-okungbowa** [comment]
@hkdctol i see you're doing your QA on inventory-next.
the feature should be tested in inventory sandbox i.e. https://inventory.sandbox.datagov.us/
let me know if this helps

Cc @cmugisha @kimwdavidson

**Comment by hkdctol** [comment]
@osahon-okungbowa thanks for the info--was able to sign in and confirm the deletion works.
