### ISSUE TITLE
Design: Interim option to return to inventory app from form

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#503]
## User Story

As a data publisher, I want to be able to return to the inventory application from the new metadata form, so that I can access other functions I might need. 

## Acceptance Criteria
- [ ] 

## Details / tasks
Currently, once a user clicks to add a dataset, the only way to get back to the application is to use the back button, which is unintuitive and can be unpredictable. In the future, we may want to better integrate experiences, but for now, users just need a way to get back to the inventory application/

**Comment by gujacq** [comment]
Design is here, under "Back/edit flows" label: https://www.figma.com/file/klRVVF5U6fFmDbiu3s6L3g/Metadata-Form?node-id=648%3A1297

Here's the screenshot, essentially, there should be a back to dashboard link above each headline

<img width="812" alt="Screen Shot 2020-11-20 at 11 21 35 AM" src="https://user-images.githubusercontent.com/33872753/99829990-a742fe00-2b22-11eb-85b0-4631092f8a56.png">

**Comment by hkdctol** [comment]
Fine by me. @adborden agree?

**Comment by hkdctol** [comment]
This mockup is fine.
