### ISSUE TITLE
Design: Option to delete dataset with new dataset form implemented

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#504]
## User Story

As a data publisher, I want to be able to delete datasets, so that I can keep my catalog up to date. 

## Acceptance Criteria
- Mockups are approved by data.gov team

## Details / tasks
Currently, users can go to an existing dataset and click "manage," which takes them to the legacy editing form. We'd like users to be able to edit using the new form, but that form currently has no option to delete the dataset. 

Users should be able to delete either from the editing interface or to delete from the current inventory application

**Comment by gujacq** [comment]
Designs can be seen here under the "Back/edit flows NEW 1 & 2": https://www.figma.com/file/klRVVF5U6fFmDbiu3s6L3g/Metadata-Form?node-id=648%3A1297

There are two solutions:

1 - Nesting edit and delete under a manage dropdown button

<img width="1035" alt="Screen Shot 2020-11-20 at 11 41 39 AM" src="https://user-images.githubusercontent.com/33872753/99832049-9e076080-2b25-11eb-9d4d-0a55a37c10f0.png">
<img width="1025" alt="Screen Shot 2020-11-20 at 11 41 46 AM" src="https://user-images.githubusercontent.com/33872753/99832058-a19ae780-2b25-11eb-9a8a-82306de73e7b.png">


2 - Having both buttons displayed
<img width="1034" alt="Screen Shot 2020-11-20 at 11 41 53 AM" src="https://user-images.githubusercontent.com/33872753/99832119-b5464e00-2b25-11eb-8a20-eef8aab15e0c.png">

I think the second direction is more straight-foward and therefore preferred, though I don't have any user studies to back that up.

**Comment by hkdctol** [comment]
I like option 2.

**Comment by hkdctol** [comment]
Agreement on option 2 with buttons. Can the delete button be highlighted/colored red?
