### ISSUE TITLE
CSW for catalog-next at production environment

### ISSUE THREAD

**Issue by avdata99** [GSA/datagov-ckan-multi#506]
## User Story

As a geospatial user, I want the [CSW](https://github.com/GSA/pycsw) ([Catalog Service for Web](https://en.wikipedia.org/wiki/Catalogue_Service_for_the_Web)) app enabled for catalog-next in the production environment so that I can access the catalog-next datasets in a common geospatial format as I can today on catalog.data.gov.

## Acceptance Criteria
- [ ] WHEN I browse https://catalog-next.data.gov/csw?service=CSW&version=2.0.2&request=GetCapabilities
  THEN I see the XML response describing CSW's capabilities ([similar to this](https://catalog.data.gov/csw?service=CSW&version=2.0.2&request=GetCapabilities))

## Details / tasks
- [ ] add catalog-next production hosts to pycsw Ansible groups
- [ ] run the pycsw.yml playbook in production and debug/document any errors
- [ ] manually run the ckan-load job on the pycsw-worker
- [ ] create GH issues to address any errors or followup tasks

**Comment by kimwdavidson** [comment]
Aaron to take a peek, then unassign himself if it's ready for work

**Comment by avdata99** [comment]
The production hosts file was modified to add `pycsw`: https://github.com/GSA/datagov-deploy/blob/develop/ansible/inventories/production/hosts#L101-L124

**Comment by avdata99** [comment]
After the last deploy to production is working. 
Moving to QA

![image](https://user-images.githubusercontent.com/3237309/101909255-f9b09100-3b9b-11eb-8792-a9a8c1b47566.png)

![image](https://user-images.githubusercontent.com/3237309/101909279-02a16280-3b9c-11eb-8fc6-4e79939f0df6.png)

**Comment by adborden** [comment]
https://catalog-next.data.gov/csw?service=CSW&version=2.0.2&request=GetCapabilities looks good.
