### ISSUE TITLE
Task: Check QA scenarios on catalog-next.data.gov

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#512]
## User Story

In order to ensure shipping catalog-next.data.gov has no blockers, data.gov users want a manual check of our [QA scenarios](https://docs.google.com/document/d/1il7Xo3tvBl5hlpQZvkioGDAJx6kWN4cd55JuXL8-iuw/edit). 

## Details / tasks
https://docs.google.com/document/d/1il7Xo3tvBl5hlpQZvkioGDAJx6kWN4cd55JuXL8-iuw/edit
Check each QA scenario and create blocker issues for any outstanding work.

**Comment by cmugisha** [comment]
@adborden  What's the estimate on this?

**Comment by adborden** [comment]
Half a day of work.

**Comment by adborden** [comment]
This work is complete. I've opened a few blockers and noted them in the [document](https://docs.google.com/document/d/1il7Xo3tvBl5hlpQZvkioGDAJx6kWN4cd55JuXL8-iuw/edit#). A highlight indicate the scenario could not be completed successfully.
