### ISSUE TITLE
Return to inventory

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#516]
## User Story
As a data publisher, I want to be able to return to the inventory application from the new metadata form, so that I can access other functions I might need.

## Implementation notes
Follow specs in #503 

## Acceptance Criteria
- [ ] When I go to /datasets
- [ ] And I click to add a dataset and the new form loads
- [ ] Then I should see an option to return to the dashboard matching the mockups in #503 
- [ ] When I click on that link
- [ ] Then I should return to the /datasets page
- [ ] Same should be true of starting at an organization page

**Comment by hkdctol** [comment]
@osahon-okungbowa should I be seeing the return to dashboard option on inventory production?

**Comment by osahon-okungbowa** [comment]
@hkdctol for now, this should only be visible on inventory sandbox - until a manual deploy to production is done by Aaron or the REI team

**Comment by hkdctol** [comment]
Confirmed this on sandbox.
<img width="1440" alt="back to dashboard" src="https://user-images.githubusercontent.com/3236989/100808888-02b69b00-3403-11eb-84ad-d818022ffed2.png">
