### ISSUE TITLE
/harvest page takes 30+ seconds to load on catalog-next

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#518]
```
$ time curl -s 'https://catalog-next.data.gov/harvest' > /dev/null

real    0m33.042s
user    0m0.015s
sys     0m0.014s
```

## How to reproduce

1. https://catalog-next.data.gov/harvest

## Expected behavior
/harvest page loads within a few seconds

## Actual behavior

/harvest page takes over 30 seconds to load.

**Comment by adborden** [comment]
This looks like https://github.com/GSA/datagov-ckan-multi/issues/403, but the changes to ckanext-harvest should've already been applied as part of the database initialization. @avdata99 can you check?

**Comment by cmugisha** [comment]
@avdata99  What's the estimate on this?

**Comment by thejuliekramer** [comment]
Results of sql test in production:
<img width="1307" alt="Screen Shot 2020-11-25 at 10 38 35 AM" src="https://user-images.githubusercontent.com/7378770/100256607-9ae7e800-2f0a-11eb-89ea-6d4b79609ea5.png">

Results of solr tests in production:
<img width="686" alt="Screen Shot 2020-11-25 at 10 39 41 AM" src="https://user-images.githubusercontent.com/7378770/100256649-a4715000-2f0a-11eb-9fd9-43773b6b6c84.png">

**Comment by avdata99** [comment]
The test looks good.
When we go to /harvest we make one extra solr query per each harvest sources

It takes 1'-2' each so for the first 20 we need at least 20 seconds

![image](https://user-images.githubusercontent.com/3237309/100257731-03dc5980-2f25-11eb-9aa4-07479624bf06.png)

**Comment by avdata99** [comment]
@thejuliekramer, we [added weeks ago](https://github.com/GSA/ckanext-datagovcatalog/blob/master/ckanext/datagovcatalog/plugin.py#L47:L47) the `include_tracking` param  in `before_view`

Considering that this could require more time (it run an extra `package_show` call per each harvest source (or dataset) in a list) I allow to stop doing this with the config `ckanext.datagovcatalog.add_packages_tracking_info`.

If you have some time: Can you add `ckanext.datagovcatalog.add_packages_tracking_info: false`  and check if this page continues using >30s?

I will add the related queries in our [data_test tool](https://github.com/GSA/catalog.data.gov/tree/sql_test_tool/tools/data-tests)

**Comment by avdata99** [comment]
This happens for datasets and harvest sources (we have and extra SOLR search to get the tracking information for each dataset/source)
Local environment logs

<pre>
<b>going to /harvest (just 3 harvest sources exists)</b>
solr_1        | 133969 INFO  (qtp1989972246-14) [   x:ckan] o.a.s.c.S.Request [ckan]  webapp=/solr path=/select 
params={facet.limit=50&q=*:*&facet.field=organization_type&facet.field=frequency&facet.field=source_type&facet.field=organization&fl=id+validated_data_dict&start=0&sort=views_recent+desc&fq=%2Bdataset_type:harvest+-collection_package_id:[""+TO+*]&fq=%2Bsite_id:"default"&fq=%2Bstate:active&facet.mincount=1&rows=21&facet=true&wt=json} 
hits=3 status=0 <b>QTime=84</b>

solr_1        | 134044 INFO  (qtp1989972246-15) [   x:ckan] o.a.s.c.S.Request [ckan]  webapp=/solr path=/select 
params={q=name:"1122fef6-f78a-4b04-8419-5753c57aaab4"+OR+id:"1122fef6-f78a-4b04-8419-5753c57aaab4"&fq=site_id:"default"&rows=1&wt=json} 
hits=1 status=0 <b>QTime=18</b>

solr_1        | 134131 INFO  (qtp1989972246-14) [   x:ckan] o.a.s.c.S.Request [ckan]  webapp=/solr path=/select 
params={q=name:"4753093b-4f65-4a49-9515-b6cc9756a8d6"+OR+id:"4753093b-4f65-4a49-9515-b6cc9756a8d6"&fq=site_id:"default"&rows=1&wt=json} 
hits=1 status=0 <b>QTime=2</b>

solr_1        | 134191 INFO  (qtp1989972246-15) [   x:ckan] o.a.s.c.S.Request [ckan]  webapp=/solr path=/select 
params={q=name:"d673f114-b79f-4f63-8aed-ac42081042d3"+OR+id:"d673f114-b79f-4f63-8aed-ac42081042d3"&fq=site_id:"default"&rows=1&wt=json} 
hits=1 status=0 <b>QTime=1</b>


<b>going to /dataset (just the first 3)</b>
solr_1        | 226710 INFO  (qtp1989972246-13) [   x:ckan] o.a.s.c.S.Request [ckan]  webapp=/solr path=/select 
params={facet.limit=50&q=*:*&facet.field=groups&facet.field=vocab_category_all&facet.field=metadata_type&facet.field=tags&facet.field=res_format&facet.field=organization_type&facet.field=organization&facet.field=publisher&facet.field=bureauCode&fl=id+validated_data_dict&start=0&sort=views_recent+desc&fq=+-dataset_type:harvest+-collection_package_id:[""+TO+*]&fq=%2Bsite_id:"default"&fq=%2Bstate:active&facet.mincount=1&rows=21&facet=true&wt=json} 
hits=20 status=0 <b>QTime=19</b>

solr_1        | 226732 INFO  (qtp1989972246-19) [   x:ckan] o.a.s.c.S.Request [ckan]  webapp=/solr path=/select 
params={q=name:"33f0ab56-0304-4afc-b179-f908b64439eb"+OR+id:"33f0ab56-0304-4afc-b179-f908b64439eb"&fq=site_id:"default"&rows=1&wt=json} 
hits=1 status=0 <b>QTime=1</b>

solr_1        | 226775 INFO  (qtp1989972246-13) [   x:ckan] o.a.s.c.S.Request [ckan]  webapp=/solr path=/select 
params={q=name:"941b1cd9-f9df-43b7-84dc-bf26c62646d7"+OR+id:"941b1cd9-f9df-43b7-84dc-bf26c62646d7"&fq=site_id:"default"&rows=1&wt=json} 
hits=1 status=0 <b>QTime=1</b>

solr_1        | 226827 INFO  (qtp1989972246-16) [   x:ckan] o.a.s.c.S.Request [ckan]  webapp=/solr path=/select 
params={q=name:"d9824b9f-f6fb-4acf-86d8-9915eb1c8d07"+OR+id:"d9824b9f-f6fb-4acf-86d8-9915eb1c8d07"&fq=site_id:"default"&rows=1&wt=json} 
hits=1 status=0 <b>QTime=2</b>

</pre>

**Comment by avdata99** [comment]
@adborden our [new test tool](https://github.com/GSA/catalog.data.gov/pull/170) allow us to check production.
All DB and SOLR queries seem fine.
I think [this PR](https://github.com/GSA/ckanext-datagovcatalog/pull/22) will fix the slowness at `/harvest`
Still not sure why `package_show` for harvest sources require more time than for datasets

**Comment by avdata99** [comment]
Now:

<pre>
time curl -s 'https://catalog-next.data.gov/harvest' > /dev/null

real	<b>0m1,593s</b>
user	0m0,069s
sys	0m0,008s
</pre>

**Comment by adborden** [comment]
lgtm
