### ISSUE TITLE
Federal datasets are marked as non-federal

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#519]
GSA dataset is marked a s non-federal dataset.

<img width="942" alt="Screen Shot 2020-11-20 at 3 16 32 PM" src="https://user-images.githubusercontent.com/509703/99858943-817a2100-2b43-11eb-871b-390866af8cfe.png">

## How to reproduce

1. https://catalog-next.data.gov/dataset/per-diem-reimbursement-rates-api

## Expected behavior

Dataset page does **not** have the non-federal treatment.

## Actual behavior

Non-federal banner and access & use information is displayed for a federal dataset.

**Comment by hkdctol** [comment]
@avdata99 @thejuliekramer  does this ticket need spec? It seemed like the federal ones had non-federal and non-federal was showing no banner.

**Comment by avdata99** [comment]
I think this issue just needs an estimate (I just added).

I checked the data we use to import this source: https://catalog.data.gov/api/3/action/harvest_source_show?name_or_id=gsa-json
There is no data saying this is non-federal so it must be treated as federal (default)

The error is clear, we don't need more specs @hkdctol

**Comment by avdata99** [comment]
If the `organization_type` is then the flag _This is a Non-Federal ..._ [will be shown](https://github.com/GSA/ckanext-datagovtheme/blob/master/ckanext/datagovtheme/templates/package/read_base.html#L28-L29)

The organization is well imported so this requires more analysis
![image](https://user-images.githubusercontent.com/3237309/101034129-212eaa80-3559-11eb-881a-e83c52b0d36c.png)
