### ISSUE TITLE
package_search over collection member datasets shows only 27k

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#520]
catalog-classic shows ~4M
```
$ curl -s 'https://catalog.data.gov/api/action/package_search?fq=collection_package_id:*&rows=0' | jq .result.count
4190268
```

catalog-next shows 27K
```
$ curl -s 'https://catalog-next.data.gov/api/action/package_search?fq=collection_package_id:*&rows=0' | jq .result.count
27786
```

## How to reproduce

1. https://catalog-next.data.gov/api/action/package_search?fq=collection_package_id:*&rows=0

## Expected behavior

Shows all datasets, including collection members.

## Actual behavior

Showing only 27k datasets.

**Comment by thejuliekramer** [comment]
This code is altering the package search https://github.com/GSA/ckan/blob/datagov/ckan/lib/dictization/model_dictize.py#L348 which does not exist in catalog next

**Comment by thejuliekramer** [comment]
```
curl -s 'https://catalog.sandbox.datagov.us/api/action/package_search?fq=collection_package_id:*&rows=0' | jq .result.count
155

```

```
curl -s 'https://catalog-next.sandbox.datagov.us/api/action/package_search?fq=collection_package_id:*&rows=0' | jq .result.count
1403
```

**Comment by thejuliekramer** [comment]
@adborden I am wondering what we want the final result of this query to be - this query ignores datasets that are not part of a collection - do we want to get all datasets including children or just datasets that are part of a collection?

**Comment by thejuliekramer** [comment]
Testing this query locally I can see that we are counting the number of children dataset of collection sources correctly but we are not counting non-collection datasets at all.

There are two harvest sources here one is not a collection and the other is a collection.

<img width="677" alt="Screen Shot 2020-12-15 at 10 34 06 AM" src="https://user-images.githubusercontent.com/7378770/102244528-08f84d00-3ec2-11eb-948f-212bb8afc947.png">

The non collection harvest source does not get counted by this query because the datasets don't have a collection package id.

The collection harvest source does get counted - but only the children because only the children have a collection_package_id

<img width="721" alt="Screen Shot 2020-12-15 at 10 33 49 AM" src="https://user-images.githubusercontent.com/7378770/102244580-16add280-3ec2-11eb-988c-4bbd236b8c45.png">

**Comment by thejuliekramer** [comment]
Is the purpose of this query to count all datasets including non collection datasets? If so we need to update this to fetch this number in a different way than using the collection_package_id - but I think the main discrepancy in the numbers is just that there are a lot older collection datasets that are no longer harvesting. The new amount this query returns is 95k

<img width="704" alt="Screen Shot 2020-12-15 at 10 45 01 AM" src="https://user-images.githubusercontent.com/7378770/102245010-a5225400-3ec2-11eb-9e2d-29dbd20a34c4.png">

**Comment by adborden** [comment]
@thejuliekramer this query should show you all the collections and their counts.

    $ curl 'https://catalog.data.gov/api/action/package_search?fq=collection_package_id:*&facet.field=\["collection_package_id"\]&facet.limit=-1&facet.mincount=2&facet.sort=count&rows=0'


I could not get the `facet.sort` parameter to work 🤷

**Comment by thejuliekramer** [comment]
<img width="993" alt="Screen Shot 2020-12-16 at 12 00 58 PM" src="https://user-images.githubusercontent.com/7378770/102390904-9d35e300-3f9a-11eb-95b2-d39e38cb23aa.png">

**Comment by thejuliekramer** [comment]
Here is the list of datasets with the biggest collection - id is the parent dataset id
[list biggest collections.txt](https://github.com/GSA/datagov-ckan-multi/files/5704900/list.biggest.collections.txt)

**Comment by avdata99** [comment]
Other big collections

|Collection | Children WEB | Children DB | Harvest Source | 
|------------------|-----------------------|------------------------|-----------|
| [Lidar Point Cloud - USGS National Map 3DEP Downloadable Data Collection](https://catalog.data.gov/dataset?collection_package_id=55e67773-09ac-459c-8be3-3fb2750ddc9b)| 1,139,371 | 1,126,190 | [USGS Lidar Point Cloud LAS Harvest Source](https://catalog.data.gov/harvest/a2562cf8-3758-4dfd-bd42-746fc62be645) |
| [USGS public distribution of FSA 10:1 NAIP Imagery Downloadable Data Collection from The National Map](https://catalog.data.gov/dataset?collection_package_id=54d3465c-ae77-4da1-a9d0-ed9b9ce77440) | 218,702 | 368,310 | [FSA 10:1 NAIP Imagery Collection](https://catalog.data.gov/harvest/f2089adb-ae87-450c-bf22-e7fb0707a419) |
| PKG ID 949b7c71-6913-45f1-85b9-2a4a3dd6e2bc (maybe deleted or not published)  | ? | 352,778 |  | 
| [USGS Historical Topographic Map Collection](https://catalog.data.gov/dataset?collection_package_id=640e11ae-cc27-49cb-b06f-bb0df1d47def) | <h2 style=“color:red;”> 84 ?</h2> | 341,816 | [USGS Historical Topographic Maps](https://catalog.data.gov/harvest/66924856-7b2b-4753-b779-08ce4f006013) |

**Comment by thejuliekramer** [comment]
I can't get to the harvest source links in catalog to get the URL's and I also don't see them in the [spreadsheet](https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit#gid=263740072) we've been using to track progress. @hkdctol are you able to reach out to get update harvest source urls for these big ones?

**Comment by thejuliekramer** [comment]
@adborden I think this ticket is done for now we are counting the number correctly we just no longer have access to these big sources. If we get new harvest source info we can add them to catalog next

**Comment by thejuliekramer** [comment]
Added a the information here to this issue so we don't lose track https://github.com/GSA/datagov-ckan-multi/issues/510

**Comment by hkdctol** [comment]
@thejuliekramer the Original Product Resolution one is confirmed by USGS. Tracking down the details on the others.

**Comment by thejuliekramer** [comment]
Harvest source name - usgs-ned-original-product-resolution-opr-downloadable-data-collection

**Comment by thejuliekramer** [comment]
@hkdctol I don't see the original product resolution one in this spreadsheet - did they confirm it via email?

**Comment by thejuliekramer** [comment]
I updated the main [Harvest Source Progress](https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit?ts=5e4177f8#gid=263740072) sheet with these large harvest sources that are causing the discrepancy - they have not been imported yet because I am getting a timeout from catalog when trying to import that harvest source - we will manually add these harvest sources when we are able to log in to production catalog-next
