### ISSUE TITLE
catalog-next group counts are not with 10% of catalog-classic

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#521]
As part of our QA scenarios, our [7 groups on catalog-next](https://catalog-next.data.gov/group) should contain the same number of datasets as [catalog-classic](https://catalog.data.gov/group), within 10%.

Group | catalog-next | catalog-classic
------ | ---------------- | ------------
Agriculture | 4 | 18
Climate | 277 | 462
Energy | 72 | 180
Local Government | N/A | N/A
Maritime | 10 | 15
Ocean | 9 | 43
Older Adults Health | 214 | 249

## How to reproduce

1. Description of steps to reproduce the issue.

## Expected behavior

catalog-next group dataset counts is within 10% of catalog-classic, or we know why there is a discrepancy.

## Actual behavior

Groups are missing datasets.

**Comment by thejuliekramer** [comment]
@adborden I was researching the cause for this and it looks like all of the datasets in catalog that are properly linked to a harvest source are showing up in our groups in catalog next, but if the dataset is an orphan we don't have a way to import it from catalog. For example this dataset https://catalog.data.gov/dataset/internet-weather-source in the Agriculture group does not have any link to a harvest source in catalog so it is not importing to catalog-next. All datasets that could be imported are properly tagged with the group in catalog-next

**Comment by adborden** [comment]
Okay, that's good enough for me.
