### ISSUE TITLE
Discovery: submit an API or indirect download resource

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#524]
## User Story

As a data manager, I want a resource upload UI that simplifies some special case resources so that I can provide high quality metadata to users.

## Acceptance Criteria
- [ ] i have a clear understanding of what is required for implementing this
- [ ] create a new issue to handle the implementation of this issue with detailed tasks

## Details / tasks
There are some special cases for resource upload in Inventory. Resources can be a direct download link, an API, or an indirect download link. "Upload data" is a special case of direct download link where the data needs to be uploaded for hosting.

### direct download link

Uses the [downloadURL](https://resources.data.gov/resources/dcat-us/#distribution-downloadURL) field.

An HTML web page is not a direct download link.

### API

Uses the [accessURL](https://resources.data.gov/resources/dcat-us/#distribution-accessURL) field and a [format](https://resources.data.gov/resources/dcat-us/#distribution-format) of `API`.

### indirect download link

Is a resource that is not directly downloadable, like an HTML website that might contain data or tables or a contact form for restricted access.

Uses the [accessURL](https://resources.data.gov/resources/dcat-us/#distribution-accessURL) field.

**Comment by anuveyatsu** [comment]
## Current state

We have 2 ways of adding data to a resource:

* **Upload data** - upload a file from local disk to the remote storage so it can be served from there.
* **Link to data** - provide a link to a file. Normally, this is a "direct" download URL (eg, `https:/www.example.com/data.csv`).

![](https://i.imgur.com/sdSEQ1G.png)

Note that both "Upload data" and "Link to data" options don't follow DCAT spec. It saves URLs in `url` property. For example:

https://inventory.sandbox.datagov.us/api/3/action/package_show?id=testing-spec-chars

It looks like we need to:

* Replace "Link to data" with "Direct download link"
* Refactor "Upload data" so it follows DCAT spec

## New ways of adding data

Basically, we will add 3 new buttons next to existing ones:

* **Direct download link** - this looks similar to "link to data" but uses different property in metadata (`distribution → downloadURL`).
  * input element
  * only check if valid URL
  * add a help text explaining what value user should add here
  * on submit, the value is saved under `distribution → downloadURL`
* **API**
  * input element
  * only check if valid URL
  * a help text with explanation
  * on submit, the value is saved under `distribution → accessURL` and `format` is `API` by default (should user be able to change format?)
* **Indirect download link** - 
  * input element
  * only check if valid URL
  * a help text with explanation
  * on submit, the value is saved under `distribution → accessURL`

On all options, user still has existing metadata options to add/edit: `name`, `description`, `mediaType`, `format`:

![](https://i.imgur.com/gSy6Psx.png)

**Comment by anuveyatsu** [comment]
Based on analysis we've done here, we've created this issue for implementation work:

https://app.zenhub.com/workspaces/datagov-multi-tenant-ckan-5cf12b601437ff1e943f0aa2/issues/gsa/datagov-ckan-multi/529

**Comment by adborden** [comment]
> Note that both "Upload data" and "Link to data" options don't follow DCAT spec. It saves URLs in `url` property. For example:
> 
> https://inventory.sandbox.datagov.us/api/3/action/package_show?id=testing-spec-chars
> 
> It looks like we need to:
> 
> * Replace "Link to data" with "Direct download link"
> * Refactor "Upload data" so it follows DCAT spec

@anuveyatsu can you clarify? Within CKAN, the data doesn't follow DCAT-US. It's only on export that the CKAN package representation is converted to DCAT-US. When I export GSA's data.json and look for the "Testing spec chars" dataset, this is the DCAT-US I'm seeing which looks correct. I can see the distribution and downloadUrl.

```
$ cat ~/Downloads/redacted/data.json | jq '.dataset[] | select(.title == "Testing spec chars")'
{
  "@type": "dcat:Dataset",
  "title": "Testing spec chars",
  "description": "Dataset desc with exact one &",
  "modified": "2020-11-07T08:28:15.814Z",
  "accessLevel": "public",
  "identifier": "765432123",
  "license": "https://www.usa.gov/publicdomain/label/1.0/",
  "rights": "true",
  "publisher": {
    "@type": "org:Organization",
    "name": "ATF - Bureau of Alcohol, Tobacco, Firearms and Explosives"
  },
  "contactPoint": {
    "@type": "vcard:Contact",
    "fn": "Karlen",
    "hasEmail": "mailto:foo@foo.com"
  },
  "distribution": [
    {
      "@type": "dcat:Distribution",
      "mediaType": "text/csv",
      "title": "sample.csv",
      "description": "Resource desc with exact TWO &&",
      "downloadURL": "https://inventory.sandbox.datagov.us/dataset/a6c07528-068a-4478-b3be-b590992b4ba9/resource/b8760203-3b55-4d1e-8424-7d44a8b444c6/download/sample.csv"
    }
  ],
  "keyword": [
    "tag"
  ],
  "bureauCode": [
    "015:11"
  ],
  "programCode": [
    "015:001"
  ],
  "language": [
    "en-US"
  ]
}
```

**Comment by adborden** [comment]
ckanext-datajson is what handles the dcat-us export and it is currently using `resource_type` to [figure out how to map CKAN's `url` field](https://github.com/GSA/ckanext-datajson/blob/8ef33f9fc1e6ecba0f53c2da3f26caacffc20d52/ckanext/datajson/package2pod.py#L421-L443). So if you want to keep the existing implementation (we don't have to) we just need the form UI to set the correct resource type.

FWIW, the old for implemented this with [4 separate buttons](https://github.com/GSA/USMetadata/blob/d3a138851f04a0d1aa5bb753452338299c8bf788/ckanext/usmetadata/templates/package/snippets/resource_form.html#L9-L23). I don't think we really want that implementation, but leaving it here for reference.

**Comment by anuveyatsu** [comment]
@adborden this is really useful that you've clarified. I was wondering if we should follow DCAT-US standard and that lots of other fields are broken. It's now clear :+1:

Looking at the old metadata form, I think we can have just 3 buttons as "Link to data" and "Direct download URL" seems to be the same thing. WDYT?

**Comment by adborden** [comment]
I think "Direct download link" is a better name than "Link to data" but what happens to the "Upload data" case? Would that be a fourth button?

@hkdctol I'm not sure how folks responded to the old form with the four buttons. Did users find it confusing? I'm a bit weary about going with the button design without a little research to back it up, but I also don't want our form to encourage folks to misuse the downloadUrl field.

**Comment by adborden** [comment]
This is what the old form looked like, with 4 radio buttons. I don't think this really communicates why you would choose one or the other. For example, when should I use "Access URL" vs "Link to a file"?
![screencapture-inventory-sandbox-datagov-us-dataset-new-resource-test-adb-1-2020-12-14-10_44_11](https://user-images.githubusercontent.com/509703/102122682-b43dcf00-3dfa-11eb-8a47-3ce699771a47.png)

**Comment by kimwdavidson** [comment]
Buttons and help text: 

Link to a file: Provide a direct download link to a file
Upload a file: Upload a file from your computer
Link to an API: Provide a link to access a dataset via API
Access URL: Provide to access to a resource that is not directly downloadable, like an html website

**Comment by cmugisha** [comment]
@gujacq Did Kim answer your questions? If not, we're meeting for scrum tomorrow and can get more support. Please remember to estimate and move this to In Progress when you're ready to start working on it.

**Comment by gujacq** [comment]
I think I understand. @adborden can you confirm what Kim posted above is the correct name for each button and accurate help text?

**Comment by gujacq** [comment]
FYI for @kimwdavidson and @adborden I'm changing the access URL to: "Provide a **link** to a resource that is not directly downloadable, like an html website" since I think that's more direct than "access".

**Comment by gujacq** [comment]
Designs are here under the green "Resource Upload" section: https://www.figma.com/file/klRVVF5U6fFmDbiu3s6L3g/Metadata-Form?node-id=1545%3A1490

Here are pngs:

1 - Updated with the new labels and help text. The format is now radio buttons
![resource upload - updated](https://user-images.githubusercontent.com/33872753/102394202-03246980-3f9f-11eb-8923-7c8fa10a886a.png)

2 - If users choose either link to file, link to an API, or access URL they get a field to enter the URL with help text 
![resource upload - updated url](https://user-images.githubusercontent.com/33872753/102394246-146d7600-3f9f-11eb-99f1-cf781fb4e5c3.png)

3 - If users choose "upload a file", they get an upload button to choose a file to upload
![resource upload - updated url](https://user-images.githubusercontent.com/33872753/102394435-5eeef280-3f9f-11eb-9170-31a522c86a54.png)
