### ISSUE TITLE
Support "Other" option for Data Publishing Frequency

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#525]
## User Story

As a data manager, I want an Other option for [Data Publishing Frequency](https://resources.data.gov/resources/dcat-us/#accrualPeriodicity) so that I have a simple list of options and can specify a custom recurrence when necessary.

## Acceptance Criteria
- [x] WHEN I view the Data Publishing Frequency field
  THEN I see options:
  - Irregular/As needed
  - Continuously
  - Daily
  - Weekly
  - Monthly
  - Yearly
  - Other
- [x] WHEN I select "Daily" for modified
  THEN the dataset is saved with the value `R/P1D`
- [x] WHEN I select "Irregular/As needed"
  THEN the dataset is saved with the value `irregular`.
- [x] WHEN I select "Other"
  THEN I am presented with the help text referencing ISO 8601 with a link to the wikipedia page and examples of recurrence periods I can use
  AND a text input is available for me to enter a custom recurrence period
- [x] GIVEN I select "Other"
  AND I type "monthly"
  WHEN I click "Save"
  THEN I am presented an error that the modified field is not formatted as a proper ISO 8601 timestamp.

## Details / tasks
 - [x] Similar to https://github.com/GSA/datagov-ckan-multi/issues/482 except that "As Needed" should save as the value `irregular`.
 - [x] Remove Update Frequency field
 - [x] Update modified field so that it will be set to current timestamp on update. 
 - [x] Change the validation in USMetadata so that it will accept ISO 8601 duration formats

**Comment by adborden** [comment]
🤦  I screwed this up. Originally, we were going to make the [modified](https://github.com/GSA/datagov-ckan-multi/issues/482) field machine generated (a timestamp when the metadata was last edited). Then I confused modified (again), with accrualPeriodicity (Data Publishing Frequency), and we added the modified field back to the form.

I'm pretty sure that what we really want is to update Data Publishing Frequency similar to https://github.com/GSA/datagov-ckan-multi/issues/482. Then we should remove Update Frequency (modified) from the form and it will always be a machine generated timestamp.

Does that sound correct to everyone? Hopefully this is a small level of effort since we've done the bulk of the work in #482.

**Comment by osahon-okungbowa** [comment]
@kmanaseryan noted that: for this issue to be completed, the server-side validation has to be updated to allow this field store iso timestamp periods. @anuveyatsu is pairing with Karlen to get this resolved.
The inclusion of server-side validation modification means the completion of this issue will take longer than initially estimated. This is now estimated to be about 5 story points

**Comment by cmugisha** [comment]
@kmanaseryan @anuveyatsu @osahon-okungbowa Is this ready to be moved to QA?

**Comment by osahon-okungbowa** [comment]
@cmugisha no, not yet. This was one of the issues Aaron helped unblock yesterday during scrum. So Karlen is still working

**Comment by cmugisha** [comment]
@osahon-okungbowa What's the status on this? It was estimated for a half day but has been in progress for a while?

**Comment by osahon-okungbowa** [comment]
@cmugisha  work on this ticket was blocked by the need to update a dependency (USMetadata data extension). This was finally unblocked last Friday. So, work on this ticket was finalised today and the PR is awaiting review and deployment (this will be done early tomorrow).
