### ISSUE TITLE
Change themes field to a geospatial or not selector

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#526]
## Notes
Currently, themes field is unclear and is unuseful for categorizing data if misused. Change themes field to 

"My dataset is a geospatial dataset" with Yes/No as radio options

Datasets that select "yes" should have the geospatial theme applied. 

![Screen Shot 2020-11-25 at 4 03 47 PM](https://user-images.githubusercontent.com/509703/100293224-d947cc00-2f37-11eb-85fc-63047a1337f9.png)

## Acceptance Criteria
- [x] When I go to the metadata form
- [x] Then I do not see the themes field
- [x] And I see a field that says "My dataset is a geospatial dataset" with Yes/No as radio options
- [x] When I choose "yes" and save
- [x] Then I should see geospatial as a theme on the published dataset
- [x] When I choose "no" 
- [x] Then I should not see any theme on the published dataset

## Details / tasks

- [x] Rename Themes field to "My dataset is a geospatial dataset"
- [x] Add "Yes" and "No" options
- [x] Remove helptext and infotexts
- [x] Yes => “geospatial”
- [x] No => empty value
- [x] No radio button should be selected by default

**Comment by kimwdavidson** [comment]
Covering the #430 need for now
