### ISSUE TITLE
EPA Journey Mapping

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#53]
We'll be collecting information about the EPA's processes and needs to add to the product journey map. 

Notes here: 

https://docs.google.com/document/d/1SOmk8rRteOgW1VgN73tYvAIHvcAZZyby6FPVMqaNcXY/edit#

**Comment by kimwdavidson** [comment]
Kim and Hyon to provide availability

**Comment by hkdctol** [comment]
June 6: 12:00 – 4 PM

June 10: 1-4 PM (for EPA, GSA has a conflict 3-4)

June 17: 1-4 PM

if you can pick one we can confirm EPA.

**Comment by rufuspollock** [comment]
FIXED. This happened.
