### ISSUE TITLE
Admin accounts using login.gov for catalog-next.data.gov

### ISSUE THREAD

**Issue by hkdctol** [GSA/datagov-ckan-multi#534]
## User Story

As Data.gov PMO, we want to have all current catalog admin users to have admin accounts on catalog-next.data.gov using login.gov for authentication, so that when we switch to catalog-next as the official Data.gov catalog, admin users are able to manage the catalog. 

## Acceptance Criteria
- [ ] Current catalog admin users (listed in this [doc](https://docs.google.com/spreadsheets/d/14ASz5fJ-DoJ7Y2Tb5MIphkgVBgxgaYZBDmx8uBASQx4/edit?usp=sharing) are able to access the new catalog and have all their admin functions available and authenticate through login.gov

## Details / tasks

- [x] Contact all current users (most are Data.gov PMO) and make sure users have login.gov accounts, and ensure they choose the appropriate 2FA options
- [ ] Recreate the admin accounts for each user in [catalog user list](https://docs.google.com/spreadsheets/d/14ASz5fJ-DoJ7Y2Tb5MIphkgVBgxgaYZBDmx8uBASQx4/edit?usp=sharing) in catalog-next.data.gov

**Comment by mogul** [comment]
Closing in favor of https://github.com/GSA/datagov-deploy/issues/2673
