### ISSUE TITLE
Discovery: CKAN 2.9 upgrade LOE

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#536]
We'd like to t-shirt size the items in this list: https://docs.google.com/spreadsheets/d/13sSxoEntVfSZidMWm9ZCrCf0YN9GDc9ajnDVcf07704/edit#gid=0 so that we can prioritize this work and build a backlog

**Comment by avdata99** [comment]
The documents were completed. We are ready to create an epic and the required stories.
