### ISSUE TITLE
Initial Pass at FedRamp Tailored Template

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#54]

**Comment by adborden** [comment]
@woodt @kimwdavidson can you fill me on what there is to QA here?

**Comment by adborden** [comment]
No need to over think this, is there a link the the template?

**Comment by JJediny** [comment]
https://github.com/GSA/datagov-ckan-multi/blob/master/_drafts/APPENDIX-B-FedRAMP-Tailored.md
