### ISSUE TITLE
CKAN open control reusable component 

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#55]

**Comment by adborden** [comment]
Is there a link for the relevant PR?

**Comment by JJediny** [comment]
https://github.com/GSA/datagov-ckan-multi/tree/master/_data/opencontrol/components/CKAN the issue of having separate yaml files for each still exists and the completeness of the documentation is still open but could close as the initial pass was done

**Comment by adborden** [comment]
Thanks, moving to Done.
