### ISSUE TITLE
Resolve webob dependency vulnerability

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#552]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit)._

**Date of report:** 11/19/2020
**Severity:** moderate
**Due date:** 2/18/2021

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

### Brief description
https://snyk.io/vuln/SNYK-PYTHON-WEBOB-40490
https://github.com/GSA/catalog.data.gov/issues/169

**Comment by adborden** [comment]
If we're unable to upgrade webob, we need to triage an alternative resolution https://github.com/GSA/datagov-deploy/wiki/Dependency-scanning#triage-walkthrough

**Comment by thejuliekramer** [comment]
PR for updating webob and pylons https://github.com/GSA/catalog.data.gov/pull/208

**Comment by thejuliekramer** [comment]
Error  from CKAN core when updating Webob

`ckan_1        | 2021-01-21 16:19:29,146 INFO spawned: 'ckan-worker' with pid 127
ckan_1        | 2021-01-21 16:19:30,147 INFO success: ckan-worker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
ckan_1        | Traceback (most recent call last):
ckan_1        |   File "/usr/bin/paster", line 11, in <module>
ckan_1        |     load_entry_point('PasteScript==2.0.2', 'console_scripts', 'paster')()
ckan_1        |   File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
ckan_1        |     invoke(command, command_name, options, args[1:])
ckan_1        |   File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
ckan_1        |     exit_code = runner.run(args)
ckan_1        |   File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
ckan_1        |     result = self.command()
ckan_1        |   File "/usr/lib/python2.7/site-packages/paste/script/serve.py", line 284, in command
ckan_1        |     relative_to=base, global_conf=vars)
ckan_1        |   File "/usr/lib/python2.7/site-packages/paste/script/serve.py", line 329, in loadapp
ckan_1        |     **kw)
ckan_1        |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 253, in loadapp
ckan_1        |     return loadobj(APP, uri, name=name, **kw)
ckan_1        |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 277, in loadobj
ckan_1        |     global_conf=global_conf)
ckan_1        |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 302, in loadcontext
ckan_1        |     global_conf=global_conf)
ckan_1        |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 326, in _loadconfig
ckan_1        |     return loader.get_context(object_type, name, global_conf)
ckan_1        |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 459, in get_context
ckan_1        |     section)
ckan_1        |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 481, in _context_from_use
ckan_1        |     object_type, name=use, global_conf=global_conf)
ckan_1        |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 412, in get_context
ckan_1        |     global_conf=global_conf)
ckan_1        |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 302, in loadcontext
ckan_1        |     global_conf=global_conf)
ckan_1        |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 334, in _loadegg
ckan_1        |     return loader.get_context(object_type, name, global_conf)
ckan_1        |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 625, in get_context
ckan_1        |     object_type, name=name)
ckan_1        |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 651, in find_egg_entry_point
ckan_1        |     possible.append((entry.load(), protocol, entry.name))
ckan_1        |   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
ckan_1        |     return self.resolve()
ckan_1        |   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
ckan_1        |     module = __import__(self.module_name, fromlist=['__name__'], level=0)
ckan_1        |   File "/srv/app/src/ckan/ckan/config/middleware/__init__.py", line 25, in <module>
ckan_1        |     original_charset__set = webob.request.BaseRequest._charset__set
ckan_1        | AttributeError: type object 'BaseRequest' has no attribute '_charset__set'`

**Comment by thejuliekramer** [comment]
https://docs.ckan.org/en/2.8/contributing/testing.html?highlight=webob#ckan.tests.helpers.webtest_submit notes on Webob

Possible patch fix would be to apply the changes here 

https://github.com/Pylons/webob/commit/97041f58fcee30b37a8c0fba0108cf69c6e01330#diff-04a5fa381537d49ca9b75f0cd624f14f55ec5c2aa14303d358f3f88dca3d3c9aR141

**Comment by avdata99** [comment]
We are using [webob 1.0.8](https://github.com/Pylons/webob/tree/1.0.8/webob) (10 years ago)
If we apply a fix should be on this version

**Comment by thejuliekramer** [comment]
The two files to update  [`webob/descriptors.py`](https://github.com/Pylons/webob/blob/1.0.8/webob/descriptors.py#L61) and  [`webob/exc.py`](https://github.com/Pylons/webob/blob/1.0.8/webob/exc.py#L501) exist in `1.0.8` if  we want to make this change

**Comment by thejuliekramer** [comment]
Adding [webob patch](https://github.com/GSA/webob/tree/ckan-patch) from inventory https://github.com/GSA/inventory-app/blob/master/requirements.txt#L7

**Comment by thejuliekramer** [comment]
PR to upgrade webob with patch https://github.com/GSA/catalog.data.gov/pull/210
