### ISSUE TITLE
Resolve SQLAlchemy dependency vulnerabilities

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#553]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit)._

**Date of report:** 9/10/2020
**Severity:** high
**Due date:** 10/10/2020

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [ ] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

### Brief description
https://snyk.io/vuln/SNYK-PYTHON-SQLALCHEMY-590109
https://github.com/GSA/catalog.data.gov/issues/112

https://snyk.io/vuln/SNYK-PYTHON-SQLALCHEMY-173678
https://github.com/GSA/catalog.data.gov/issues/119

**Comment by adborden** [comment]
If upgrading SQLAlchemy is not an option, we'll have to identify an alternative https://github.com/GSA/datagov-deploy/wiki/Dependency-scanning#triage-walkthrough

**Comment by adborden** [comment]
I've lumped two sqlalchemy issues in here together, but we should split them out if the work is different.

**Comment by thejuliekramer** [comment]
@FuhuXia @jbrown-xentity did you have to make change for this vulnerability in catalog classic?

**Comment by thejuliekramer** [comment]
@avdata99 is going to reach out to the CKAN community to see if anyone has taken steps to tackle this in older versions of CKAN

**Comment by avdata99** [comment]
Following [here](https://github.com/ckan/ckan/issues/5796#issuecomment-758844107) and internally with my team

**Comment by adborden** [comment]
FYI, any exceptions/resolutions we make are documented in the `.snyk` file. For [SNYK-PYTHON-SQLALCHEMY-173678](https://snyk.io/vuln/SNYK-PYTHON-SQLALCHEMY-173678), we determined that [CKAN 2.3 did not use the `group_by` or `order_by` parameters](https://github.com/GSA/catalog-app/blob/master/.snyk#L10-L16) and therefore no fix is needed.

Oddly, [SNYK-PYTHON-SQLALCHEMY-590109](https://snyk.io/vuln/SNYK-PYTHON-SQLALCHEMY-590109) lists a [similar exception](https://github.com/GSA/catalog-app/blob/master/.snyk#L17-L23), but that doesn't make sense regarding the vulnerability description. @pjsharpe07 are you sure that one is correct?

**Comment by adborden** [comment]
One option we discussed was to fork SQLAlchemy and apply this patch https://github.com/sqlalchemy/sqlalchemy/commit/d3ba45c00f83f7d57be5fb5caa7fb27f61624e28 for https://snyk.io/vuln/SNYK-PYTHON-SQLALCHEMY-590109

**Comment by avdata99** [comment]
Moving to TODO since we postposed this
