### ISSUE TITLE
Resource edit does not allow for uploading

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/datagov-ckan-multi#556]
When you edit a dataset that has a resource file, you have the option to edit the resource. However, you cannot upload a file: you can only link to a publicly available resource.

## How to reproduce

1. Go to an inventory instance
2. Create a dataset with a file uploaded from your local machine
3. Click the "Edit" button on the dataset page
4. Go to the resource page
5. Click the "Edit" link
6. See limited options

## Expected behavior

Replacing a dataset from a file upload is an available option

## Actual behavior

Cannot re-upload a resource file (or new version).

**Comment by osahon-okungbowa** [comment]
@cmugisha @anuveyatsu is tackling this now. this bug affects (and was created by) the Resource Editing user story which we recently completed.

**Comment by adborden** [comment]
Looks good!

**Comment by adborden** [comment]
@hkdctol @osahon-okungbowa I also confirmed that when re-uploading the file, the resource Id and the URL do not change 👍
