### ISSUE TITLE
Add ckanext-harvest to CKAN 2.9

### ISSUE THREAD

**Issue by thejuliekramer** [GSA/datagov-ckan-multi#566]
## User Story

As a data.gov developer, I want ckanext-harvest running with CKAN 2.9 and Python 3 so that we can move out of CKAN 2.8 and reduce our technical debt and meet compliance standards.

## Acceptance Criteria
- [ ] Running with Python3
- [ ] Running with CKAN 2.9

## Details / tasks

- [ ] Add ckanext-harvest to CKAN 2.9 branch
- [ ] Upgrade Python version to 3
- [ ] Remove support for CKAN 2.3
- [ ] CI passing in CKAN 2.9

More details [here](https://docs.google.com/spreadsheets/d/13sSxoEntVfSZidMWm9ZCrCf0YN9GDc9ajnDVcf07704/edit#gid=0)

**Comment by adborden** [comment]
Closing since ckanext-harvest already supports CKAN2.9.
