### ISSUE TITLE
ckanext-spatial Py3 + CKAN 2.9 support

### ISSUE THREAD

**Issue by thejuliekramer** [GSA/datagov-ckan-multi#571]
## User Story

As a data.gov developer, I want ckanext-spatial running with CKAN 2.9 and Python 3 so that we can move out of CKAN 2.8 and reduce our technical debt and meet compliance standards.

## Acceptance Criteria
- [ ] WHEN I view CI
  THEN I see a successful job testing the extension under CKAN 2.9
  AND I see a successful job testing the extension under CKAN 2.8
  AND I see a successful job testing the extension under the legacy test environment
- [ ] WHEN I remove the tests
  THEN I see CI fail due to test coverage being below a threshold

## Background

CKAN 2.9 extension [tracker](https://docs.google.com/spreadsheets/d/13sSxoEntVfSZidMWm9ZCrCf0YN9GDc9ajnDVcf07704/edit#gid=0).

## Details / tasks

**ckanext-spatial has an existing branch to support Python 3 https://github.com/ckan/ckanext-spatial/pull/249**

Use the fork of ckanext-spatial for now and see how we can support merging of this PR.

**Comment by jbrown-xentity** [comment]
This is an upstream repo that now supports Py3, nothing to do.
