### ISSUE TITLE
USGS Lidar Point Cloud LAS Harvest Source Not Harvesting

### ISSUE THREAD

**Issue by thejuliekramer** [GSA/datagov-ckan-multi#582]
## How to reproduce

1. Stop all harvest source gather/fetch processes (to free up enough memory to harvest the large source) Gather stage takes up 1/2 of memory on machine.
2. Clear all gather/fetch  queues
3. Run harvest source https://catalog.data.gov/harvest/usgs-lidar-point-cloud-las-harvest-source

## Expected behavior

Harvest source should harvest with 1139371 datasets

## Actual behavior

Harvest source parent collection dataset is not created correctly and displays 0 datasets

## Notes

The last time I tried to harvest this source the url timed out but I was able to gather and fetch in the past.

The harvest source `usgs-lidar-point-cloud-las-harvest-source` is able to gather and fetch with enough memory when it is the only source running on the machine at a time. The memory used is  about 1/2 of the machine's availability.

The harvest source `usgs-lidar-point-cloud-las-harvest-source` is making it through the gather and fetch stages but the collection is not being created correctly and therefore the harvested datasets are not linked to the parent dataset (collection) correctly.

The main collection dataset is created here - https://github.com/GSA/ckanext-geodatagov/blob/master/ckanext/geodatagov/harvesters/waf_collection.py#L79-L102

You can also look up  the existing source in the  database using this query including the collection metadata url of this harvest source  - http://thor-f5.er.usgs.gov/ngtoc/metadata/waf/elevation/lidar_point_cloud/las/

```
SELECT
  key, value
FROM
  harvest_object_extra
WHERE
  key='waf_location'
AND value='http://thor-f5.er.usgs.gov/ngtoc/metadata/waf/elevation/lidar_point_cloud/las/'
```

If we can figure out why the collection parent dataset is not being created correctly I think we can solve this issue.

My next step would be to figure out why url is timing out and then clearing  all of the datasets and starting fresh to see if parent dataset is created correctly

**Comment by hkdctol** [comment]
![USGS4.png](https://images.zenhubusercontent.com/5d374a506df6e4059e63379d/72a3705c-625c-4597-a932-aca1a9739463)

**Comment by hkdctol** [comment]
Closing - a more recent issue #3218 was created so this one is duplicative.
