### ISSUE TITLE
Upgrade ckan-cloud-operator in cluster

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#66]

**Comment by akariv** [comment]
- [ ] Re-install provisioning apps with new infrastructure
- [ ] Add new Jenkins commands
- [ ] Integrate provisioning API with Jenkins

**Comment by akariv** [comment]
Adam Kariv [9:26 AM]
Updated links @JJediny 
- Jenkins: https://cc-p-jenkins.datagov.us/
- Rancher: https://ckan-cloud-rancher.datagov.us/
- Provisioning app: https://ckan-cloud-app-provisioning.datagov.us

Jenkins is currently using Google as an auth provider, Rancher and Provisioning use GitHub as before.
You should have admin access to all systems.

**Comment by adborden** [comment]
@akariv would you please add me as admin to Jenkins?

I noticed that Ori still owns the Google App, can you update that? Would you like me to open a ticket for it?
<img alt="Screenshot from 2019-07-18 14-30-56" src="https://user-images.githubusercontent.com/509703/61493648-f09c9f80-a968-11e9-8785-a429eca74b51.png" width="300" />

**Comment by adborden** [comment]
Also, I may need admin access to the Provisioning app. Not sure if this is a bug or not. My GSA email is a secondary on my GH account, not sure if that's why I'm getting "No Access".
![Screenshot from 2019-07-18 14-34-24](https://user-images.githubusercontent.com/509703/61493797-4ffaaf80-a969-11e9-8e84-81c71eb1f6de.png)

**Comment by adborden** [comment]
To complicate things, looks like GSA is blocking me from logging into Jenkins with my gsa.gov Google Account. @JJediny have you seen this (cloudlock notification) when logging into jenkins?

**Comment by akariv** [comment]
Aaron, I added you to the provisioning app (we're only considering the
primary email atm).
Regarding the Google App owner - I agree we should change that, but let's
open a separate issue for that please.

**Comment by adborden** [comment]
@kimwdavidson this looks good to me. Do I close this out or move this to the Done column?
