### ISSUE TITLE
Julie and Andres set up for Harvester work 

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#71]
Julie and Andres will both:

* [x] Install CKAN Harvester extension
  * [x] Document how this worked in hackmd. Link in this ticket
  * [x] Add feedback to a hackmd about ease of installing harvester extension and link to this ticket
* [x] Install ckanext-datajson extension - http://github.com/gsA/ckanext-datajson/
* [x] Install geodata-gov extension - https://github.com/GSA/ckanext-geodatagov/

**Comment by rufuspollock** [comment]
Andres has got this setup.

**Comment by rufuspollock** [comment]
FIXED. This was done in last sprint.
