### ISSUE TITLE
Part III: automate running harvesting (e.g. jenkins etc) and pushing to metastore

### ISSUE THREAD

**Issue by rufuspollock** [GSA/datagov-ckan-multi#80]
Automate running harvesting (e.g. jenkins etc) and pushing to metastore

## Tasks

* [x] Evaluate task runner options (e.g. jenkins, airflow)
* [x] Implement this
* [x] Implement pushing to metastore (if not already done)

**Comment by rufuspollock** [comment]
We have the airflow job working.

**Comment by avdata99** [comment]
![Selection_2123.png](https://images.zenhubusercontent.com/5d0fa29f8356d802835f2561/9cc98d29-d4b8-4ece-8468-5262adc37cc0)

This is our first _airflow_ script to put all the harvest jobs in a queue:  
https://gitlab.com/datopian/ckan-ng-harvest/blob/develop/automate-tasks/airflow/harvest_with_airflow.py

**Comment by rufuspollock** [comment]
FIXED.
