### ISSUE TITLE
 Part I.b: save to CKAN metastore

### ISSUE THREAD

**Issue by rufuspollock** [GSA/datagov-ckan-multi#81]
This is a raw push - assuming all datasets are new (i.e. without the diffing done in)

**Comment by rufuspollock** [comment]
Work done so far

* Class and function writing to my local CKAN instance
* Create some adapters for translate data.json dataset to CKAN datasets. 
* First test for this adapter

**Comment by rufuspollock** [comment]
We are able to save to CKAN local instance. We need to add resources creation and check all the extras and data saved in the previous CKAN extensions. We need to check all the harvest process with our local CKAN instance.

**Comment by avdata99** [comment]
We added the creation of the resources. Tests at the local CKAN instance are working.  
This is done.
