### ISSUE TITLE
Part IV: integrate with CKAN config

### ISSUE THREAD

**Issue by rufuspollock** [GSA/datagov-ckan-multi#82]
Integrate with config stored in CKAN harvest extension and pushing errors there

**Comment by thejuliekramer** [comment]
@rufuspollock what are you thinking is the plan of action here? Is there a specific API endpoint we can right errors to currently? Right now we can [get the admin users](https://docs.ckan.org/en/2.8/api/#ckan.logic.action.get.user_list) and [send them emails](https://docs.ckan.org/en/2.8/api/#ckan.logic.action.update.send_email_notifications) but I am not sure if this is what you are thinking. Let us know when you can please. CC @kimwdavidson

**Comment by rufuspollock** [comment]
@thejuliekramer so first look at the structure of HarvestGatherError and HarvestObjectError and API for creating them.

Also what is the structure and type of errors we are current getting?

**Comment by thejuliekramer** [comment]
Where is the API for creating them? That is accessible from outside of CKAN? The type of errors are dataset field errors, when missing or invalid. They are currently being ouput to a json file. Is the plan to handle to errors on the CKAN side or in the harvester? Should we send json or some other format to CKAN?

**Comment by rufuspollock** [comment]
@thejuliekramer i don't know if an API is exposed - have you checked the Harvester extension docs and code for this? If not you may only be able to create them from within code.

**Comment by thejuliekramer** [comment]
Yes they use the api I mentioned above, seems like this is the way to go.
