### ISSUE TITLE
Determine optimal upgrade path between new and legacy platform

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#83]
Assess existing functionality
Determine which features can be deprecated or replaced
Which features need to be refactored or rebuilt

**Comment by rufuspollock** [comment]
I'm closing this as done but also opening new item #95 to look further at collections.

Plan as discussed with @adborden is:

* A cut-over to a clean system on v2.8 and reimplement what we need 
* Most important is harvesting => want to see that first … [we are working on that now]
 * data.json
 * then geo harvesters
 * Features like: Retry failed jobs … and more insight into the process. How many jobs are queued up. How many are backed up … 

Then ...

* Theme
* Collections: room to improve/reinvent that feature (data.json harvester ties in …) -- further discussion on this
* Legacy formats: a lot of old datasets with old metadata
  * E.g. have a lot of ISO 19139 … and could convert that into something newer …  Whilst retaining the original source … (“show your work”)
