### ISSUE TITLE
CKAN Cloud login redirects to *.ckan.io with invalid certificate

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#84]
I tried logging into the CKAN Cloud at https://ckan-cloud-rancher.datagov.us/. On clicking login, I was redirected to [datagov-ckan-cloud-management.ckan.io](https://datagov-ckan-cloud-management.ckan.io) which was serving a certificate for [ckan-cloud-rancher.datagov.us](https://ckan-cloud-rancher.datagov.us/).

The redirect provides a clue. Looks like we need to update the configuration in the GitHub application.

> https://datagov-ckan-cloud-management.ckan.io/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch

![Screenshot from 2019-07-17 08-53-53](https://user-images.githubusercontent.com/509703/61391117-e13a2b00-a870-11e9-8daa-3303fd69b2a4.png)

![Screenshot from 2019-07-17 08-54-00](https://user-images.githubusercontent.com/509703/61391135-e7c8a280-a870-11e9-8b86-efb503932064.png)

## Reproduction

1. Open https://ckan-cloud-rancher.datagov.us/, unauthenticated.
1. Click Login with GitHub

## Expected

Login through GH's OAuth

## Actual

Certificate error.

**Comment by JJediny** [comment]
I just updated the url in the github Oauth developer setting to use the datagov.us callback, this should be working shortly

**Comment by adborden** [comment]
Thanks! That did it.
