### ISSUE TITLE
Evaluate CKAN logging w.r.t. NIST 800-53 AU family "content of audit log" control

### ISSUE THREAD

**Issue by woodt** [GSA/datagov-ckan-multi#85]
Evaluate out of the box CKAN logging against AU-3 guidelines.  Develop remediation (aka logging enhancement) proposal if needed.

Likely outcomes:
- no additional work needed
- OR, spec for patch or extension to CKAN to improve logging detail to better meet AU controls.

For example, here is the AU-3 description:

The information system generates audit records containing information that establishes what type of event occurred, when the event occurred, where the event occurred, the source of the event, the outcome of the event, and the identity of any individuals or subjects associated with the event.

For a low impact system (as is current plan), AU-3, AU-8, and AU-12 are the relevant information system controls.

**Comment by woodt** [comment]
# Control description

[AC-2]

The information system generates audit records containing information that 
establishes what type of event occurred, when the event occurred, where the
event occurred, the source of the event, the outcome of the event, and the
identity of any individuals or subjects associated with the event.

## Event types

* Administrative privilege use
* Password changes
* Creation of privileged user accounts
* Changes to privilege level
* Failed login attempts

# Current logging situation

Unfortunately, very little of the existing logging contributes useful
information to an audit record.

Some controllers resport validation errors that might indicated
attacks.  E.g., the *package* controller rejects and logs invalid
search requests.

The authenticator does log (at DEBUG level, which is probably
incorrect) failed authentication attempts.


# Approaches

## General requirements
* Use Python logging to allow post-installation configuration
* Log to stdout to facilitate log aggregation in a container execution environment

CKAN activity stream maintenance appears to be a good "cross-cutting"
function in the CKAN system to add additional logging that can address
the audit log requirements listed above.  Improving the existing
authenticator logging to 


## Approach 1

Patch CKAN `model/activity.log` to inject logging requests.  Patch other CKAN core elements as needed.

Advantage: very simple and reliable

Disadvantage: requires a patch to CKAN core

## Approach 2

Write a logging extension.  Use the plugin toolkits IMapper interface to watch
for the creation of Activity objects.

Advantage: no patch required; can be distributed/maintained separately from CKAN

Disadvantage: concept demonstration required to make sure that the SQLAlchemy mapper
event mechanism is sufficient, and Activity objects as presented to the plugin are
adequate for logging.

*After investigation*, it seems that the plugin mapper extension is only available for certain
CKAN model classes (this restriction doesn't seem to be documented anywhere.)  The Activity
class is *not* one of them.  I don't think this approach will be feasible.

# Recommendations

* [Approach 1] Generate a patch to CKAN core to add audit logging to address the requirements listed
in the first section.  The activity module would be a good place to start.

* Document proper configuration of the Python logging system to meet audit logging requirements.

* [Stretch] Investigate whether a structured logging formatter (e.g., Python structlog) would
"work and play well" in the ELK logging world within the Kubernetes cluster.

# Issues

* The activity stream does include quite a bit of information, but it is decoupled from
web request handling, so, for example, it might be difficult to include source IP address,
which would be very useful.

**Comment by adborden** [comment]
Thanks @woodt. I agree that Approach 1 sounds the most promising. I would add that we include automated tests so that the logging doesn't disappear in some kind of future refactor.

Would there be any benefit to having another CKAN expert review this? The issue about not being able to connect the activity to the request information seems like something we want to address.

**Comment by tkprmr** [comment]
@jqnatividad to follow up with @rufuspollock on this to see if he can help to review

**Comment by jqnatividad** [comment]
After some discussion, Approach 1 is the recommended approach per @woodt's evaluation.

As it happens, there is already ongoing work with another major CKAN user to make the activity stream module more robust (more detailed activity stream; capturing metadata changes; etc.)

Will harmonize/leverage existing work with NIST requirements.

**Comment by kimwdavidson** [comment]
@jqnatividad and @woodt to create tickets for implementing Approach 1
