### ISSUE TITLE
Determine and document current state of the CI/CD pipeline

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#88]
Ensure all team members are synced on the current state of the pipeline. Likely an initial call to get synced at a high level, followed by follow up conversations and questions

- [x] Rufus to add documentation to this ticket
- [x] Team to read documentation
- [x] Extended call on Thurs Aug 8th to discuss

**Comment by rufuspollock** [comment]
@woodt which CI/CD pipeline? For CKAN for CCO for ...?

**Comment by kimwdavidson** [comment]
Everyone to review documentation by August 6th

**Comment by rufuspollock** [comment]
CKAN CI can be seen (using circleci!) is here: https://github.com/ckan/ckan

ATM CCO does not have automated tests (they are being worked on in #75) - https://github.com/ViderumGlobal/ckan-cloud-operator

**Comment by woodt** [comment]
(Thanks Rufus ...)  So I have been thinking about how to capture the CI/CD pipeline info.  Here's my pass at a way of structuring the information:  https://docs.google.com/spreadsheets/d/1nFnu_5R_kVAyuwpS2EFRSEUsq54uUCjFD5Zibhanrxk/edit?usp=sharing

**Comment by rufuspollock** [comment]
@woodt thanks - i have requested access to that doc.

**Comment by rufuspollock** [comment]
@woodt i have had a look and looks fine. Not sure if much to comment on yet :-)

**Comment by woodt** [comment]
I think we should consider this story complete when we finish the spreadsheet.

**Comment by kimwdavidson** [comment]
@woodt can this ticket be closed?

**Comment by tkprmr** [comment]
@woodt I am closing this ticket for now since all task items are completed and checked marked as listed in the description. 
we can open a new ticket if required in case anything found in the review
