### ISSUE TITLE
RDS went offline on the cluster

### ISSUE THREAD

**Issue by akariv** [GSA/datagov-ckan-multi#99]
All instances in the cluster are currently down because RDS is not responding.
(credentials for RDS can be found in each of the instances secrets)

## How to reproduce

1. Description of steps to reproduce the issue.
All ckan pods in all instances are in a crashloop because of this.

## Expected behavior

RDS should respond and ckan instances can connect to it.

---

We need to understand what happened and how we prevent this from happening again.

**Comment by kimwdavidson** [comment]
@akariv and @woodt don't have access. @adborden to take a look and see about getting them access.

**Comment by adborden** [comment]
The RDS instance is back online.

**Comment by aluminiumgeek** [comment]
@adborden could you describe what happened with the instance, please?

**Comment by adborden** [comment]
The instance ran out of space. It was configured for 20GB, I bumped it up to 40GB. The instance was manually stood up.
